# Mount drive and bucket
Todo: Remove in public version

In [1]:
# Check if the notebook is run in Google Colab
import sys

COLAB = 'google.colab' in sys.modules

In [2]:
import sys
import datetime
import logging

# nblog = open(f"/content/bigdata/nb_{datetime.datetime.utcnow().strftime('%Y%m%d_%H%M')}.log", "a+")
# print(nblog)
# sys.stdout.echo = nblog
# sys.stderr.echo = nblog

#get_ipython().log.handlers[0].stream = nblog
#get_ipython().log.setLevel(logging.INFO)

%autosave 60

Autosaving every 60 seconds


In [3]:
# if COLAB:
#   from google.colab import drive
#   drive.mount('/content/drive')

In [4]:
if COLAB:
  from google.colab import auth
  auth.authenticate_user()
else:
    print("Run the command!")
  #Todo #bring the command inside the notebook
  #run this terminal inside docker: gcloud auth login b.girsule@gmail.com --no-launch-browser

Run the command!


In [5]:
# Todo: Check if possible in local docker
# from google.cloud import storage

In [6]:
# Check if the tf version is 2.10.0, this is required to use the 'ignore_class' in the  SparseCategoricalCrossentropy
import tensorflow as tf

if '2.10.0' != tf.__version__:
  !pip uninstall tensorflow -y
  !pip install tensorflow-gpu==2.10.0
  please_restart_the_runtime
else:
  print("TF Version is 2.10.0, ok!")

2023-03-29 13:07:27.718253: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-29 13:07:27.955000: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-03-29 13:07:28.098245: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-29 13:07:28.959160: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: li

TF Version is 2.10.0, ok!


In [7]:
from tensorflow import keras
# import tensorflow_gcs_config
from tensorflow.python.lib.io import file_io

from keras.layers import Input, Dense, Flatten #, ReLU, Add, Flatten, Concatenate, LayerNormalization, UpSampling2D, Activation, LSTM, Multiply, Dropout, Reshape, Permute, BatchNormalization, MaxPooling1D, AveragePooling1D, MaxPooling3D, AveragePooling2D, LayerNormalization, MaxPooling2D
from keras.models import Model
from keras.optimizers import Adam

In [8]:
import os
from os import listdir
from os.path import isfile, join

In [9]:
import pandas as pd
import numpy as np
import copy
import matplotlib.pyplot as plt
from tqdm import tqdm
import pickle
import gc
import random

In [10]:
# Set the google cloud bucket data
project_id = 'tweetprediction'
bucket_name = 'crypto_nlp_training'

In [11]:
# Set the checkpoint path for saving train progress
if COLAB:
    CHECKPOINT_PATH = f"gs://{bucket_name}/chk/"
else:
    CHECKPOINT_PATH = f"/content/bigdata/chk/"

In [12]:
# Check if the notebook is run in google colab, if so, clone the repo
if COLAB:
    print("Running in Colab")

    # Clone the whole repo to get all data and code if not already done
    if not os.path.exists("/content/CryptoCrystalBall"):
      !git clone https://github.com/girsigit/CryptoCrystalBall

      # cd into the notebooks directory --> Necessary to match all paths for importing
    #%cd /content/CryptoCrystalBall/JupyterDocker/notebooks
    %cd /content

In [13]:
# Try importing the Ta-Lib library, if this fails, try to install it and
# import it again afterwards
try:
    import talib
except:
    !wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
    !tar -xzvf ta-lib-0.4.0-src.tar.gz
    %cd ta-lib
    !./configure --prefix=/usr
    !make
    !make install
    !pip install Ta-Lib
    %cd ..

    import talib

In [14]:
try:
  from transformers import TFRobertaModel, RobertaConfig
except:
  # Important!: Version 4.23 does not work on TPU
  !pip install transformers==4.22

  from transformers import TFRobertaModel, RobertaConfig

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.


Moving 0 files to the new cache system


0it [00:00, ?it/s]

In [15]:
# !pip uninstall -y tensorboard-plugin-profile

In [16]:
# # Required to do profiling
# !pip install tensorboard-plugin-profile

In [17]:
import logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)

---
# Add custom import path for DataStreamCreator and IndicatorCalculator

These libs are not in the standard python directory, so their paths have to be added to the import paths

In [18]:
# # Get the current directory
# current_dir = os.getcwd()
# current_dir_splitted = current_dir.split(os.sep)

# Todo: is inside /content/CB in local docker
current_dir_splitted = ["", "content"]
current_dir_splitted

['', 'content']

In [19]:
# Create the import directories for the DataStreamCreator and the IndicatorCalculator
dsc_dir = '/content/CryptoCrystalBall/DataStreamCreator'
print(f"dsc_dir: {dsc_dir}")

ind_dir = '/content/CryptoCrystalBall/IndicatorCalculator'
print(f"ind_dir: {ind_dir}")

# Add them to the import paths
sys.path.insert(0, dsc_dir)
sys.path.insert(0, ind_dir)

dsc_dir: /content/CryptoCrystalBall/DataStreamCreator
ind_dir: /content/CryptoCrystalBall/IndicatorCalculator


In [20]:
# Import the actual classes
from IndicatorCalculator import IndicatorCalculator
import DataStreamCreator

---
# Define all the parameters and variables

In [21]:
# Define the tick data path
DATA_PATH = os.path.join(os.sep, *current_dir_splitted, 'DemoData')
print(f"DATA_PATH: {DATA_PATH}")

DATA_PATH: /content/DemoData


In [22]:
# Define the chart image save path
IMG_SAVE_PATH = os.path.join(os.sep, *current_dir_splitted, 'Documentation', 'Images')
print(f"IMG_SAVE_PATH: {IMG_SAVE_PATH}")

IMG_SAVE_PATH: /content/Documentation/Images


In [23]:
# Define a global random seed
RANDOM_SEED = 42

# Set the seed in np
np.random.seed(RANDOM_SEED)

In [24]:
# X_BLOCK_LENGHT defines how far into the past a 'slice of a chart' shall be
# See: https://github.com/girsigit/CryptoCrystalBall/tree/main/DataStreamCreator#xblockgenerator
X_BLOCK_LENGHT = 256

In [25]:
# How many examples shall be processed at the same time, limited by GPU memory
BATCH_SIZE = 384

In [26]:
# A fixed number of features is used
FEATURES = 160

In [27]:
# Finanical indicator timespans
# See: https://github.com/girsigit/CryptoCrystalBall/tree/main/IndicatorCalculator
SHORTSPAN = 7
MIDSPAN = 38
LONGSPAN = 50

In [28]:
# Additional settings for the data stream
# For this notebook, the calculation of pattern indicators is turned off
DATA_STREAM_PARAMETERS = {
    "calcPatternIndicators": False, # No patterns are used
    "calcVolumeInidators": False, # No volume indicators, these are wide spread and may disturb the classifer
    "dropna": True # Drop all tick/indicator table rows containing nan values instead of just replacing them by 0 (which would lead to wrong predictions)
}

# Load the train dataset

In [29]:
# Get train file names - Only pick the ones ending with -USDT to prevent
# influence between different currencies
TRAIN_PATH = "/content/dataset/etffancy"

# Get all file names
ALL_FILES = [os.path.join(TRAIN_PATH,f) for f in listdir(TRAIN_PATH) if isfile(join(TRAIN_PATH, f)) and ".csv" in f ]

# Sort them (as a stable basis for randomizing afterwards)
ALL_FILES = sorted(ALL_FILES)

print(f"The train dataset contains {len(ALL_FILES)} files.")
print(ALL_FILES[:3])

The train dataset contains 1064 files.
['/content/dataset/etffancy/DE0002635265.csv', '/content/dataset/etffancy/DE0002635273.csv', '/content/dataset/etffancy/DE0002635281.csv']


In [30]:
# Split the dataset into train, test (trade algorithm train) and eval (trade algorithm test)
SPLIT_RANDOM_SEED = 666
TRAIN_SET_SIZE = 0.5
TEST_SET_SIZE = 0.25
# EVAL_SET_SIZE: The rest

random.Random(SPLIT_RANDOM_SEED).shuffle(ALL_FILES)

train_split_index = int(len(ALL_FILES) * TRAIN_SET_SIZE)
print(f"train_split_index: {train_split_index}")

test_split_index = int(len(ALL_FILES) * (TRAIN_SET_SIZE + TEST_SET_SIZE))
print(f"test_split_index: {test_split_index}")

TRAIN_FILES = ALL_FILES[:train_split_index]
TEST_FILES = ALL_FILES[train_split_index:test_split_index]
EVAL_FILES = ALL_FILES[test_split_index:]

train_split_index: 532
test_split_index: 798


---
# Prepare data source

For training a neural network, first the data source has to be prepared. For this purpose, the method `FileListToDataStream` from the `DataStreamCreator` class is used. This method creates a stream of `X-Block` and `y-data` arrays out of a list of .csv file names, pointing to tick tables (called `EXAMPLE_FILE_PATHS` in this example). For details about `X-Blocks` and `y-data`, please refer to the documentation of the `XBlockGenerator` and the `YDataGenerator` under https://github.com/girsigit/CryptoCrystalBall/tree/main/DataStreamCreator.

<br>

WRONG  WRONG  WRONG  WRONG  WRONG  WRONG  WRONG  WRONG  
Target values (y-data) from the data generator would not be necessary in this notebook, but since it cannot be switched off, the future direction and its derviation of the price have been chosen in `Y_TYPE_DICT` since they are not expensive to compute. A switch flag will be added in a future release.

In [31]:
# FPNWithAttention_5_ETF_Trained_Past_Future_Gain_TrainSetOnly_GPU_64LB
Y_TYPE_DICT = copy.deepcopy(DataStreamCreator.YDataGenerator.PARAM_DICT_TEMPLATE_Y_DATA_TYPE_PAST_FUTURE_GAIN)
Y_TYPE_DICT["gain_timespan"] = 60
# Y_TYPE_DICT["direction_ma_timespan"] = 14
# Y_TYPE_DICT["derivation_ma_timespan"] = 14
Y_TYPE_DICT

{'dataType': 3,
 'gain_timespan': 60,
 'direction_ma_timespan': 48,
 'derivation_ma_timespan': 48}

In [32]:
TARGET_FEATURE_CNT = 160 #256

In [33]:
XShape = (BATCH_SIZE, X_BLOCK_LENGHT, TARGET_FEATURE_CNT)
XShape

(384, 256, 160)

In [34]:
import numpy as np
a = np.array([1,2,3,4])
a[[1,3]]

array([2, 4])

In [35]:
# A python generator function has to be applied on the dataStream

def pythonGeneratorSignalsTraining():
  # Initialize the FileListToDataStream generator
  dataStreamTraining = DataStreamCreator.FileListToDataStream(fileList = TRAIN_FILES,
                                                      batch_size = BATCH_SIZE,
                                                      X_Block_lenght = X_BLOCK_LENGHT,
                                                      y_type_dict=Y_TYPE_DICT,
                                                      shuffle=True,
                                                      parallel_generators = np.min([BATCH_SIZE, 8]),
                                                      random_seed = RANDOM_SEED,
                                                      **DATA_STREAM_PARAMETERS
                                                      )

  # This while has to integrated into the FileListToDataStream method
  while True:  
    try:
      ne = next(dataStreamTraining)
      _X = ne['X']
      _y = ne['y'][:,[1,3]]
    
      # Limit the y signal to avoid excess
      _y /= 10.0
      _y = np.clip(_y, -10.0, 10.0)
        
      # 'Blow up' the X array to a 2**n size
      #_X_new = np.zeros((_X.shape[0], _X.shape[1], TARGET_FEATURE_CNT))
      #_X_new[:,:,:_X.shape[2]] = _X

      yield (_X, _y)
    except StopIteration as si:
      logging.warning("StopIteration in pythonGenerator")
      logging.warning(si)
      return

In [36]:
# Create a Tensorflow dataset out of the python generator, which can be fed to the network
tfGenTraining = tf.data.Dataset.from_generator(pythonGeneratorSignalsTraining, 
                                               output_types = (tf.float32, tf.float32),
                                               output_shapes=(
                                                   (BATCH_SIZE, X_BLOCK_LENGHT, TARGET_FEATURE_CNT),
                                                   (BATCH_SIZE, 2)
                                                   )
                                               )

tfGenTraining = tfGenTraining.prefetch(buffer_size=32)
tfGenTraining

2023-03-29 13:07:32.956232: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-29 13:07:33.024532: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-29 13:07:33.024695: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-29 13:07:33.026917: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compi

<PrefetchDataset element_spec=(TensorSpec(shape=(384, 256, 160), dtype=tf.float32, name=None), TensorSpec(shape=(384, 2), dtype=tf.float32, name=None))>

---
# Create the neural network

In the example, two Conv1D pyramids are used to extract features at different levels out of the feature and the time dimension.

It is also possible to use different architecures, like LSTM, Conv2D, Attention-Based ones or even NLP-based models. I have already tried many different ones and will publish them into the model zoo.

```
Todo: Create Model Zoo
```

```
Todo: Create Image of netwrok structure
```

In [37]:
# from keras.layers import Input, Dense, ReLU, Add, Flatten, Concatenate, LayerNormalization, UpSampling2D, Activation, LSTM, Multiply, Dropout, Reshape, Permute, BatchNormalization, MaxPooling1D, AveragePooling1D, MaxPooling3D, AveragePooling2D, LayerNormalization, MaxPooling2D, UnitNormalization, UpSampling1D
from keras.layers import UnitNormalization, Permute, Conv1D, UpSampling1D, Add, LSTM, Concatenate, Multiply, Activation, Attention, Dropout

In [38]:
# Create the FPNWithFScaledInput model
# Infos about the feature pyramid: https://jonathan-hui.medium.com/understanding-feature-pyramid-networks-for-object-detection-fpn-45b227b9106c

def CreateModelFPNWithAttention():
  # Define model parameters
  mp = {
      "NAME": "FPNWithAttentionBiggerTimebased",
      "VERSION": "2_FutureOnly_60days",
      "CNN_INITIAL_FILTERS": 64,
      "CNN_EXTRACTOR_LAYERS": 6,
      "CNN_INITIAL_KERNEL_SIZE": 2,
      "CNN_MAX_KERNEL_SIZE": 8,
      "FEATURE_PYRAMID_START_INDEX": 2,
      "HEAD_LSTM_SIZE": 64,
      "HEAD_DENSE_SIZE": 32
      }
  
  # Create the model input  
  inputTicksAndIndicators = Input(shape=(X_BLOCK_LENGHT, TARGET_FEATURE_CNT), name='inputTicksAndIndicators', dtype='float32')
  inputTicksAndIndicators = Dropout(0.1, name='inputDropout')(inputTicksAndIndicators)

  # Normalize the input data, as it has a wide value spread (range of 1e8)
  normalized = UnitNormalization(name="UnitNormalizationInput", axis=-2)(inputTicksAndIndicators)

  # Permute it to Conv over Features
  #normalized = Permute((2, 1), name="PermuteInput")(normalized)

  # ----------------------------------------------------------------------------

  # As an example a 1D-CNN pyramid is used to extract higher-level features out
  # of the indicator+tick dimension
  conv_layers = []
  aligned_layers = []
  feature_map_layers = []
  anti_aliased_layers = []
  anti_aliased_pyramid_indices = []
  regressor_layers = []

  finalFilters = mp["CNN_INITIAL_FILTERS"] * 2**(mp["FEATURE_PYRAMID_START_INDEX"])
  print(finalFilters) 

  for i in range(mp["CNN_EXTRACTOR_LAYERS"]):
    if 0 == i:
      source_layer = normalized
    else:
      source_layer = feature_conv
    
    filters = int(mp["CNN_INITIAL_FILTERS"]*(2**i))
    kernel_size = mp["CNN_INITIAL_KERNEL_SIZE"]*(2**i)
    kernel_size = int(np.min([mp["CNN_MAX_KERNEL_SIZE"], kernel_size]))
    strides = int(np.min([2,kernel_size]))

    print(f"Step {i}, using {filters} filters with a kernel size of {kernel_size} at strides of {strides}")

    # Create the feature extraction convolution
    res_net_element = Conv1D(filters=source_layer.shape[-1],
                          kernel_size=kernel_size,
                          strides=1, 
                          padding="same",
                          name=f"ResNet_{i}_Conv1D_1")(source_layer)
    
    res_net_element = Activation("relu",
                              name=f"ResNet_{i}_ReLU")(res_net_element)
    
    res_net_element = Conv1D(filters=source_layer.shape[-1],
                          kernel_size=kernel_size,
                          strides=1, 
                          padding="same",
                          name=f"ResNet_{i}_Conv1D_2")(res_net_element)
    
    res_net_element = Add(name=f"ResNet_{i}_Add")([res_net_element, source_layer])
        
    feature_conv = Conv1D(filters=filters,
                          kernel_size=kernel_size,
                          strides=strides, 
                          padding="same",
                          name=f"ResNet_{i}_Feature_Conv1D_FilterDimReduction")(res_net_element)

    attention_map = Attention(name=f"Attention_Layer_{i}")([feature_conv,feature_conv])
    print(f"attention_map.shape: {attention_map.shape}")

    feature_conv_attentioned = Multiply(name=f"Multiply_Apply_Attention_{i}")([feature_conv, attention_map])
    print(f"feature_conv_attentioned.shape: {feature_conv_attentioned.shape}")
    
    conv_layers.append(feature_conv_attentioned)

    # Apply the feature extraction pyramid
    if mp["FEATURE_PYRAMID_START_INDEX"] <= i:
      # Apply a 1x1 convolution to align the channel depth    
      if feature_conv_attentioned.shape[-1] != finalFilters:
        aligned_layer = Conv1D(filters=finalFilters,
                              kernel_size=1,
                              strides=1,
                              padding="same",
                              name=f"Channel_Depth_Alignment_{i}")(feature_conv_attentioned)
      else:
        aligned_layer = feature_conv_attentioned
      
      aligned_layers.append(aligned_layer)

  # Go top-down through the aligned_layers to create the feature_map_layers
  for i in range(mp["CNN_EXTRACTOR_LAYERS"]-1, mp["FEATURE_PYRAMID_START_INDEX"]-1, -1):
    aligned_layers_index = i - mp["FEATURE_PYRAMID_START_INDEX"]
    aligned_layer = aligned_layers[aligned_layers_index]

    print(f"Building feature_map_layers, step {i}. Shape of aligned_layer: {aligned_layer.shape}")

    # The highest-filtered layer is taken as feature map directly
    if i == mp["CNN_EXTRACTOR_LAYERS"]-1:
      feature_map_layers.append(aligned_layer)
      anti_aliased_layers.append(feature_map_layers[-1])
    else:
      # Take the last feature_map_layer and scale it by two
      upsampled = UpSampling1D(size=2,
                               name=f"Pyramid_Upsampling_{i}")(feature_map_layers[-1])

      # Add the aligned_layer
      added = Add(name=f"Pyramid_Add_{i}")([upsampled, aligned_layer])

      # Append as new feature_map_layer
      feature_map_layers.append(added)

      # Apply a convolution with a kernel size of 3 to "reduce the aliasing effect"
      anti_aliased_layer = Conv1D(filters=feature_map_layers[-1].shape[-1],
                                  kernel_size=3,
                                  strides=1,
                                  padding="same",
                                  name=f"Anti_Alias_{i}")(feature_map_layers[-1])

      anti_aliased_layers.append(anti_aliased_layer)

    # Helper storage to keep pyramid index consistent, also in predictor/regressor
    anti_aliased_pyramid_indices.append(i)

  # Apply the predictor head to each feature dimension layer
  for n in range(len(anti_aliased_layers)):
    predictor_input = anti_aliased_layers[n]

    # Get the pyramid index
    pyramid_index = anti_aliased_pyramid_indices[n]

    # Permute the Conv output back
    predictor_input = Permute((2, 1), name=f"PermutePredictorInput_{pyramid_index}")(predictor_input)

    predictor = LSTM(units=mp["HEAD_LSTM_SIZE"],
                     name=f"Predictor_Head_{pyramid_index}_LSTM")(predictor_input)
    
    # Direction and derivation regressor
    regressor = Dense(units=mp["HEAD_DENSE_SIZE"],
                      name=f"Predictor_Head_{pyramid_index}_Dense_Regressor",
                      activation='relu')(predictor)
    
    regressor_layers.append(regressor)
  
  # Add all regressors together
  regressor_conced = Concatenate(name="Concatenate_regressors")(regressor_layers)
  #regressor_conced = Dense(regressor_conced.shape[1], name="Combined_Regressor_1")(regressor_conced)
  #regressor_conced = Dense(regressor_conced.shape[1], name="Combined_Regressor_2")(regressor_conced)

  # The output are two values (direction and derivation) in the range [-1.0, 1.0]
  output = Dense(2, activation="tanh", name="Output")(regressor_conced)
  outputs = [output]

  # Combine it all into a model object
  model = Model(inputs=inputTicksAndIndicators, outputs=outputs, name=mp["NAME"] + "_" + str(mp["VERSION"]))

  return model, mp

model, model_config = CreateModelFPNWithAttention()
print(model_config)
model.summary(line_length=220)

256
Step 0, using 64 filters with a kernel size of 2 at strides of 2
attention_map.shape: (None, 128, 64)
feature_conv_attentioned.shape: (None, 128, 64)
Step 1, using 128 filters with a kernel size of 4 at strides of 2
attention_map.shape: (None, 64, 128)
feature_conv_attentioned.shape: (None, 64, 128)
Step 2, using 256 filters with a kernel size of 8 at strides of 2
attention_map.shape: (None, 32, 256)
feature_conv_attentioned.shape: (None, 32, 256)
Step 3, using 512 filters with a kernel size of 8 at strides of 2
attention_map.shape: (None, 16, 512)
feature_conv_attentioned.shape: (None, 16, 512)
Step 4, using 1024 filters with a kernel size of 8 at strides of 2
attention_map.shape: (None, 8, 1024)
feature_conv_attentioned.shape: (None, 8, 1024)
Step 5, using 2048 filters with a kernel size of 8 at strides of 2
attention_map.shape: (None, 4, 2048)
feature_conv_attentioned.shape: (None, 4, 2048)
Building feature_map_layers, step 5. Shape of aligned_layer: (None, 4, 256)
Building feat

# Train the model

### Train strategy in the paper
https://huggingface.co/roberta-base

The model was trained on 1024 V100 GPUs for 500K steps with a batch size of 8K and a sequence length of 512. The optimizer used is Adam with a learning rate of 6e-4, β1=0.9\beta_{1} = 0.9β1​=0.9, β2=0.98\beta_{2} = 0.98β2​=0.98 and ϵ=1e−6\epsilon = 1e-6ϵ=1e−6, a weight decay of 0.01, learning rate warmup for 24,000 steps and linear decay of the learning rate after.

In [39]:
CHKPNT_NAME = f"{model.name}_GPU_{X_BLOCK_LENGHT}LB"
CHKPNT_NAME

'FPNWithAttentionBiggerTimebased_2_FutureOnly_60days_GPU_256LB'

In [40]:
# Set an optimizer
optimizer = Adam(
    learning_rate=1e-03,
    epsilon=1e-06,
    beta_1=0.9,
    beta_2=0.98,
    decay=0.01)

In [41]:
# Compile the model
model.compile(
    optimizer = optimizer,
    loss = ["mse"], 
    metrics=["mae"])

In [42]:
#@title CustomCallback
class CustomCallback(tf.keras.callbacks.Callback):
  def __init__(self, save_freq, val_freq, checkpoint_path, model_name, epoch_add=0):
    self.save_freq = save_freq
    self.val_freq = val_freq
    self.checkpoint_path = checkpoint_path
    self.model_name = model_name
    self.current_epoch = 0
    self.epoch_add = epoch_add

  def on_epoch_begin(self, epoch, logs=None):
    self.current_epoch = epoch + self.epoch_add
    # keys = list(logs.keys())
    # print("Start epoch {} of training; got log keys: {}".format(epoch, keys))

  def on_epoch_end(self, epoch, logs=None):
    self.saveTheModel(-1, logs)

  def on_train_batch_end(self, batch, logs=None):
    self.saveTheModel(batch, logs)

  def saveTheModel(self, batch, logs=None):
    if (0 < batch and 0 == batch % self.save_freq) or (0 > batch):
      logging.info(str(datetime.datetime.utcnow()))
    
      if 0 > batch:
        _save_folder = os.path.join(self.checkpoint_path,
                                    self.model_name,
                                    "cp_daily_valid_{:02d}_end".format(self.current_epoch)
                                    )
      else:
        _save_folder = os.path.join(self.checkpoint_path,
                                    self.model_name,
                                    "cp_daily_valid_{:02d}_{:05d}".format(self.current_epoch, batch)
                                    )
      
      fp = os.path.join(_save_folder, "model.h5")
      model.save(fp)
      logging.info(f"Saved model to '{fp}'")
      
      # Save optimizer config
      # c = copy.deepcopy(self.model.optimizer.get_config())

      fp = os.path.join(_save_folder, "c.pickle")
      with file_io.FileIO(fp, mode='wb+') as handle:
        pickle.dump(self.model.optimizer.get_config(), handle, protocol=pickle.HIGHEST_PROTOCOL)
        
      logging.info(f"Saved optimizer config to '{fp}'")

      # Save optimizer weights
      # w = copy.deepcopy(self.model.optimizer.get_weights())

      fp = os.path.join(_save_folder, "w.pickle")
      with open(fp, "wb") as handle:
        # with file_io.FileIO(fp, mode='wb+') as handle:
        pickle.dump(self.model.optimizer.get_weights(), handle, protocol=pickle.HIGHEST_PROTOCOL)
      
      logging.info(f"Saved optimizer weights to '{fp}'")
        
      logging.info(f"Did a gc collect: {gc.collect()}")

    # if 0 < batch and 0 == batch % self.val_freq:
    #   print("-------------------------EVAL-------------------------")
    #   model.evaluate(tfgenTest)
    #   print("\n-------------------------EVAL-------------------------")

In [43]:
gc.collect()

9886

In [44]:
epoch_add = 0

In [45]:
CALLBACK_EVERY_N_BATCHES = 2000

In [47]:
cc = CustomCallback(checkpoint_path = CHECKPOINT_PATH,
                    model_name = CHKPNT_NAME,
                    save_freq = CALLBACK_EVERY_N_BATCHES,
                    val_freq = CALLBACK_EVERY_N_BATCHES,
                    epoch_add = epoch_add)

In [48]:
# Load the TensorBoard notebook extension
%load_ext tensorboard

In [49]:
%reload_ext tensorboard

The TensorBoard UI is displayed in a browser window. In this colab, perform the following steps to prepare to capture profile information.
1.  Click on the dropdown menu box on the top right side and scroll down and click PROFILE. A new window appears that shows: **No profile data was found** at the top.
1.  Click on the CAPTURE PROFILE button. A new dialog appears. The top input line shows: **Profile Service URL or TPU name**. Copy and paste the Profile Service URL (the service_addr value shown before launching TensorBoard) into the top input line. While still on the dialog box, start the training with the next step.
1.  Click on the next colab cell to start training the model.
1.  Watch the output from the training until several epochs have completed. This allows time for the profile data to start being collected. Return to the dialog box and click on the CAPTURE button. If the capture succeeds, the page will auto refresh and redirect you to the profiling results.

In [50]:
# Todo: Create more elegant solution
log_dir = "gs://ticks_with_indicators_with_volume/logs/TPU/" + CHKPNT_NAME + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

if not COLAB:
    log_dir = os.path.join("/content/bigdata/log",log_dir.split("/")[-1])

log_dir

'/content/bigdata/log/FPNWithAttentionBiggerTimebased_2_FutureOnly_60days_GPU_256LB20230329-130752'

In [51]:
import datetime

tensorboard_callback = tf.keras.callbacks.TensorBoard(
    log_dir=log_dir,
    histogram_freq=1,
    update_freq=CALLBACK_EVERY_N_BATCHES,
    profile_batch=(5,100)
    )

2023-03-29 13:07:52.838221: I tensorflow/core/profiler/lib/profiler_session.cc:101] Profiler session initializing.
2023-03-29 13:07:52.838241: I tensorflow/core/profiler/lib/profiler_session.cc:116] Profiler session started.
2023-03-29 13:07:52.838994: I tensorflow/core/profiler/backends/gpu/cupti_tracer.cc:1664] Profiler found 1 GPUs
2023-03-29 13:07:52.839234: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcupti.so.11.2'; dlerror: libcupti.so.11.2: cannot open shared object file: No such file or directory
2023-03-29 13:07:52.941421: I tensorflow/core/profiler/lib/profiler_session.cc:128] Profiler session tear down.
2023-03-29 13:07:52.941608: I tensorflow/core/profiler/backends/gpu/cupti_tracer.cc:1798] CUPTI activity buffer flushed


In [52]:
#model.load_weights("/content/bigdata/chk/FPNWithAttentionBigger_3_FutureOnly_GPU_256LB/cp_daily_valid_33_end/model.h5")

In [53]:
%tensorboard --logdir $log_dir --host 0.0.0.0 --port 6006

In [54]:
model.fit(tfGenTraining,
          epochs=1,
          verbose = 1,
          callbacks=[tensorboard_callback, cc])

INFO:root:File 'IE00B6X2VY59.csv' loaded, 531 left
INFO:root:File 'IE00BYXVGZ48.csv' loaded, 530 left
INFO:root:File 'DE000A0F5UF5.csv' loaded, 529 left
INFO:root:File 'DE000ETFL441.csv' loaded, 528 left
INFO:root:File 'LU1781541179.csv' loaded, 527 left
INFO:root:File 'LU1650487926.csv' loaded, 526 left
INFO:root:File 'LU1285960032.csv' loaded, 525 left
INFO:root:File 'IE00B1FZSD53.csv' loaded, 524 left
2023-03-29 13:08:10.017700: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8700
2023-03-29 13:08:11.364852: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
INFO:root:File 'IE00B5KQNG97.csv' loaded, 523 left
INFO:root:File 'IE00BYM31M36.csv' loaded, 522 left


      4/Unknown - 26s 244ms/step - loss: 6.5225e-05 - mae: 0.0053

2023-03-29 13:08:21.997919: I tensorflow/core/profiler/lib/profiler_session.cc:101] Profiler session initializing.
2023-03-29 13:08:21.997946: I tensorflow/core/profiler/lib/profiler_session.cc:116] Profiler session started.


      6/Unknown - 27s 326ms/step - loss: 4.6180e-05 - mae: 0.0043WARNING:tensorflow:Callback method `on_train_batch_end` is slow compared to the batch time (batch time: 0.1178s vs `on_train_batch_end` time: 0.1288s). Check your callbacks.


      7/Unknown - 27s 314ms/step - loss: 4.0685e-05 - mae: 0.0040

INFO:root:File 'LU2082996542.csv' loaded, 521 left


     14/Unknown - 30s 306ms/step - loss: 2.5746e-05 - mae: 0.0032

INFO:root:File 'IE00BF4G7076.csv' loaded, 520 left


     22/Unknown - 32s 315ms/step - loss: 1.9830e-05 - mae: 0.0029

INFO:root:File 'IE00BQN1K786.csv' loaded, 519 left


     30/Unknown - 35s 328ms/step - loss: 1.6701e-05 - mae: 0.0027

INFO:root:File 'LU0136240974.csv' loaded, 518 left


     41/Unknown - 40s 357ms/step - loss: 0.0018 - mae: 0.0053

INFO:root:File 'IE00BLDGH447.csv' loaded, 517 left


     43/Unknown - 41s 359ms/step - loss: 0.0017 - mae: 0.0055

INFO:root:File 'IE00BFTWP510.csv' loaded, 516 left


     47/Unknown - 43s 372ms/step - loss: 0.0015 - mae: 0.0054

INFO:root:File 'IE00BQT3WG13.csv' loaded, 515 left


     55/Unknown - 45s 366ms/step - loss: 0.0013 - mae: 0.0056

INFO:root:File 'LU1407888053.csv' loaded, 514 left


     73/Unknown - 51s 349ms/step - loss: 0.0010 - mae: 0.0050

INFO:root:File 'IE00BMYDM794.csv' loaded, 513 left


     78/Unknown - 52s 347ms/step - loss: 9.5297e-04 - mae: 0.0048

INFO:root:File 'IE00B441G979.csv' loaded, 512 left


     83/Unknown - 55s 358ms/step - loss: 8.9625e-04 - mae: 0.0047

INFO:root:File 'IE00B8X9NY41.csv' loaded, 511 left


     86/Unknown - 57s 365ms/step - loss: 8.6523e-04 - mae: 0.0046

INFO:root:File 'IE00BMDH1538.csv' loaded, 510 left


     91/Unknown - 58s 361ms/step - loss: 8.1819e-04 - mae: 0.0044

INFO:root:File 'IE00BLF7VX27.csv' loaded, 509 left


     95/Unknown - 60s 361ms/step - loss: 7.8403e-04 - mae: 0.0043

INFO:root:File 'IE00BYMS5W68.csv' loaded, 508 left


     99/Unknown - 61s 362ms/step - loss: 7.5252e-04 - mae: 0.0042

2023-03-29 13:08:56.968126: I tensorflow/core/profiler/lib/profiler_session.cc:67] Profiler session collecting data.
2023-03-29 13:08:56.970911: I tensorflow/core/profiler/backends/gpu/cupti_tracer.cc:1798] CUPTI activity buffer flushed
2023-03-29 13:08:57.307680: I tensorflow/core/profiler/backends/gpu/cupti_collector.cc:521]  GpuTracer has collected 585505 callback api events and 588402 activity events. 
2023-03-29 13:09:02.160443: I tensorflow/core/profiler/lib/profiler_session.cc:128] Profiler session tear down.
2023-03-29 13:09:06.370125: I tensorflow/core/profiler/rpc/client/save_profile.cc:136] Creating directory: /content/bigdata/log/FPNWithAttentionBiggerTimebased_2_FutureOnly_60days_GPU_256LB20230329-130752/plugins/profile/2023_03_29_13_09_02

2023-03-29 13:09:10.286056: I tensorflow/core/profiler/rpc/client/save_profile.cc:142] Dumped gzipped tool data for trace.json.gz to /content/bigdata/log/FPNWithAttentionBiggerTimebased_2_FutureOnly_60days_GPU_256LB20230329-130752/plugi

    100/Unknown - 79s 536ms/step - loss: 7.4507e-04 - mae: 0.0042

INFO:root:File 'LU1079842321.csv' loaded, 507 left


    101/Unknown - 80s 541ms/step - loss: 7.3780e-04 - mae: 0.0042

INFO:root:File 'IE00BKVL7778.csv' loaded, 506 left


    104/Unknown - 81s 537ms/step - loss: 7.1701e-04 - mae: 0.0041

INFO:root:File 'LU1681045537.csv' loaded, 505 left


    108/Unknown - 83s 538ms/step - loss: 6.9065e-04 - mae: 0.0041

INFO:root:File 'IE00B60SX287.csv' loaded, 504 left


    118/Unknown - 87s 526ms/step - loss: 6.3307e-04 - mae: 0.0039

INFO:root:File 'IE00BJXRT698.csv' loaded in retry loop, 503 left


    135/Unknown - 92s 493ms/step - loss: 5.5449e-04 - mae: 0.0037

INFO:root:File 'IE00B40B8R38.csv' loaded, 502 left


    140/Unknown - 93s 488ms/step - loss: 5.3491e-04 - mae: 0.0036

INFO:root:File 'IE00BYTH5T38.csv' loaded, 501 left


    142/Unknown - 94s 486ms/step - loss: 5.2745e-04 - mae: 0.0036

INFO:root:File 'IE00077FRP95.csv' loaded, 500 left


    146/Unknown - 95s 480ms/step - loss: 5.1335e-04 - mae: 0.0036

INFO:root:File 'DE0002635273.csv' loaded, 499 left


    150/Unknown - 98s 485ms/step - loss: 4.9987e-04 - mae: 0.0035

INFO:root:File 'IE00B5WHFQ43.csv' loaded in retry loop, 498 left


    158/Unknown - 101s 482ms/step - loss: 4.7500e-04 - mae: 0.0035

INFO:root:File 'IE00BKVL7D31.csv' loaded, 497 left


    169/Unknown - 104s 468ms/step - loss: 4.4453e-04 - mae: 0.0034

INFO:root:File 'LU2356220926.csv' loaded, 496 left


    174/Unknown - 106s 463ms/step - loss: 4.3192e-04 - mae: 0.0033

INFO:root:File 'IE00BYZK4883.csv' loaded, 495 left


    176/Unknown - 107s 464ms/step - loss: 4.2709e-04 - mae: 0.0033

INFO:root:File 'IE00B4YBJ215.csv' loaded, 494 left


    178/Unknown - 108s 468ms/step - loss: 4.2241e-04 - mae: 0.0033

INFO:root:File 'IE00BMDKNW35.csv' loaded, 493 left


    185/Unknown - 111s 461ms/step - loss: 4.0660e-04 - mae: 0.0032

INFO:root:File 'LU1769088581.csv' loaded, 492 left


    189/Unknown - 112s 459ms/step - loss: 3.9813e-04 - mae: 0.0032

INFO:root:File 'IE00B6YX5B26.csv' loaded, 491 left


    203/Unknown - 117s 451ms/step - loss: 3.7126e-04 - mae: 0.0031

INFO:root:File 'LU2023678449.csv' loaded, 490 left


    206/Unknown - 118s 450ms/step - loss: 3.6600e-04 - mae: 0.0031

INFO:root:File 'LU1953188833.csv' loaded, 489 left


    216/Unknown - 121s 442ms/step - loss: 3.5079e-04 - mae: 0.0031

INFO:root:File 'LU1861134382.csv' loaded, 488 left


    218/Unknown - 122s 443ms/step - loss: 3.4764e-04 - mae: 0.0031

INFO:root:File 'IE00BLRPN388.csv' loaded, 487 left


    220/Unknown - 122s 442ms/step - loss: 3.4455e-04 - mae: 0.0031

INFO:root:File 'LU1781540957.csv' loaded, 486 left


    228/Unknown - 125s 438ms/step - loss: 3.3295e-04 - mae: 0.0031

INFO:root:File 'IE00BD9MMF62.csv' loaded, 485 left


    231/Unknown - 126s 437ms/step - loss: 3.2874e-04 - mae: 0.0031

INFO:root:File 'LU1806495575.csv' loaded, 484 left


    238/Unknown - 129s 434ms/step - loss: 3.1935e-04 - mae: 0.0030

INFO:root:File 'DE000A0H08N1.csv' loaded, 483 left


    246/Unknown - 133s 437ms/step - loss: 3.0937e-04 - mae: 0.0030

INFO:root:File 'LU2082997946.csv' loaded, 482 left


    252/Unknown - 135s 434ms/step - loss: 3.0230e-04 - mae: 0.0030

INFO:root:File 'DE0002635307.csv' loaded, 481 left


    255/Unknown - 137s 439ms/step - loss: 2.9886e-04 - mae: 0.0030

INFO:root:File 'IE00BWBXM492.csv' loaded, 480 left


    260/Unknown - 139s 438ms/step - loss: 2.9323e-04 - mae: 0.0030

INFO:root:File 'IE00BC7GZJ81.csv' loaded, 479 left


    262/Unknown - 140s 440ms/step - loss: 2.9105e-04 - mae: 0.0030

INFO:root:File 'LU0832436512.csv' loaded, 478 left


    264/Unknown - 142s 442ms/step - loss: 2.8891e-04 - mae: 0.0030

INFO:root:File 'IE00BD3V0B10.csv' loaded, 477 left


    272/Unknown - 144s 438ms/step - loss: 2.8271e-04 - mae: 0.0030

INFO:root:File 'IE00BYTRR863.csv' loaded, 476 left


    279/Unknown - 147s 436ms/step - loss: 2.7586e-04 - mae: 0.0030

INFO:root:File 'DE000ETFL037.csv' loaded, 475 left


    294/Unknown - 152s 431ms/step - loss: 0.0079 - mae: 0.0080

INFO:root:File 'IE00B60SX170.csv' loaded in retry loop, 474 left


    308/Unknown - 157s 427ms/step - loss: 0.0077 - mae: 0.0092

INFO:root:File 'LU1215454460.csv' loaded, 473 left


    316/Unknown - 159s 425ms/step - loss: 0.0076 - mae: 0.0102

INFO:root:File 'IE00BJXRZ273.csv' loaded, 472 left


    327/Unknown - 162s 419ms/step - loss: 0.0074 - mae: 0.0101

INFO:root:File 'IE00BKT1CS59.csv' loaded, 471 left


    334/Unknown - 164s 417ms/step - loss: 0.0072 - mae: 0.0101

INFO:root:File 'LU1287023342.csv' loaded, 470 left


    336/Unknown - 166s 418ms/step - loss: 0.0072 - mae: 0.0100

INFO:root:File 'LU1981859819.csv' loaded, 469 left


    346/Unknown - 169s 416ms/step - loss: 0.0070 - mae: 0.0099

INFO:root:File 'LU1841731745.csv' loaded, 468 left


    356/Unknown - 172s 412ms/step - loss: 0.0068 - mae: 0.0097

INFO:root:File 'IE000L5NW549.csv' loaded, 467 left


    360/Unknown - 173s 411ms/step - loss: 0.0067 - mae: 0.0096

INFO:root:File 'IE00B4LN9N13.csv' loaded, 466 left


    361/Unknown - 174s 413ms/step - loss: 0.0067 - mae: 0.0096

INFO:root:File 'FR0010869578.csv' loaded, 465 left


    372/Unknown - 178s 412ms/step - loss: 0.0065 - mae: 0.0094

INFO:root:File 'IE00BCRY6557.csv' loaded, 464 left


    383/Unknown - 182s 410ms/step - loss: 0.0063 - mae: 0.0093

INFO:root:File 'LU2090062949.csv' loaded, 463 left


    389/Unknown - 184s 408ms/step - loss: 0.0062 - mae: 0.0092

INFO:root:File 'IE00B5M1WJ87.csv' loaded, 462 left


    393/Unknown - 186s 409ms/step - loss: 0.0061 - mae: 0.0092

INFO:root:File 'IE00B1TXHL60.csv' loaded, 461 left


    395/Unknown - 188s 412ms/step - loss: 0.0061 - mae: 0.0092

INFO:root:File 'IE00BMQ8YK98.csv' loaded, 460 left


    399/Unknown - 189s 411ms/step - loss: 0.0060 - mae: 0.0091

INFO:root:File 'IE00BKWQ0D84.csv' loaded, 459 left


    400/Unknown - 190s 412ms/step - loss: 0.0060 - mae: 0.0091

INFO:root:File 'LU1525418643.csv' loaded, 458 left


    402/Unknown - 192s 414ms/step - loss: 0.0060 - mae: 0.0091

INFO:root:File 'IE00BJK9H753.csv' loaded, 457 left


    423/Unknown - 197s 407ms/step - loss: 0.0057 - mae: 0.0087

INFO:root:File 'LU2082997359.csv' loaded, 456 left


    432/Unknown - 200s 404ms/step - loss: 0.0059 - mae: 0.0090

INFO:root:File 'IE00B6YX5L24.csv' loaded, 455 left


    436/Unknown - 202s 405ms/step - loss: 0.0059 - mae: 0.0092

INFO:root:File 'LU2082996898.csv' loaded, 454 left


    438/Unknown - 203s 405ms/step - loss: 0.0059 - mae: 0.0092

INFO:root:File 'IE00B3B8PX14.csv' loaded, 453 left


    441/Unknown - 205s 407ms/step - loss: 0.0059 - mae: 0.0092

INFO:root:File 'IE00B02KXL92.csv' loaded, 452 left


    452/Unknown - 209s 407ms/step - loss: 0.0057 - mae: 0.0091

INFO:root:File 'LU1681041205.csv' loaded, 451 left


    456/Unknown - 211s 408ms/step - loss: 0.0057 - mae: 0.0091

INFO:root:File 'IE00BHZPJ015.csv' loaded, 450 left


    459/Unknown - 212s 408ms/step - loss: 0.0091 - mae: 0.0106

INFO:root:File 'LU0959210278.csv' loaded, 449 left


    471/Unknown - 216s 406ms/step - loss: 0.0091 - mae: 0.0114

INFO:root:File 'IE000KPJJWM6.csv' loaded, 448 left


    472/Unknown - 217s 406ms/step - loss: 0.0091 - mae: 0.0114

INFO:root:File 'IE00BKWQ0M75.csv' loaded, 447 left


    481/Unknown - 220s 404ms/step - loss: 0.0089 - mae: 0.0114

INFO:root:File 'IE000NDWFGA5.csv' loaded, 446 left


    482/Unknown - 220s 404ms/step - loss: 0.0089 - mae: 0.0114

INFO:root:File 'IE00BYSZ5R67.csv' loaded, 445 left


    511/Unknown - 228s 397ms/step - loss: 0.0084 - mae: 0.0109

INFO:root:File 'IE00BGJWWY63.csv' loaded, 444 left


    513/Unknown - 229s 397ms/step - loss: 0.0084 - mae: 0.0109

INFO:root:File 'IE00BJK9HD13.csv' loaded, 443 left


    525/Unknown - 232s 394ms/step - loss: 0.0082 - mae: 0.0107

INFO:root:File 'IE00BMH5Y871.csv' loaded, 442 left


    527/Unknown - 233s 394ms/step - loss: 0.0082 - mae: 0.0106

INFO:root:File 'IE00BYV1Y969.csv' loaded, 441 left


    529/Unknown - 234s 395ms/step - loss: 0.0081 - mae: 0.0106

INFO:root:File 'LU0392496427.csv' loaded, 440 left


    532/Unknown - 236s 396ms/step - loss: 0.0081 - mae: 0.0106

INFO:root:File 'IE00BNDS1P30.csv' loaded, 439 left


    535/Unknown - 237s 396ms/step - loss: 0.0080 - mae: 0.0105

INFO:root:File 'IE00B3CNHJ55.csv' loaded, 438 left


    540/Unknown - 240s 397ms/step - loss: 0.0080 - mae: 0.0104

INFO:root:File 'DE000A0H08H3.csv' loaded, 437 left


    543/Unknown - 242s 400ms/step - loss: 0.0079 - mae: 0.0104

INFO:root:File 'IE00BHXMHL11.csv' loaded, 436 left


    547/Unknown - 244s 400ms/step - loss: 0.0079 - mae: 0.0103

INFO:root:File 'IE00BYTRRC02.csv' loaded, 435 left


    553/Unknown - 246s 399ms/step - loss: 0.0078 - mae: 0.0102

INFO:root:File 'DE000ETF7011.csv' loaded, 434 left


    568/Unknown - 250s 396ms/step - loss: 0.0076 - mae: 0.0100

INFO:root:File 'IE00BYPLS672.csv' loaded, 433 left


    570/Unknown - 252s 397ms/step - loss: 0.0076 - mae: 0.0100

INFO:root:File 'IE00B2NPL135.csv' loaded, 432 left


    583/Unknown - 256s 396ms/step - loss: 0.0074 - mae: 0.0098

INFO:root:File 'DE000ETFL565.csv' loaded, 431 left


    592/Unknown - 259s 395ms/step - loss: 0.0073 - mae: 0.0097

INFO:root:File 'IE00BYSX4846.csv' loaded, 430 left


    598/Unknown - 261s 394ms/step - loss: 0.0072 - mae: 0.0096

INFO:root:File 'IE0032895942.csv' loaded, 429 left


    600/Unknown - 263s 397ms/step - loss: 0.0072 - mae: 0.0096

INFO:root:File 'LU1230561679.csv' loaded, 428 left


    619/Unknown - 269s 393ms/step - loss: 0.0070 - mae: 0.0094

INFO:root:File 'IE00BZ048462.csv' loaded, 427 left


    627/Unknown - 271s 392ms/step - loss: 0.0069 - mae: 0.0093

INFO:root:File 'LU1829218822.csv' loaded, 426 left


    636/Unknown - 275s 392ms/step - loss: 0.0068 - mae: 0.0092

INFO:root:File 'LU2182388400.csv' loaded, 425 left


    642/Unknown - 277s 392ms/step - loss: 0.0067 - mae: 0.0091

INFO:root:File 'IE00BM8R0N95.csv' loaded, 424 left


    647/Unknown - 278s 391ms/step - loss: 0.0067 - mae: 0.0091

INFO:root:File 'IE00BK5BR626.csv' loaded, 423 left


    650/Unknown - 279s 391ms/step - loss: 0.0066 - mae: 0.0090

INFO:root:File 'IE00B4L5YC18.csv' loaded, 422 left


    653/Unknown - 281s 392ms/step - loss: 0.0066 - mae: 0.0090

INFO:root:File 'LU2197908721.csv' loaded in retry loop, 421 left


    657/Unknown - 282s 391ms/step - loss: 0.0066 - mae: 0.0090

INFO:root:File 'IE00B1FZS798.csv' loaded, 420 left


    666/Unknown - 286s 392ms/step - loss: 0.0065 - mae: 0.0089

INFO:root:File 'IE00BYV1YH46.csv' loaded, 419 left


    669/Unknown - 288s 392ms/step - loss: 0.0064 - mae: 0.0088

INFO:root:File 'IE00B3YLTY66.csv' loaded, 418 left


    679/Unknown - 291s 392ms/step - loss: 0.0063 - mae: 0.0087

INFO:root:File 'IE00BL0BMZ89.csv' loaded, 417 left


    692/Unknown - 295s 389ms/step - loss: 0.0062 - mae: 0.0086

INFO:root:File 'IE000EBFYWX3.csv' loaded, 416 left


    695/Unknown - 296s 389ms/step - loss: 0.0062 - mae: 0.0086

INFO:root:File 'LU1829219390.csv' loaded, 415 left


    697/Unknown - 296s 389ms/step - loss: 0.0062 - mae: 0.0086

INFO:root:File 'DE0005933931.csv' loaded, 414 left


    703/Unknown - 300s 391ms/step - loss: 0.0061 - mae: 0.0085

INFO:root:File 'IE00BFYN8Y92.csv' loaded, 413 left


    725/Unknown - 306s 388ms/step - loss: 0.0059 - mae: 0.0083

INFO:root:File 'DE0006289499.csv' loaded, 412 left


    729/Unknown - 309s 389ms/step - loss: 0.0059 - mae: 0.0083

INFO:root:File 'LU1812090543.csv' loaded, 411 left


    744/Unknown - 314s 388ms/step - loss: 0.0058 - mae: 0.0082

INFO:root:File 'DE0006289390.csv' loaded, 410 left


    750/Unknown - 317s 390ms/step - loss: 0.0057 - mae: 0.0081

INFO:root:File 'IE00BM9GRM34.csv' loaded, 409 left


    756/Unknown - 319s 389ms/step - loss: 0.0057 - mae: 0.0081

INFO:root:File 'DE0002635299.csv' loaded, 408 left


    760/Unknown - 322s 390ms/step - loss: 0.0057 - mae: 0.0081

INFO:root:File 'LU1377382368.csv' loaded, 407 left


    763/Unknown - 323s 391ms/step - loss: 0.0056 - mae: 0.0080

INFO:root:File 'LU1437015735.csv' loaded, 406 left


    777/Unknown - 327s 389ms/step - loss: 0.0055 - mae: 0.0079

INFO:root:File 'IE00B7452L46.csv' loaded, 405 left


    796/Unknown - 333s 387ms/step - loss: 0.0054 - mae: 0.0078

INFO:root:File 'IE00BYTRRB94.csv' loaded, 404 left


    802/Unknown - 335s 387ms/step - loss: 0.0054 - mae: 0.0077

INFO:root:File 'IE00BHZRQY00.csv' loaded, 403 left


    813/Unknown - 339s 385ms/step - loss: 0.0053 - mae: 0.0077

INFO:root:File 'LU1437018168.csv' loaded, 402 left


    824/Unknown - 342s 384ms/step - loss: 0.0052 - mae: 0.0076

INFO:root:File 'LU1291098827.csv' loaded, 401 left


    841/Unknown - 347s 382ms/step - loss: 0.0051 - mae: 0.0075

INFO:root:File 'LU1681042609.csv' loaded in retry loop, 400 left


    852/Unknown - 351s 382ms/step - loss: 0.0051 - mae: 0.0074

INFO:root:File 'LU1681047319.csv' loaded, 399 left


    856/Unknown - 353s 383ms/step - loss: 0.0050 - mae: 0.0074

INFO:root:File 'LU1681044480.csv' loaded, 398 left


    858/Unknown - 354s 383ms/step - loss: 0.0050 - mae: 0.0074

INFO:root:File 'IE00BKWQ0F09.csv' loaded, 397 left


    869/Unknown - 358s 383ms/step - loss: 0.0050 - mae: 0.0073

INFO:root:File 'DE000A0Q4R36.csv' loaded, 396 left


    874/Unknown - 362s 385ms/step - loss: 0.0049 - mae: 0.0073

INFO:root:File 'LU1900066975.csv' loaded, 395 left


    885/Unknown - 366s 385ms/step - loss: 0.0049 - mae: 0.0072

INFO:root:File 'LU2109786827.csv' loaded, 394 left


    899/Unknown - 370s 383ms/step - loss: 0.0048 - mae: 0.0072

INFO:root:File 'IE00B4L5Y983.csv' loaded, 393 left


    902/Unknown - 372s 384ms/step - loss: 0.0048 - mae: 0.0072

INFO:root:File 'IE00BZ4BMM98.csv' loaded, 392 left


    915/Unknown - 376s 383ms/step - loss: 0.0047 - mae: 0.0071

INFO:root:File 'FR0011475078.csv' loaded, 391 left


    937/Unknown - 382s 381ms/step - loss: 0.0046 - mae: 0.0070

INFO:root:File 'IE00B5MTYK77.csv' loaded, 390 left


    941/Unknown - 384s 382ms/step - loss: 0.0046 - mae: 0.0070

INFO:root:File 'LU0629460089.csv' loaded, 389 left


    945/Unknown - 386s 382ms/step - loss: 0.0046 - mae: 0.0069

INFO:root:File 'IE00BJK9H860.csv' loaded, 388 left


    949/Unknown - 388s 382ms/step - loss: 0.0045 - mae: 0.0069

INFO:root:File 'IE00BWTNM966.csv' loaded, 387 left


    968/Unknown - 393s 380ms/step - loss: 0.0045 - mae: 0.0068

INFO:root:File 'IE00B52SF786.csv' loaded, 386 left


    982/Unknown - 397s 379ms/step - loss: 0.0044 - mae: 0.0067

INFO:root:File 'IE00BKWQ0P07.csv' loaded, 385 left


    989/Unknown - 400s 379ms/step - loss: 0.0044 - mae: 0.0067

INFO:root:File 'LU1650491795.csv' loaded, 384 left


    993/Unknown - 401s 379ms/step - loss: 0.0043 - mae: 0.0067

INFO:root:File 'IE00BHJYDV33.csv' loaded, 383 left


    995/Unknown - 402s 379ms/step - loss: 0.0043 - mae: 0.0067

INFO:root:File 'IE00BYZK4669.csv' loaded, 382 left


   1004/Unknown - 405s 378ms/step - loss: 0.0043 - mae: 0.0066

INFO:root:File 'IE00B1FZS350.csv' loaded, 381 left


   1019/Unknown - 410s 378ms/step - loss: 0.0042 - mae: 0.0066

INFO:root:File 'IE00BLRPRR04.csv' loaded, 380 left


   1024/Unknown - 412s 377ms/step - loss: 0.0042 - mae: 0.0066

INFO:root:File 'LU0603940916.csv' loaded, 379 left


   1026/Unknown - 413s 378ms/step - loss: 0.0042 - mae: 0.0065

INFO:root:File 'IE00B979GK47.csv' loaded, 378 left


   1028/Unknown - 414s 378ms/step - loss: 0.0042 - mae: 0.0065

INFO:root:File 'IE00BYPC1H27.csv' loaded, 377 left


   1039/Unknown - 417s 377ms/step - loss: 0.0041 - mae: 0.0065

INFO:root:File 'DE000ETFL482.csv' loaded, 376 left


   1040/Unknown - 418s 378ms/step - loss: 0.0041 - mae: 0.0065

INFO:root:File 'LU2056739464.csv' loaded, 375 left


   1044/Unknown - 420s 378ms/step - loss: 0.0041 - mae: 0.0065

INFO:root:File 'IE000ST40PX8.csv' loaded, 374 left


   1045/Unknown - 420s 378ms/step - loss: 0.0041 - mae: 0.0065

INFO:root:File 'IE00BQN1K901.csv' loaded, 373 left


   1052/Unknown - 423s 378ms/step - loss: 0.0041 - mae: 0.0064

INFO:root:File 'IE00BKWQ0C77.csv' loaded, 372 left


   1054/Unknown - 423s 377ms/step - loss: 0.0041 - mae: 0.0064

INFO:root:File 'IE00BJQRDM08.csv' loaded, 371 left


   1060/Unknown - 426s 378ms/step - loss: 0.0041 - mae: 0.0064

INFO:root:File 'IE00B8FHGS14.csv' loaded, 370 left


   1067/Unknown - 429s 378ms/step - loss: 0.0040 - mae: 0.0064

INFO:root:File 'IE00B1FZS913.csv' loaded, 369 left


   1076/Unknown - 432s 378ms/step - loss: 0.0040 - mae: 0.0063

INFO:root:File 'LU2198883410.csv' loaded, 368 left


   1089/Unknown - 436s 377ms/step - loss: 0.0040 - mae: 0.0063

INFO:root:File 'IE00B5MTZM66.csv' loaded, 367 left


   1093/Unknown - 438s 378ms/step - loss: 0.0039 - mae: 0.0063

INFO:root:File 'IE00B1W57M07.csv' loaded, 366 left


   1101/Unknown - 442s 378ms/step - loss: 0.0039 - mae: 0.0063

INFO:root:File 'IE00BMDBMT65.csv' loaded, 365 left


   1110/Unknown - 444s 378ms/step - loss: 0.0039 - mae: 0.0062

INFO:root:File 'LU1681039134.csv' loaded, 364 left


   1113/Unknown - 446s 378ms/step - loss: 0.0039 - mae: 0.0062

INFO:root:File 'LU1681041544.csv' loaded, 363 left


   1115/Unknown - 448s 379ms/step - loss: 0.0039 - mae: 0.0062

INFO:root:File 'IE00B8GF1M35.csv' loaded, 362 left


   1127/Unknown - 452s 379ms/step - loss: 0.0038 - mae: 0.0062

INFO:root:File 'FR0010361683.csv' loaded, 361 left


   1133/Unknown - 455s 379ms/step - loss: 0.0038 - mae: 0.0062

INFO:root:File 'IE00BDDRF478.csv' loaded, 360 left


   1157/Unknown - 461s 377ms/step - loss: 0.0037 - mae: 0.0061

INFO:root:File 'IE00BGBN6P67.csv' loaded, 359 left


   1162/Unknown - 463s 377ms/step - loss: 0.0037 - mae: 0.0061

INFO:root:File 'LU1650488494.csv' loaded, 358 left


   1180/Unknown - 469s 376ms/step - loss: 0.0037 - mae: 0.0060

INFO:root:File 'LU1681045024.csv' loaded, 357 left


   1182/Unknown - 471s 377ms/step - loss: 0.0037 - mae: 0.0060

INFO:root:File 'IE00BYXVGY31.csv' loaded, 356 left


   1183/Unknown - 472s 377ms/step - loss: 0.0036 - mae: 0.0060

INFO:root:File 'IE00BFNM3B99.csv' loaded, 355 left


   1186/Unknown - 473s 378ms/step - loss: 0.0036 - mae: 0.0060

INFO:root:File 'IE00BHZRQZ17.csv' loaded, 354 left


   1203/Unknown - 478s 376ms/step - loss: 0.0036 - mae: 0.0059

INFO:root:File 'IE0032077012.csv' loaded, 353 left


   1207/Unknown - 481s 378ms/step - loss: 0.0036 - mae: 0.0059

INFO:root:File 'IE00BFXR5W90.csv' loaded, 352 left


   1209/Unknown - 482s 378ms/step - loss: 0.0036 - mae: 0.0059

INFO:root:File 'LU2244386053.csv' loaded, 351 left


   1215/Unknown - 484s 377ms/step - loss: 0.0036 - mae: 0.0059

INFO:root:File 'IE00B3VTML14.csv' loaded, 350 left


   1219/Unknown - 486s 378ms/step - loss: 0.0035 - mae: 0.0059

INFO:root:File 'FR0007056841.csv' loaded, 349 left


   1223/Unknown - 489s 379ms/step - loss: 0.0035 - mae: 0.0059

INFO:root:File 'IE00B23LNQ02.csv' loaded, 348 left


   1236/Unknown - 494s 379ms/step - loss: 0.0035 - mae: 0.0058

INFO:root:File 'IE00BG5J1M21.csv' loaded, 347 left


   1243/Unknown - 496s 379ms/step - loss: 0.0035 - mae: 0.0058

INFO:root:File 'IE00BMFNW783.csv' loaded, 346 left


   1250/Unknown - 498s 378ms/step - loss: 0.0035 - mae: 0.0058

INFO:root:File 'DE000ETF7037.csv' loaded, 345 left


   1255/Unknown - 500s 378ms/step - loss: 0.0034 - mae: 0.0058

INFO:root:File 'FR0011550185.csv' loaded, 344 left


   1268/Unknown - 504s 377ms/step - loss: 0.0034 - mae: 0.0058

INFO:root:File 'IE000XGNMWE1.csv' loaded, 343 left


   1271/Unknown - 505s 377ms/step - loss: 0.0034 - mae: 0.0057

INFO:root:File 'LU1215461325.csv' loaded, 342 left


   1283/Unknown - 508s 377ms/step - loss: 0.0034 - mae: 0.0057

INFO:root:File 'DE000A0D8Q31.csv' loaded, 341 left


   1301/Unknown - 515s 376ms/step - loss: 0.0033 - mae: 0.0057

INFO:root:File 'LU1437017350.csv' loaded, 340 left


   1313/Unknown - 518s 375ms/step - loss: 0.0033 - mae: 0.0056

INFO:root:File 'IE00B14X4N27.csv' loaded, 339 left


   1319/Unknown - 521s 376ms/step - loss: 0.0033 - mae: 0.0056

INFO:root:File 'LU1681043599.csv' loaded, 338 left


   1320/Unknown - 522s 376ms/step - loss: 0.0033 - mae: 0.0056

INFO:root:File 'IE00BKP5L730.csv' loaded, 337 left


   1331/Unknown - 526s 376ms/step - loss: 0.0032 - mae: 0.0056

INFO:root:File 'IE00B5MTYL84.csv' loaded, 336 left


   1339/Unknown - 529s 376ms/step - loss: 0.0032 - mae: 0.0056

INFO:root:File 'IE00BYTH5R14.csv' loaded, 335 left


   1340/Unknown - 530s 376ms/step - loss: 0.0032 - mae: 0.0056

INFO:root:File 'LU0136234068.csv' loaded, 334 left


   1348/Unknown - 534s 377ms/step - loss: 0.0032 - mae: 0.0055

INFO:root:File 'IE00BFNM3F38.csv' loaded, 333 left


   1353/Unknown - 536s 377ms/step - loss: 0.0032 - mae: 0.0055

INFO:root:File 'IE00B4WXJG34.csv' loaded, 332 left


   1373/Unknown - 542s 376ms/step - loss: 0.0031 - mae: 0.0055

INFO:root:File 'IE00B4WXJH41.csv' loaded, 331 left


   1379/Unknown - 545s 377ms/step - loss: 0.0031 - mae: 0.0055

INFO:root:File 'IE00BDDRDW15.csv' loaded, 330 left


   1403/Unknown - 551s 375ms/step - loss: 0.0031 - mae: 0.0054

INFO:root:File 'LU1681041627.csv' loaded, 329 left


   1405/Unknown - 553s 376ms/step - loss: 0.0031 - mae: 0.0054

INFO:root:File 'LU1650492256.csv' loaded in retry loop, 328 left


   1414/Unknown - 556s 375ms/step - loss: 0.0031 - mae: 0.0054

INFO:root:File 'FR0010342592.csv' loaded, 327 left


   1426/Unknown - 561s 375ms/step - loss: 0.0030 - mae: 0.0053

INFO:root:File 'DE000A0D8Q49.csv' loaded, 326 left


   1431/Unknown - 564s 376ms/step - loss: 0.0030 - mae: 0.0053

INFO:root:File 'IE00BMCZLJ20.csv' loaded, 325 left


   1444/Unknown - 567s 375ms/step - loss: 0.0030 - mae: 0.0053

INFO:root:File 'LU1681040496.csv' loaded, 324 left


   1447/Unknown - 569s 376ms/step - loss: 0.0030 - mae: 0.0053

INFO:root:File 'IE00BDQYWQ65.csv' loaded, 323 left


   1463/Unknown - 573s 375ms/step - loss: 0.0030 - mae: 0.0053

INFO:root:File 'LU1602144575.csv' loaded, 322 left


   1467/Unknown - 575s 375ms/step - loss: 0.0029 - mae: 0.0053

INFO:root:File 'IE00BKM4H312.csv' loaded, 321 left


   1484/Unknown - 580s 374ms/step - loss: 0.0029 - mae: 0.0052

INFO:root:File 'IE00BFNM3G45.csv' loaded, 320 left


   1488/Unknown - 582s 374ms/step - loss: 0.0029 - mae: 0.0052

INFO:root:File 'LU1686832277.csv' loaded, 319 left


   1501/Unknown - 585s 373ms/step - loss: 0.0029 - mae: 0.0052

INFO:root:File 'LU1437018838.csv' loaded, 318 left


   1502/Unknown - 586s 373ms/step - loss: 0.0029 - mae: 0.0052

INFO:root:File 'IE00B5MTWY73.csv' loaded, 317 left


   1503/Unknown - 587s 373ms/step - loss: 0.0029 - mae: 0.0052

INFO:root:File 'IE00BYVJRP78.csv' loaded, 316 left


   1508/Unknown - 590s 375ms/step - loss: 0.0029 - mae: 0.0052

INFO:root:File 'LU1834986900.csv' loaded, 315 left


   1512/Unknown - 593s 375ms/step - loss: 0.0029 - mae: 0.0052

INFO:root:File 'IE000IM4K4K2.csv' loaded, 314 left


   1513/Unknown - 593s 375ms/step - loss: 0.0029 - mae: 0.0052

INFO:root:File 'LU0496786574.csv' loaded, 313 left


   1528/Unknown - 598s 375ms/step - loss: 0.0028 - mae: 0.0051

INFO:root:File 'IE00BGPP6473.csv' loaded, 312 left


   1533/Unknown - 599s 375ms/step - loss: 0.0028 - mae: 0.0051

INFO:root:File 'LU2023678282.csv' loaded, 311 left


   1543/Unknown - 602s 374ms/step - loss: 0.0028 - mae: 0.0051

INFO:root:File 'LU1280303014.csv' loaded, 310 left


   1547/Unknown - 604s 374ms/step - loss: 0.0028 - mae: 0.0051

INFO:root:File 'IE00BG0J4C88.csv' loaded, 309 left


   1549/Unknown - 605s 374ms/step - loss: 0.0028 - mae: 0.0051

INFO:root:File 'IE00BJXRZJ40.csv' loaded, 308 left


   1550/Unknown - 606s 374ms/step - loss: 0.0028 - mae: 0.0051

INFO:root:File 'IE00B0M62Q58.csv' loaded, 307 left


   1554/Unknown - 609s 375ms/step - loss: 0.0028 - mae: 0.0051

INFO:root:File 'IE00B5MTWD60.csv' loaded, 306 left


   1567/Unknown - 613s 375ms/step - loss: 0.0028 - mae: 0.0051

INFO:root:File 'IE00B3ZW0K18.csv' loaded, 305 left


   1575/Unknown - 616s 375ms/step - loss: 0.0027 - mae: 0.0051

INFO:root:File 'IE00B6TLBW47.csv' loaded, 304 left


   1593/Unknown - 622s 375ms/step - loss: 0.0027 - mae: 0.0050

INFO:root:File 'LU1829219713.csv' loaded, 303 left


   1599/Unknown - 625s 375ms/step - loss: 0.0027 - mae: 0.0050

INFO:root:File 'LU1291101555.csv' loaded, 302 left


   1604/Unknown - 626s 375ms/step - loss: 0.0027 - mae: 0.0050

INFO:root:File 'IE00B6S2Z822.csv' loaded, 301 left


   1629/Unknown - 634s 374ms/step - loss: 0.0027 - mae: 0.0050

INFO:root:File 'LU1215415214.csv' loaded, 300 left


   1647/Unknown - 639s 373ms/step - loss: 0.0026 - mae: 0.0049

INFO:root:File 'DE000A0H08J9.csv' loaded, 299 left


   1651/Unknown - 642s 374ms/step - loss: 0.0026 - mae: 0.0049

INFO:root:File 'IE00B0M63284.csv' loaded, 298 left


   1654/Unknown - 644s 374ms/step - loss: 0.0026 - mae: 0.0049

INFO:root:File 'LU1681044720.csv' loaded, 297 left


   1658/Unknown - 647s 375ms/step - loss: 0.0026 - mae: 0.0049

INFO:root:File 'LU0950381748.csv' loaded, 296 left


   1674/Unknown - 652s 374ms/step - loss: 0.0026 - mae: 0.0049

INFO:root:File 'IE00B5377D42.csv' loaded, 295 left


   1677/Unknown - 654s 375ms/step - loss: 0.0026 - mae: 0.0049

INFO:root:File 'LU1852211215.csv' loaded, 294 left


   1683/Unknown - 656s 375ms/step - loss: 0.0026 - mae: 0.0049

INFO:root:File 'IE00BSKRJZ44.csv' loaded, 293 left


   1684/Unknown - 657s 375ms/step - loss: 0.0026 - mae: 0.0049

INFO:root:File 'IE00B4L5ZG21.csv' loaded, 292 left


   1703/Unknown - 663s 374ms/step - loss: 0.0025 - mae: 0.0048

INFO:root:File 'IE00B449XP68.csv' loaded, 291 left


   1724/Unknown - 669s 374ms/step - loss: 0.0025 - mae: 0.0048

INFO:root:File 'IE00BDFK1573.csv' loaded, 290 left


   1738/Unknown - 673s 373ms/step - loss: 0.0025 - mae: 0.0048

INFO:root:File 'IE00B3VWM098.csv' loaded, 289 left


   1755/Unknown - 679s 372ms/step - loss: 0.0025 - mae: 0.0048

INFO:root:File 'IE00BG0J4841.csv' loaded, 288 left


   1757/Unknown - 680s 372ms/step - loss: 0.0025 - mae: 0.0048

INFO:root:File 'IE00BNGFMY78.csv' loaded, 287 left


   1768/Unknown - 682s 372ms/step - loss: 0.0024 - mae: 0.0047

INFO:root:File 'IE00BX7RR706.csv' loaded, 286 left


   1769/Unknown - 683s 372ms/step - loss: 0.0024 - mae: 0.0047

INFO:root:File 'LU1602144229.csv' loaded, 285 left


   1778/Unknown - 686s 372ms/step - loss: 0.0025 - mae: 0.0048

INFO:root:File 'IE00BYML9W36.csv' loaded, 284 left


   1779/Unknown - 687s 372ms/step - loss: 0.0025 - mae: 0.0048

KeyboardInterrupt: 

In [ ]:
model.optimizer.learning_rate = 5e-6

In [ ]:
model.optimizer.learning_rate

In [ ]:
epoch_add = 1

cc = CustomCallback(checkpoint_path = CHECKPOINT_PATH,
                    model_name = CHKPNT_NAME,
                    save_freq = CALLBACK_EVERY_N_BATCHES,
                    val_freq = CALLBACK_EVERY_N_BATCHES,
                    epoch_add = epoch_add)

In [ ]:
model.fit(tfGenTraining,
          epochs=5,
          verbose = 1,
          callbacks=[tensorboard_callback, cc])

In [ ]:
# A python generator function has to be applied on the dataStream

def pythonGeneratorEval(fileList):
  # Initialize the FileListToDataStream generator
  dataStreamEval= DataStreamCreator.FileListToDataStream(fileList = fileList,
                                                      batch_size = BATCH_SIZE,
                                                      X_Block_lenght = X_BLOCK_LENGHT,
                                                      y_type_dict=Y_TYPE_DICT,
                                                      shuffle=False,
                                                      parallel_generators = 1,
                                                      random_seed = RANDOM_SEED,
                                                      **DATA_STREAM_PARAMETERS
                                                      )
  
  # This while has to integrated into the FileListToDataStream method
  while True:  
    try:
      ne = next(dataStreamEval)
      _X = ne['X']
      _y = _y = ne['y']#[:,[1,3]]
    
      # Limit the y signal to avoid excess
      _y /= 10.0
      _y = np.clip(_y, -10.0, 10.0)
    
      # 'Blow up' the X array to a 2**n size
      #_X_new = np.zeros((_X.shape[0], _X.shape[1], TARGET_FEATURE_CNT))
      #_X_new[:,:,:_X.shape[2]] = _X

      yield (_X, _y)
    except StopIteration as si:
      logging.warning("StopIteration in pythonGenerator")
      logging.warning(si)
      return

In [ ]:
# Create a Tensorflow dataset out of the python generator, which can be fed to the network
tfGenEval = tf.data.Dataset.from_generator(lambda: pythonGeneratorEval(fileList=[TRAIN_FILES[4]]), 
                                               output_types = (tf.float32, tf.float32),
                                               output_shapes=(
                                                   (BATCH_SIZE, X_BLOCK_LENGHT, TARGET_FEATURE_CNT),
                                                   (BATCH_SIZE, 4)
                                                   )
                                               )
tfGenEval

In [ ]:
# ne[0].shape

In [ ]:
# ne[1].shape

In [ ]:
# plt.plot(ne[1][:,0])

In [ ]:
# plt.plot(ne[1][:,1])

In [ ]:
# evl = model.evaluate(tfGenEval)
# evl

In [ ]:
p = model.predict(tfGenEval)
p *= 10.0
p.shape

In [ ]:
def getPastDataFromGen(genIn, predictedShapeIn):
    it = genIn.as_numpy_iterator()

    y_past_data = np.empty((predictedShapeIn[0], 2))
    i = 0

    try:
        while (ne := next(it)):
            #print(i)
            y_past_data[i:i+ne[1].shape[0],0] = ne[1][:,0]
            y_past_data[i:i+ne[1].shape[0],1] = ne[1][:,2]

            i += ne[1].shape[0]

    except StopIteration:
        pass

    return y_past_data
    
y_past_data = getPastDataFromGen(tfGenEval, p.shape)
y_past_data.shape

In [ ]:
plt.plot(y_past_data[:,0])

In [ ]:
plt.plot(y_past_data[:,1])

In [ ]:
plt.plot(p[:,0])

In [ ]:
plt.plot(p[:,1])

In [ ]:
p.shape

In [ ]:
tickDF = pd.read_csv(TRAIN_FILES[1])
tickDF

In [ ]:
tickDF.shape[0] - p.shape[0]

In [ ]:
tickDFcropped = tickDF.iloc[-p.shape[0]:, :]
tickDFcropped

In [ ]:
# p_dir = p[:,0]
# p_dir_derivation = p[:,1]

p_future = p[:,0]
p_future_derivation = p[:,1]

In [ ]:
# Plot the prediction again, now over the open price
chart_name="Predicted direction of price movement with open price"
fig, ax1 = plt.subplots(figsize=(20,10))
ax1.set_title(chart_name, fontsize=14)

_ = ax1.plot(p_future, color="green", label="Predicted p_future")
_ = ax1.plot(p_future_derivation, color="red", label="Predicted p_future_derivation")
# _ = ax1.plot(p_neutral, color="gray", label="Predicted neutral")

ax2 = ax1.twinx()

ax2.plot(tickDFcropped.loc[:,'open'].values, color="black", label="Price")

ax1.set_xlabel("Timesteps")
ax1.set_ylabel("Direction")
ax2.set_ylabel("Price")

# Show a legend
lines, labels = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax2.legend(lines + lines2, labels + labels2, loc="upper left")

# Save the figure
# fig_name = "FileListToDataStreamExample_" + chart_name.replace(" ", "_").replace("'", "").replace("(", "").replace(")", "") + ".svg"
# plt.savefig(os.path.join(IMG_SAVE_PATH, fig_name), bbox_inches="tight")

In [ ]:
#@title Buy and sell signal thresholds
BUY_SIGNAL_THRESHOLD_FUTURE = 0.15 #@param {type:"number"}
BUY_SIGNAL_THRESHOLD_PAST = 0.01 #@param {type:"number"}

SELL_SIGNAL_THRESHOLD_PAST = 0.1 #@param {type:"number"}

In [ ]:
#@title Plot buy and sell signals
chart_name="Buy and sell signals"
fig, ax1 = plt.subplots(figsize=(20,10))
ax1.set_title(chart_name)

x_datetimes = [datetime.datetime.fromtimestamp(ts) for ts in tickDFcropped.loc[:,'open'].index]

_ = ax1.plot(x_datetimes, tickDFcropped.loc[:,'open'].values, color="black", label="Price", linewidth=2)

# Color area axis
ax2 = ax1.twinx()

# Convert the float value prediction into rising and falling categories
yCategoryFall = p_past_gain >= SELL_SIGNAL_THRESHOLD_PAST
yCategoryRise = (p_future_gain > p_past_gain) & (p_past_gain <= BUY_SIGNAL_THRESHOLD_FUTURE) #(p_future_gain >= BUY_SIGNAL_THRESHOLD_FUTURE)

ax2.fill_between(x_datetimes, yCategoryFall , alpha=0.5, color="red", label="'Buy' signal")
ax2.fill_between(x_datetimes, yCategoryRise , alpha=0.5, color="green", label="'Sell' signal")

# Remove tick marks and set limits for color area axis
ax2.set_yticks([])
ax2.set_ylim(-0.05,1.05)

ax3 = ax1.twinx()
_ = ax3.plot(x_datetimes, p_future_gain, color="blue", label="Predicted future gain")
# _ = ax3.plot(x_datetimes, 10.0*p_dir_derivation, color="red", label="10.0 * Predicted price direction derivation")
# ax3.set_ylim(-1.05,1.05)

ax3.plot([np.min(x_datetimes), np.max(x_datetimes)], [0.0,0.0], color="gray")

# Show a legend
lines, labels = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
lines3, labels3 = ax3.get_legend_handles_labels()
ax2.legend(lines + lines2 + lines3, labels + labels2 + labels3, loc="upper left")

# Save the figure
# fig_name = chart_name.replace(" ", "_").replace("'", "") + ".svg"
# plt.savefig(os.path.join(IMG_SAVE_PATH, fig_name), bbox_inches="tight")

# Add predictions to tick tables

In [ ]:
stop

In [ ]:
# PREDICTED_SAVE_PATH = "/content/dataset/etffancy/PastFutureGainV2/test"

In [ ]:
!mkdir /content/dataset/etffancy/FPNWithAttentionBiggerTimebased_1_FutureOnly
!mkdir /content/dataset/etffancy/FPNWithAttentionBiggerTimebased_1_FutureOnly/test
!mkdir /content/dataset/etffancy/FPNWithAttentionBiggerTimebased_1_FutureOnly/eval

In [ ]:
# Create a Tensorflow dataset out of the python generator, which can be fed to the network
# https://stackoverflow.com/questions/52443273/how-do-you-send-arguments-to-a-generator-function-using-tf-data-dataset-from-gen

#fileList = EVAL_FILES
#PREDICTED_SAVE_PATH = "/content/dataset/etffancy/FPNWithAttentionBiggerTimebased_1_FutureOnly/eval"

fileList = TEST_FILES
PREDICTED_SAVE_PATH = "/content/dataset/etffancy/FPNWithAttentionBiggerTimebased_1_FutureOnly/test"

pd.options.mode.chained_assignment = None  # default='warn'

for file_index in tqdm(range(0, len(fileList))):
    try:
        filename = fileList[file_index]

        logging.info(f"\nFile name: '{filename}' for index {file_index}")

        tfGenEval = tf.data.Dataset.from_generator(lambda: pythonGeneratorEval(fileList=[filename]), 
                                                       output_types = (tf.float32, tf.float32),
                                                       output_shapes=(
                                                           (BATCH_SIZE, X_BLOCK_LENGHT, TARGET_FEATURE_CNT),
                                                           (BATCH_SIZE, 4)
                                                           )
                                                       )
        p = model.predict(tfGenEval, verbose = 0)

        logging.info(f"p.shape: {p.shape}")

        p_future_gain = p[:,0]
        p_future_gain_derivation = p[:,1]
        
        # Load the tick table
        tickDF = pd.read_csv(filename)
        tickDFcropped = tickDF.iloc[-p.shape[0]:, :]
        
        # Add the predicted future gain
        tickDFcropped.loc[:,"p_future_gain"] = p_future_gain
        tickDFcropped.loc[:,"p_future_gain_derivation"] = p_future_gain_derivation
        
        # Get the (known) past data
        y_past_data = getPastDataFromGen(tfGenEval, p.shape)

        # Add the past gain
        tickDFcropped.loc[:,"p_past_gain"] = y_past_data[:,0]
        tickDFcropped.loc[:,"p_past_gain_derivation"] = y_past_data[:,1]

        # Save the DF
        tickDFcropped.to_csv(os.path.join(PREDICTED_SAVE_PATH, filename.split(os.path.sep)[-1]))

        logging.info("Saved the predicted data.")
    except KeyboardInterrupt:
        raise
    except Exception as ex:
        logging.warning(str(ex))

In [ ]:
# Create a Tensorflow dataset out of the python generator, which can be fed to the network
# https://stackoverflow.com/questions/52443273/how-do-you-send-arguments-to-a-generator-function-using-tf-data-dataset-from-gen

fileList = EVAL_FILES
PREDICTED_SAVE_PATH = "/content/dataset/etffancy/FPNWithAttentionBiggerTimebased_1_FutureOnly/eval"

# fileList = TEST_FILES
# PREDICTED_SAVE_PATH = "/content/dataset/etffancy/FPNWithAttentionBiggerTimebased_1_FutureOnly/test"

pd.options.mode.chained_assignment = None  # default='warn'

for file_index in tqdm(range(0, len(fileList))):
    try:
        filename = fileList[file_index]

        logging.info(f"\nFile name: '{filename}' for index {file_index}")

        tfGenEval = tf.data.Dataset.from_generator(lambda: pythonGeneratorEval(fileList=[filename]), 
                                                       output_types = (tf.float32, tf.float32),
                                                       output_shapes=(
                                                           (BATCH_SIZE, X_BLOCK_LENGHT, TARGET_FEATURE_CNT),
                                                           (BATCH_SIZE, 4)
                                                           )
                                                       )
        p = model.predict(tfGenEval, verbose = 0)

        logging.info(f"p.shape: {p.shape}")

        p_future_gain = p[:,0]
        p_future_gain_derivation = p[:,1]
        
        # Load the tick table
        tickDF = pd.read_csv(filename)
        tickDFcropped = tickDF.iloc[-p.shape[0]:, :]
        
        # Add the predicted future gain
        tickDFcropped.loc[:,"p_future_gain"] = p_future_gain
        tickDFcropped.loc[:,"p_future_gain_derivation"] = p_future_gain_derivation
        
        # Get the (known) past data
        y_past_data = getPastDataFromGen(tfGenEval, p.shape)

        # Add the past gain
        tickDFcropped.loc[:,"p_past_gain"] = y_past_data[:,0]
        tickDFcropped.loc[:,"p_past_gain_derivation"] = y_past_data[:,1]

        # Save the DF
        tickDFcropped.to_csv(os.path.join(PREDICTED_SAVE_PATH, filename.split(os.path.sep)[-1]))

        logging.info("Saved the predicted data.")
    except KeyboardInterrupt:
        raise
    except Exception as ex:
        logging.warning(str(ex))