# Mount drive and bucket
Todo: Remove in public version

In [1]:
# Check if the notebook is run in Google Colab
import sys

COLAB = 'google.colab' in sys.modules

In [2]:
import sys
import datetime
import logging

nblog = open(f"/content/bigdata/nb_{datetime.datetime.utcnow().strftime('%Y%m%d_%H%M')}.log", "a+")
print(nblog)
sys.stdout.echo = nblog
sys.stderr.echo = nblog

#get_ipython().log.handlers[0].stream = nblog
#get_ipython().log.setLevel(logging.INFO)

%autosave 60

<_io.TextIOWrapper name='/content/bigdata/nb_20230330_0633.log' mode='a+' encoding='UTF-8'>


Autosaving every 60 seconds


In [3]:
# if COLAB:
#   from google.colab import drive
#   drive.mount('/content/drive')

In [4]:
if COLAB:
  from google.colab import auth
  auth.authenticate_user()
else:
    print("Run the command!")
  #Todo #bring the command inside the notebook
  #run this terminal inside docker: gcloud auth login b.girsule@gmail.com --no-launch-browser

Run the command!


In [5]:
# Todo: Check if possible in local docker
# from google.cloud import storage

In [6]:
# Check if the tf version is 2.10.0, this is required to use the 'ignore_class' in the  SparseCategoricalCrossentropy
import tensorflow as tf

if '2.10.0' != tf.__version__:
  !pip uninstall tensorflow -y
  !pip install tensorflow-gpu==2.10.0
  please_restart_the_runtime
else:
  print("TF Version is 2.10.0, ok!")

2023-03-30 06:33:48.751689: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-30 06:33:48.879520: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-30 06:33:49.527947: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-03-30 06:33:49.528010: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or 

TF Version is 2.10.0, ok!


In [7]:
from tensorflow import keras
# import tensorflow_gcs_config
from tensorflow.python.lib.io import file_io

from keras.layers import Input, Dense, Flatten #, ReLU, Add, Flatten, Concatenate, LayerNormalization, UpSampling2D, Activation, LSTM, Multiply, Dropout, Reshape, Permute, BatchNormalization, MaxPooling1D, AveragePooling1D, MaxPooling3D, AveragePooling2D, LayerNormalization, MaxPooling2D
from keras.models import Model
from keras.optimizers import Adam

In [8]:
import os
from os import listdir
from os.path import isfile, join

In [9]:
import pandas as pd
import numpy as np
import copy
import matplotlib.pyplot as plt
from tqdm import tqdm
import pickle
import gc
import random

In [10]:
# Set the google cloud bucket data
project_id = 'tweetprediction'
bucket_name = 'crypto_nlp_training'

In [11]:
# Set the checkpoint path for saving train progress
if COLAB:
    CHECKPOINT_PATH = f"gs://{bucket_name}/chk/"
else:
    CHECKPOINT_PATH = f"/content/bigdata/chk/"

In [12]:
# Check if the notebook is run in google colab, if so, clone the repo
if COLAB:
    print("Running in Colab")

    # Clone the whole repo to get all data and code if not already done
    if not os.path.exists("/content/CryptoCrystalBall"):
      !git clone https://github.com/girsigit/CryptoCrystalBall

      # cd into the notebooks directory --> Necessary to match all paths for importing
    #%cd /content/CryptoCrystalBall/JupyterDocker/notebooks
    %cd /content

In [13]:
# Try importing the Ta-Lib library, if this fails, try to install it and
# import it again afterwards
try:
    import talib
except:
    !wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
    !tar -xzvf ta-lib-0.4.0-src.tar.gz
    %cd ta-lib
    !./configure --prefix=/usr
    !make
    !make install
    !pip install Ta-Lib
    %cd ..

    import talib

In [14]:
try:
  from transformers import TFRobertaModel, RobertaConfig
except:
  # Important!: Version 4.23 does not work on TPU
  !pip install transformers==4.22

  from transformers import TFRobertaModel, RobertaConfig

In [15]:
# !pip uninstall -y tensorboard-plugin-profile

In [16]:
# # Required to do profiling
# !pip install tensorboard-plugin-profile

In [17]:
import logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)

---
# Add custom import path for DataStreamCreator and IndicatorCalculator

These libs are not in the standard python directory, so their paths have to be added to the import paths

In [18]:
# # Get the current directory
# current_dir = os.getcwd()
# current_dir_splitted = current_dir.split(os.sep)

# Todo: is inside /content/CB in local docker
current_dir_splitted = ["", "content"]
current_dir_splitted

['', 'content']

In [19]:
# Create the import directories for the DataStreamCreator and the IndicatorCalculator
dsc_dir = '/content/CryptoCrystalBall/DataStreamCreator'
print(f"dsc_dir: {dsc_dir}")

ind_dir = '/content/CryptoCrystalBall/IndicatorCalculator'
print(f"ind_dir: {ind_dir}")

# Add them to the import paths
sys.path.insert(0, dsc_dir)
sys.path.insert(0, ind_dir)

dsc_dir: /content/CryptoCrystalBall/DataStreamCreator
ind_dir: /content/CryptoCrystalBall/IndicatorCalculator


In [20]:
# Import the actual classes
from IndicatorCalculator import IndicatorCalculator
import DataStreamCreator

---
# Define all the parameters and variables

In [21]:
# Define the tick data path
DATA_PATH = os.path.join(os.sep, *current_dir_splitted, 'DemoData')
print(f"DATA_PATH: {DATA_PATH}")

DATA_PATH: /content/DemoData


In [22]:
# Define the chart image save path
IMG_SAVE_PATH = os.path.join(os.sep, *current_dir_splitted, 'Documentation', 'Images')
print(f"IMG_SAVE_PATH: {IMG_SAVE_PATH}")

IMG_SAVE_PATH: /content/Documentation/Images


In [23]:
# Define a global random seed
RANDOM_SEED = 42

# Set the seed in np
np.random.seed(RANDOM_SEED)

In [24]:
# X_BLOCK_LENGHT defines how far into the past a 'slice of a chart' shall be
# See: https://github.com/girsigit/CryptoCrystalBall/tree/main/DataStreamCreator#xblockgenerator
# X_BLOCK_LENGHT = 256
X_BLOCK_LENGHT = 128

In [25]:
# How many examples shall be processed at the same time, limited by GPU memory
BATCH_SIZE = 384 # for X_BLOCK_LENGHT = 256
BATCH_SIZE = 512 # for X_BLOCK_LENGHT = 128

In [26]:
# A fixed number of features is used
FEATURES = 160

In [27]:
# Finanical indicator timespans
# See: https://github.com/girsigit/CryptoCrystalBall/tree/main/IndicatorCalculator
SHORTSPAN = 7
MIDSPAN = 38
LONGSPAN = 50

In [28]:
# Additional settings for the data stream
# For this notebook, the calculation of pattern indicators is turned off
DATA_STREAM_PARAMETERS = {
    "calcPatternIndicators": False, # No patterns are used
    "calcVolumeInidators": False, # No volume indicators, these are wide spread and may disturb the classifer
    "dropna": True # Drop all tick/indicator table rows containing nan values instead of just replacing them by 0 (which would lead to wrong predictions)
}

# Load the train dataset

In [29]:
# Get train file names - Only pick the ones ending with -USDT to prevent
# influence between different currencies
TRAIN_PATH = "/content/dataset/etffancy"

# Get all file names
ALL_FILES = [os.path.join(TRAIN_PATH,f) for f in listdir(TRAIN_PATH) if isfile(join(TRAIN_PATH, f)) and ".csv" in f ]

# Sort them (as a stable basis for randomizing afterwards)
ALL_FILES = sorted(ALL_FILES)

print(f"The train dataset contains {len(ALL_FILES)} files.")
print(ALL_FILES[:3])

The train dataset contains 1064 files.
['/content/dataset/etffancy/DE0002635265.csv', '/content/dataset/etffancy/DE0002635273.csv', '/content/dataset/etffancy/DE0002635281.csv']


In [30]:
# Split the dataset into train, test (trade algorithm train) and eval (trade algorithm test)
SPLIT_RANDOM_SEED = 666
TRAIN_SET_SIZE = 0.5
TEST_SET_SIZE = 0.25
# EVAL_SET_SIZE: The rest

random.Random(SPLIT_RANDOM_SEED).shuffle(ALL_FILES)

train_split_index = int(len(ALL_FILES) * TRAIN_SET_SIZE)
print(f"train_split_index: {train_split_index}")

test_split_index = int(len(ALL_FILES) * (TRAIN_SET_SIZE + TEST_SET_SIZE))
print(f"test_split_index: {test_split_index}")

TRAIN_FILES = ALL_FILES[:train_split_index]
TEST_FILES = ALL_FILES[train_split_index:test_split_index]
EVAL_FILES = ALL_FILES[test_split_index:]

train_split_index: 532
test_split_index: 798


---
# Prepare data source

For training a neural network, first the data source has to be prepared. For this purpose, the method `FileListToDataStream` from the `DataStreamCreator` class is used. This method creates a stream of `X-Block` and `y-data` arrays out of a list of .csv file names, pointing to tick tables (called `EXAMPLE_FILE_PATHS` in this example). For details about `X-Blocks` and `y-data`, please refer to the documentation of the `XBlockGenerator` and the `YDataGenerator` under https://github.com/girsigit/CryptoCrystalBall/tree/main/DataStreamCreator.

<br>

WRONG  WRONG  WRONG  WRONG  WRONG  WRONG  WRONG  WRONG  
Target values (y-data) from the data generator would not be necessary in this notebook, but since it cannot be switched off, the future direction and its derviation of the price have been chosen in `Y_TYPE_DICT` since they are not expensive to compute. A switch flag will be added in a future release.

In [31]:
# FPNWithAttention_5_ETF_Trained_Past_Future_Gain_TrainSetOnly_GPU_64LB
Y_TYPE_DICT = copy.deepcopy(DataStreamCreator.YDataGenerator.PARAM_DICT_TEMPLATE_Y_DATA_TYPE_PAST_FUTURE_GAIN)
Y_TYPE_DICT["gain_timespan"] = 60
# Y_TYPE_DICT["direction_ma_timespan"] = 14
# Y_TYPE_DICT["derivation_ma_timespan"] = 14
Y_TYPE_DICT

{'dataType': 3,
 'gain_timespan': 60,
 'direction_ma_timespan': 48,
 'derivation_ma_timespan': 48}

In [32]:
TARGET_FEATURE_CNT = 160 #256

In [33]:
XShape = (BATCH_SIZE, X_BLOCK_LENGHT, TARGET_FEATURE_CNT)
XShape

(512, 128, 160)

In [34]:
import numpy as np
a = np.array([1,2,3,4])
a[[1,3]]

array([2, 4])

In [35]:
# A python generator function has to be applied on the dataStream

def pythonGeneratorSignalsTraining():
  # Initialize the FileListToDataStream generator
  dataStreamTraining = DataStreamCreator.FileListToDataStream(fileList = TRAIN_FILES,
                                                      batch_size = BATCH_SIZE,
                                                      X_Block_lenght = X_BLOCK_LENGHT,
                                                      y_type_dict=Y_TYPE_DICT,
                                                      shuffle=True,
                                                      parallel_generators = np.min([BATCH_SIZE, 8]),
                                                      random_seed = RANDOM_SEED,
                                                      **DATA_STREAM_PARAMETERS
                                                      )

  # This while has to integrated into the FileListToDataStream method
  while True:  
    try:
      ne = next(dataStreamTraining)
      _X = ne['X']
      _y = ne['y'][:,[1,3]]
    
      # Limit the y signal to avoid excess
      _y /= 10.0
      _y = np.clip(_y, -10.0, 10.0)
        
      # 'Blow up' the X array to a 2**n size
      #_X_new = np.zeros((_X.shape[0], _X.shape[1], TARGET_FEATURE_CNT))
      #_X_new[:,:,:_X.shape[2]] = _X

      yield (_X, _y)
    except StopIteration as si:
      logging.warning("StopIteration in pythonGenerator")
      logging.warning(si)
      return

In [36]:
# Create a Tensorflow dataset out of the python generator, which can be fed to the network
tfGenTraining = tf.data.Dataset.from_generator(pythonGeneratorSignalsTraining, 
                                               output_types = (tf.float32, tf.float32),
                                               output_shapes=(
                                                   (BATCH_SIZE, X_BLOCK_LENGHT, TARGET_FEATURE_CNT),
                                                   (BATCH_SIZE, 2)
                                                   )
                                               )

tfGenTraining = tfGenTraining.prefetch(buffer_size=32)
tfGenTraining

2023-03-30 06:33:51.380424: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-30 06:33:51.456000: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-30 06:33:51.456173: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-30 06:33:51.456856: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags

<PrefetchDataset element_spec=(TensorSpec(shape=(512, 128, 160), dtype=tf.float32, name=None), TensorSpec(shape=(512, 2), dtype=tf.float32, name=None))>

---
# Create the neural network

In the example, two Conv1D pyramids are used to extract features at different levels out of the feature and the time dimension.

It is also possible to use different architecures, like LSTM, Conv2D, Attention-Based ones or even NLP-based models. I have already tried many different ones and will publish them into the model zoo.

```
Todo: Create Model Zoo
```

```
Todo: Create Image of netwrok structure
```

In [37]:
# from keras.layers import Input, Dense, ReLU, Add, Flatten, Concatenate, LayerNormalization, UpSampling2D, Activation, LSTM, Multiply, Dropout, Reshape, Permute, BatchNormalization, MaxPooling1D, AveragePooling1D, MaxPooling3D, AveragePooling2D, LayerNormalization, MaxPooling2D, UnitNormalization, UpSampling1D
from keras.layers import UnitNormalization, Permute, Conv1D, UpSampling1D, Add, LSTM, Concatenate, Multiply, Activation, Attention, Dropout

In [38]:
# Create the FPNWithFScaledInput model
# Infos about the feature pyramid: https://jonathan-hui.medium.com/understanding-feature-pyramid-networks-for-object-detection-fpn-45b227b9106c

def CreateModelFPNWithAttention():
  # Define model parameters
  mp = {
      "NAME": "FPNWithAttentionBiggerTimebased",
      "VERSION": "2_FutureOnly_60days",
      "CNN_INITIAL_FILTERS": 64,
      "CNN_EXTRACTOR_LAYERS": 6,
      "CNN_INITIAL_KERNEL_SIZE": 2,
      "CNN_MAX_KERNEL_SIZE": 8,
      "FEATURE_PYRAMID_START_INDEX": 2,
      "HEAD_LSTM_SIZE": 64,
      "HEAD_DENSE_SIZE": 32
      }
  
  # Create the model input  
  inputTicksAndIndicators = Input(shape=(X_BLOCK_LENGHT, TARGET_FEATURE_CNT), name='inputTicksAndIndicators', dtype='float32')
  inputTicksAndIndicators = Dropout(0.1, name='inputDropout')(inputTicksAndIndicators)

  # Normalize the input data, as it has a wide value spread (range of 1e8)
  normalized = UnitNormalization(name="UnitNormalizationInput", axis=-2)(inputTicksAndIndicators)

  # Permute it to Conv over Features
  #normalized = Permute((2, 1), name="PermuteInput")(normalized)

  # ----------------------------------------------------------------------------

  # As an example a 1D-CNN pyramid is used to extract higher-level features out
  # of the indicator+tick dimension
  conv_layers = []
  aligned_layers = []
  feature_map_layers = []
  anti_aliased_layers = []
  anti_aliased_pyramid_indices = []
  regressor_layers = []

  finalFilters = mp["CNN_INITIAL_FILTERS"] * 2**(mp["FEATURE_PYRAMID_START_INDEX"])
  print(finalFilters) 

  for i in range(mp["CNN_EXTRACTOR_LAYERS"]):
    if 0 == i:
      source_layer = normalized
    else:
      source_layer = feature_conv
    
    filters = int(mp["CNN_INITIAL_FILTERS"]*(2**i))
    kernel_size = mp["CNN_INITIAL_KERNEL_SIZE"]*(2**i)
    kernel_size = int(np.min([mp["CNN_MAX_KERNEL_SIZE"], kernel_size]))
    strides = int(np.min([2,kernel_size]))

    print(f"Step {i}, using {filters} filters with a kernel size of {kernel_size} at strides of {strides}")

    # Create the feature extraction convolution
    res_net_element = Conv1D(filters=source_layer.shape[-1],
                          kernel_size=kernel_size,
                          strides=1, 
                          padding="same",
                          name=f"ResNet_{i}_Conv1D_1")(source_layer)
    
    res_net_element = Activation("relu",
                              name=f"ResNet_{i}_ReLU")(res_net_element)
    
    res_net_element = Conv1D(filters=source_layer.shape[-1],
                          kernel_size=kernel_size,
                          strides=1, 
                          padding="same",
                          name=f"ResNet_{i}_Conv1D_2")(res_net_element)
    
    res_net_element = Add(name=f"ResNet_{i}_Add")([res_net_element, source_layer])
        
    feature_conv = Conv1D(filters=filters,
                          kernel_size=kernel_size,
                          strides=strides, 
                          padding="same",
                          name=f"ResNet_{i}_Feature_Conv1D_FilterDimReduction")(res_net_element)

    attention_map = Attention(name=f"Attention_Layer_{i}")([feature_conv,feature_conv])
    print(f"attention_map.shape: {attention_map.shape}")

    feature_conv_attentioned = Multiply(name=f"Multiply_Apply_Attention_{i}")([feature_conv, attention_map])
    print(f"feature_conv_attentioned.shape: {feature_conv_attentioned.shape}")
    
    conv_layers.append(feature_conv_attentioned)

    # Apply the feature extraction pyramid
    if mp["FEATURE_PYRAMID_START_INDEX"] <= i:
      # Apply a 1x1 convolution to align the channel depth    
      if feature_conv_attentioned.shape[-1] != finalFilters:
        aligned_layer = Conv1D(filters=finalFilters,
                              kernel_size=1,
                              strides=1,
                              padding="same",
                              name=f"Channel_Depth_Alignment_{i}")(feature_conv_attentioned)
      else:
        aligned_layer = feature_conv_attentioned
      
      aligned_layers.append(aligned_layer)

  # Go top-down through the aligned_layers to create the feature_map_layers
  for i in range(mp["CNN_EXTRACTOR_LAYERS"]-1, mp["FEATURE_PYRAMID_START_INDEX"]-1, -1):
    aligned_layers_index = i - mp["FEATURE_PYRAMID_START_INDEX"]
    aligned_layer = aligned_layers[aligned_layers_index]

    print(f"Building feature_map_layers, step {i}. Shape of aligned_layer: {aligned_layer.shape}")

    # The highest-filtered layer is taken as feature map directly
    if i == mp["CNN_EXTRACTOR_LAYERS"]-1:
      feature_map_layers.append(aligned_layer)
      anti_aliased_layers.append(feature_map_layers[-1])
    else:
      # Take the last feature_map_layer and scale it by two
      upsampled = UpSampling1D(size=2,
                               name=f"Pyramid_Upsampling_{i}")(feature_map_layers[-1])

      # Add the aligned_layer
      added = Add(name=f"Pyramid_Add_{i}")([upsampled, aligned_layer])

      # Append as new feature_map_layer
      feature_map_layers.append(added)

      # Apply a convolution with a kernel size of 3 to "reduce the aliasing effect"
      anti_aliased_layer = Conv1D(filters=feature_map_layers[-1].shape[-1],
                                  kernel_size=3,
                                  strides=1,
                                  padding="same",
                                  name=f"Anti_Alias_{i}")(feature_map_layers[-1])

      anti_aliased_layers.append(anti_aliased_layer)

    # Helper storage to keep pyramid index consistent, also in predictor/regressor
    anti_aliased_pyramid_indices.append(i)

  # Apply the predictor head to each feature dimension layer
  for n in range(len(anti_aliased_layers)):
    predictor_input = anti_aliased_layers[n]

    # Get the pyramid index
    pyramid_index = anti_aliased_pyramid_indices[n]

    # Permute the Conv output back
    predictor_input = Permute((2, 1), name=f"PermutePredictorInput_{pyramid_index}")(predictor_input)

    predictor = LSTM(units=mp["HEAD_LSTM_SIZE"],
                     name=f"Predictor_Head_{pyramid_index}_LSTM")(predictor_input)
    
    # Direction and derivation regressor
    regressor = Dense(units=mp["HEAD_DENSE_SIZE"],
                      name=f"Predictor_Head_{pyramid_index}_Dense_Regressor",
                      activation='relu')(predictor)
    
    regressor_layers.append(regressor)
  
  # Add all regressors together
  regressor_conced = Concatenate(name="Concatenate_regressors")(regressor_layers)
  #regressor_conced = Dense(regressor_conced.shape[1], name="Combined_Regressor_1")(regressor_conced)
  #regressor_conced = Dense(regressor_conced.shape[1], name="Combined_Regressor_2")(regressor_conced)

  # The output are two values (direction and derivation) in the range [-1.0, 1.0]
  output = Dense(2, activation="tanh", name="Output")(regressor_conced)
  outputs = [output]

  # Combine it all into a model object
  model = Model(inputs=inputTicksAndIndicators, outputs=outputs, name=mp["NAME"] + "_" + str(mp["VERSION"]))

  return model, mp

model, model_config = CreateModelFPNWithAttention()
print(model_config)
model.summary(line_length=220)

256
Step 0, using 64 filters with a kernel size of 2 at strides of 2
attention_map.shape: (None, 64, 64)
feature_conv_attentioned.shape: (None, 64, 64)
Step 1, using 128 filters with a kernel size of 4 at strides of 2
attention_map.shape: (None, 32, 128)
feature_conv_attentioned.shape: (None, 32, 128)
Step 2, using 256 filters with a kernel size of 8 at strides of 2
attention_map.shape: (None, 16, 256)
feature_conv_attentioned.shape: (None, 16, 256)
Step 3, using 512 filters with a kernel size of 8 at strides of 2
attention_map.shape: (None, 8, 512)
feature_conv_attentioned.shape: (None, 8, 512)
Step 4, using 1024 filters with a kernel size of 8 at strides of 2
attention_map.shape: (None, 4, 1024)
feature_conv_attentioned.shape: (None, 4, 1024)
Step 5, using 2048 filters with a kernel size of 8 at strides of 2
attention_map.shape: (None, 2, 2048)
feature_conv_attentioned.shape: (None, 2, 2048)
Building feature_map_layers, step 5. Shape of aligned_layer: (None, 2, 256)
Building feature_

# Train the model

### Train strategy in the paper
https://huggingface.co/roberta-base

The model was trained on 1024 V100 GPUs for 500K steps with a batch size of 8K and a sequence length of 512. The optimizer used is Adam with a learning rate of 6e-4, β1=0.9\beta_{1} = 0.9β1​=0.9, β2=0.98\beta_{2} = 0.98β2​=0.98 and ϵ=1e−6\epsilon = 1e-6ϵ=1e−6, a weight decay of 0.01, learning rate warmup for 24,000 steps and linear decay of the learning rate after.

In [39]:
CHKPNT_NAME = f"{model.name}_GPU_{X_BLOCK_LENGHT}LB"
CHKPNT_NAME

'FPNWithAttentionBiggerTimebased_2_FutureOnly_60days_GPU_128LB'

In [40]:
# Set an optimizer
optimizer = Adam(
    learning_rate=1e-03,
    epsilon=1e-06,
    beta_1=0.9,
    beta_2=0.98,
    decay=0.01)

In [41]:
# Compile the model
model.compile(
    optimizer = optimizer,
    loss = ["mse"], 
    metrics=["mae"])

In [42]:
#@title CustomCallback
class CustomCallback(tf.keras.callbacks.Callback):
  def __init__(self, save_freq, val_freq, checkpoint_path, model_name, epoch_add=0):
    self.save_freq = save_freq
    self.val_freq = val_freq
    self.checkpoint_path = checkpoint_path
    self.model_name = model_name
    self.current_epoch = 0
    self.epoch_add = epoch_add

  def on_epoch_begin(self, epoch, logs=None):
    self.current_epoch = epoch + self.epoch_add
    # keys = list(logs.keys())
    # print("Start epoch {} of training; got log keys: {}".format(epoch, keys))

  def on_epoch_end(self, epoch, logs=None):
    self.saveTheModel(-1, logs)

  def on_train_batch_end(self, batch, logs=None):
    self.saveTheModel(batch, logs)

  def saveTheModel(self, batch, logs=None):
    if (0 < batch and 0 == batch % self.save_freq) or (0 > batch):
      logging.info(str(datetime.datetime.utcnow()))
    
      if 0 > batch:
        _save_folder = os.path.join(self.checkpoint_path,
                                    self.model_name,
                                    "cp_daily_valid_{:02d}_end".format(self.current_epoch)
                                    )
      else:
        _save_folder = os.path.join(self.checkpoint_path,
                                    self.model_name,
                                    "cp_daily_valid_{:02d}_{:05d}".format(self.current_epoch, batch)
                                    )
      
      fp = os.path.join(_save_folder, "model.h5")
      model.save(fp)
      logging.info(f"Saved model to '{fp}'")
      
      # Save optimizer config
      # c = copy.deepcopy(self.model.optimizer.get_config())

      fp = os.path.join(_save_folder, "c.pickle")
      with file_io.FileIO(fp, mode='wb+') as handle:
        pickle.dump(self.model.optimizer.get_config(), handle, protocol=pickle.HIGHEST_PROTOCOL)
        
      logging.info(f"Saved optimizer config to '{fp}'")

      # Save optimizer weights
      # w = copy.deepcopy(self.model.optimizer.get_weights())

      fp = os.path.join(_save_folder, "w.pickle")
      with open(fp, "wb") as handle:
        # with file_io.FileIO(fp, mode='wb+') as handle:
        pickle.dump(self.model.optimizer.get_weights(), handle, protocol=pickle.HIGHEST_PROTOCOL)
      
      logging.info(f"Saved optimizer weights to '{fp}'")
        
      logging.info(f"Did a gc collect: {gc.collect()}")

    # if 0 < batch and 0 == batch % self.val_freq:
    #   print("-------------------------EVAL-------------------------")
    #   model.evaluate(tfgenTest)
    #   print("\n-------------------------EVAL-------------------------")

In [43]:
gc.collect()

6589

In [44]:
epoch_add = 0

In [45]:
CALLBACK_EVERY_N_BATCHES = 2000

In [46]:
cc = CustomCallback(checkpoint_path = CHECKPOINT_PATH,
                    model_name = CHKPNT_NAME,
                    save_freq = CALLBACK_EVERY_N_BATCHES,
                    val_freq = CALLBACK_EVERY_N_BATCHES,
                    epoch_add = epoch_add)

In [47]:
# Load the TensorBoard notebook extension
%load_ext tensorboard

In [48]:
%reload_ext tensorboard

The TensorBoard UI is displayed in a browser window. In this colab, perform the following steps to prepare to capture profile information.
1.  Click on the dropdown menu box on the top right side and scroll down and click PROFILE. A new window appears that shows: **No profile data was found** at the top.
1.  Click on the CAPTURE PROFILE button. A new dialog appears. The top input line shows: **Profile Service URL or TPU name**. Copy and paste the Profile Service URL (the service_addr value shown before launching TensorBoard) into the top input line. While still on the dialog box, start the training with the next step.
1.  Click on the next colab cell to start training the model.
1.  Watch the output from the training until several epochs have completed. This allows time for the profile data to start being collected. Return to the dialog box and click on the CAPTURE button. If the capture succeeds, the page will auto refresh and redirect you to the profiling results.

In [49]:
# Todo: Create more elegant solution
log_dir = "gs://ticks_with_indicators_with_volume/logs/TPU/" + CHKPNT_NAME + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

if not COLAB:
    log_dir = os.path.join("/content/bigdata/log",log_dir.split("/")[-1])

log_dir

'/content/bigdata/log/FPNWithAttentionBiggerTimebased_2_FutureOnly_60days_GPU_128LB20230330-063353'

In [50]:
import datetime

tensorboard_callback = tf.keras.callbacks.TensorBoard(
    log_dir=log_dir,
    histogram_freq=1,
    update_freq=CALLBACK_EVERY_N_BATCHES,
    profile_batch=(5,100)
    )

2023-03-30 06:33:53.876757: I tensorflow/core/profiler/lib/profiler_session.cc:101] Profiler session initializing.
2023-03-30 06:33:53.876776: I tensorflow/core/profiler/lib/profiler_session.cc:116] Profiler session started.
2023-03-30 06:33:53.876816: I tensorflow/core/profiler/backends/gpu/cupti_tracer.cc:1664] Profiler found 1 GPUs
2023-03-30 06:33:53.877101: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcupti.so.11.2'; dlerror: libcupti.so.11.2: cannot open shared object file: No such file or directory
2023-03-30 06:33:54.010360: I tensorflow/core/profiler/lib/profiler_session.cc:128] Profiler session tear down.
2023-03-30 06:33:54.010546: I tensorflow/core/profiler/backends/gpu/cupti_tracer.cc:1798] CUPTI activity buffer flushed


In [51]:
#model.load_weights("/content/bigdata/chk/FPNWithAttentionBigger_3_FutureOnly_GPU_256LB/cp_daily_valid_33_end/model.h5")

In [52]:
%tensorboard --logdir $log_dir --host 0.0.0.0 --port 6006

In [53]:
model.fit(tfGenTraining,
          epochs=1,
          verbose = 1,
          callbacks=[tensorboard_callback, cc])

INFO:root:File 'IE00B6X2VY59.csv' loaded, 531 left
INFO:root:File 'IE00BYXVGZ48.csv' loaded, 530 left
INFO:root:File 'DE000A0F5UF5.csv' loaded, 529 left
INFO:root:File 'DE000ETFL441.csv' loaded, 528 left
INFO:root:File 'LU1781541179.csv' loaded, 527 left
INFO:root:File 'LU1650487926.csv' loaded, 526 left
INFO:root:File 'LU1285960032.csv' loaded, 525 left
INFO:root:File 'IE00B1FZSD53.csv' loaded, 524 left
2023-03-30 06:34:14.635809: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8700
INFO:root:File 'IE00B5KQNG97.csv' loaded, 523 left
INFO:root:File 'IE00BYM31M36.csv' loaded, 522 left


      2/Unknown - 26s 558ms/step - loss: 1.6083e-04 - mae: 0.0092

INFO:root:File 'LU2082996542.csv' loaded, 521 left


      4/Unknown - 27s 702ms/step - loss: 8.8048e-05 - mae: 0.0061

2023-03-30 06:34:24.118653: I tensorflow/core/profiler/lib/profiler_session.cc:101] Profiler session initializing.
2023-03-30 06:34:24.118683: I tensorflow/core/profiler/lib/profiler_session.cc:116] Profiler session started.
INFO:root:File 'IE00BF4G7076.csv' loaded, 520 left


      6/Unknown - 29s 820ms/step - loss: 6.2457e-05 - mae: 0.0050WARNING:tensorflow:Callback method `on_train_batch_end` is slow compared to the batch time (batch time: 0.1493s vs `on_train_batch_end` time: 0.5530s). Check your callbacks.


     12/Unknown - 33s 681ms/step - loss: 3.8166e-05 - mae: 0.0040

INFO:root:File 'IE00BQN1K786.csv' loaded, 519 left


     16/Unknown - 36s 716ms/step - loss: 3.1483e-05 - mae: 0.0036

INFO:root:File 'LU0136240974.csv' loaded, 518 left


     25/Unknown - 44s 779ms/step - loss: 2.2785e-05 - mae: 0.0031

INFO:root:File 'IE00BLDGH447.csv' loaded, 517 left


     27/Unknown - 45s 767ms/step - loss: 2.1592e-05 - mae: 0.0030

INFO:root:File 'IE00BFTWP510.csv' loaded, 516 left


     30/Unknown - 48s 784ms/step - loss: 3.5945e-05 - mae: 0.0031

INFO:root:File 'IE00BQT3WG13.csv' loaded, 515 left


     36/Unknown - 52s 772ms/step - loss: 3.2593e-05 - mae: 0.0031

INFO:root:File 'LU1407888053.csv' loaded, 514 left


     50/Unknown - 61s 729ms/step - loss: 3.4855e-05 - mae: 0.0031

INFO:root:File 'IE00BMYDM794.csv' loaded, 513 left


     57/Unknown - 65s 711ms/step - loss: 3.2232e-05 - mae: 0.0031

INFO:root:File 'IE00B441G979.csv' loaded, 512 left


     58/Unknown - 67s 735ms/step - loss: 3.2000e-05 - mae: 0.0031

INFO:root:File 'IE00B8X9NY41.csv' loaded, 511 left


     60/Unknown - 70s 753ms/step - loss: 3.1268e-05 - mae: 0.0031

INFO:root:File 'IE00BMDH1538.csv' loaded, 510 left


     62/Unknown - 71s 748ms/step - loss: 3.0517e-05 - mae: 0.0030

INFO:root:File 'IE00BLF7VX27.csv' loaded, 509 left


     69/Unknown - 75s 732ms/step - loss: 2.8700e-05 - mae: 0.0030

INFO:root:File 'IE00BYMS5W68.csv' loaded, 508 left


     73/Unknown - 78s 732ms/step - loss: 2.7526e-05 - mae: 0.0029

INFO:root:File 'LU1079842321.csv' loaded, 507 left


     74/Unknown - 79s 730ms/step - loss: 2.7231e-05 - mae: 0.0029

INFO:root:File 'IE00BKVL7778.csv' loaded, 506 left


     75/Unknown - 80s 742ms/step - loss: 2.6925e-05 - mae: 0.0029

INFO:root:File 'LU1681045537.csv' loaded, 505 left


     77/Unknown - 83s 763ms/step - loss: 2.6415e-05 - mae: 0.0029

INFO:root:File 'IE00B60SX287.csv' loaded, 504 left


     88/Unknown - 91s 758ms/step - loss: 2.4152e-05 - mae: 0.0028

INFO:root:File 'IE00BJXRT698.csv' loaded, 503 left


     99/Unknown - 98s 740ms/step - loss: 2.2944e-05 - mae: 0.0028

2023-03-30 06:35:35.101198: I tensorflow/core/profiler/lib/profiler_session.cc:67] Profiler session collecting data.
2023-03-30 06:35:35.104830: I tensorflow/core/profiler/backends/gpu/cupti_tracer.cc:1798] CUPTI activity buffer flushed
2023-03-30 06:35:35.585342: I tensorflow/core/profiler/backends/gpu/cupti_collector.cc:521]  GpuTracer has collected 594721 callback api events and 597478 activity events. 
2023-03-30 06:35:41.455955: I tensorflow/core/profiler/lib/profiler_session.cc:128] Profiler session tear down.
2023-03-30 06:35:47.102399: I tensorflow/core/profiler/rpc/client/save_profile.cc:136] Creating directory: /content/bigdata/log/FPNWithAttentionBiggerTimebased_2_FutureOnly_60days_GPU_128LB20230330-063353/plugins/profile/2023_03_30_06_35_41

2023-03-30 06:35:51.005178: I tensorflow/core/profiler/rpc/client/save_profile.cc:142] Dumped gzipped tool data for trace.json.gz to /content/bigdata/log/FPNWithAttentionBiggerTimebased_2_FutureOnly_60days_GPU_128LB20230330-063353/plugi

    101/Unknown - 120s 947ms/step - loss: 2.2601e-05 - mae: 0.0027

INFO:root:File 'IE00B40B8R38.csv' loaded, 502 left


    104/Unknown - 122s 943ms/step - loss: 2.2112e-05 - mae: 0.0027

INFO:root:File 'IE00BYTH5T38.csv' loaded, 501 left


    106/Unknown - 124s 937ms/step - loss: 2.1797e-05 - mae: 0.0027

INFO:root:File 'IE00077FRP95.csv' loaded, 500 left


    110/Unknown - 126s 923ms/step - loss: 2.1186e-05 - mae: 0.0027

INFO:root:File 'DE0002635273.csv' loaded, 499 left


    112/Unknown - 129s 938ms/step - loss: 2.1007e-05 - mae: 0.0027

INFO:root:File 'IE00B5WHFQ43.csv' loaded, 498 left


    117/Unknown - 134s 936ms/step - loss: 2.0349e-05 - mae: 0.0026

INFO:root:File 'IE00BKVL7D31.csv' loaded, 497 left


    126/Unknown - 139s 911ms/step - loss: 1.9454e-05 - mae: 0.0026

INFO:root:File 'LU2356220926.csv' loaded, 496 left


    132/Unknown - 143s 895ms/step - loss: 1.8882e-05 - mae: 0.0025

INFO:root:File 'IE00BYZK4883.csv' loaded, 495 left


    133/Unknown - 144s 898ms/step - loss: 1.8785e-05 - mae: 0.0025

INFO:root:File 'IE00B4YBJ215.csv' loaded, 494 left


    134/Unknown - 146s 907ms/step - loss: 1.8715e-05 - mae: 0.0025

INFO:root:File 'IE00BMDKNW35.csv' loaded, 493 left


    136/Unknown - 147s 903ms/step - loss: 1.8538e-05 - mae: 0.0025

INFO:root:File 'LU1769088581.csv' loaded, 492 left


    141/Unknown - 151s 895ms/step - loss: 1.8175e-05 - mae: 0.0025

INFO:root:File 'IE00B6YX5B26.csv' loaded, 491 left


    149/Unknown - 157s 887ms/step - loss: 1.7449e-05 - mae: 0.0025

INFO:root:File 'LU2023678449.csv' loaded, 490 left


    154/Unknown - 160s 878ms/step - loss: 1.7092e-05 - mae: 0.0025

INFO:root:File 'LU1953188833.csv' loaded, 489 left


    162/Unknown - 165s 865ms/step - loss: 1.6636e-05 - mae: 0.0024

INFO:root:File 'LU1861134382.csv' loaded, 488 left


    164/Unknown - 166s 864ms/step - loss: 1.6620e-05 - mae: 0.0024

INFO:root:File 'IE00BLRPN388.csv' loaded, 487 left


    166/Unknown - 167s 861ms/step - loss: 1.6624e-05 - mae: 0.0024

INFO:root:File 'LU1781540957.csv' loaded, 486 left


    172/Unknown - 171s 854ms/step - loss: 1.6804e-05 - mae: 0.0024

INFO:root:File 'IE00BD9MMF62.csv' loaded, 485 left


    175/Unknown - 174s 852ms/step - loss: 1.7116e-05 - mae: 0.0024

INFO:root:File 'LU1806495575.csv' loaded, 484 left


    181/Unknown - 177s 846ms/step - loss: 1.6880e-05 - mae: 0.0024

INFO:root:File 'DE000A0H08N1.csv' loaded, 483 left


    186/Unknown - 183s 851ms/step - loss: 1.6857e-05 - mae: 0.0025

INFO:root:File 'LU2082997946.csv' loaded, 482 left


    193/Unknown - 187s 842ms/step - loss: 1.6609e-05 - mae: 0.0025

INFO:root:File 'DE0002635307.csv' loaded, 481 left


    194/Unknown - 188s 842ms/step - loss: 1.6565e-05 - mae: 0.0025

INFO:root:File 'IE00BWBXM492.csv' loaded, 480 left


    197/Unknown - 193s 855ms/step - loss: 1.6485e-05 - mae: 0.0025

INFO:root:File 'IE00BC7GZJ81.csv' loaded, 479 left


    198/Unknown - 195s 859ms/step - loss: 1.6463e-05 - mae: 0.0025

INFO:root:File 'LU0832436512.csv' loaded, 478 left


    200/Unknown - 197s 864ms/step - loss: 1.6379e-05 - mae: 0.0024

INFO:root:File 'IE00BD3V0B10.csv' loaded, 477 left


    204/Unknown - 200s 861ms/step - loss: 1.6283e-05 - mae: 0.0024

INFO:root:File 'IE00BYTRR863.csv' loaded, 476 left


    210/Unknown - 204s 856ms/step - loss: 1.7557e-05 - mae: 0.0025

INFO:root:File 'DE000ETFL037.csv' loaded, 475 left


    225/Unknown - 215s 846ms/step - loss: 2.2535e-05 - mae: 0.0025

INFO:root:File 'IE00B60SX170.csv' loaded, 474 left


    236/Unknown - 223s 841ms/step - loss: 2.4703e-05 - mae: 0.0026

INFO:root:File 'LU1215454460.csv' loaded, 473 left


    241/Unknown - 227s 839ms/step - loss: 2.4431e-05 - mae: 0.0026

INFO:root:File 'IE00BJXRZ273.csv' loaded, 472 left


    249/Unknown - 231s 831ms/step - loss: 2.4193e-05 - mae: 0.0026

INFO:root:File 'IE00BKT1CS59.csv' loaded, 471 left


    255/Unknown - 235s 826ms/step - loss: 2.4032e-05 - mae: 0.0026

INFO:root:File 'LU1287023342.csv' loaded, 470 left


    257/Unknown - 238s 831ms/step - loss: 2.4047e-05 - mae: 0.0027

INFO:root:File 'LU1981859819.csv' loaded, 469 left


    264/Unknown - 242s 826ms/step - loss: 2.3955e-05 - mae: 0.0027

INFO:root:File 'LU1841731745.csv' loaded, 468 left


    274/Unknown - 249s 818ms/step - loss: 2.3486e-05 - mae: 0.0026

INFO:root:File 'IE000L5NW549.csv' loaded, 467 left


    277/Unknown - 250s 815ms/step - loss: 2.3770e-05 - mae: 0.0026

INFO:root:File 'IE00B4LN9N13.csv' loaded, 466 left


    280/Unknown - 253s 815ms/step - loss: 2.3641e-05 - mae: 0.0026

INFO:root:File 'FR0010869578.csv' loaded, 465 left


    287/Unknown - 258s 815ms/step - loss: 2.3338e-05 - mae: 0.0026

INFO:root:File 'IE00BCRY6557.csv' loaded, 464 left


    293/Unknown - 263s 814ms/step - loss: 2.2981e-05 - mae: 0.0026

INFO:root:File 'LU2090062949.csv' loaded, 463 left


    297/Unknown - 265s 811ms/step - loss: 2.2744e-05 - mae: 0.0026

INFO:root:File 'IE00B5M1WJ87.csv' loaded, 462 left


    300/Unknown - 269s 814ms/step - loss: 2.2581e-05 - mae: 0.0026

INFO:root:File 'IE00B1TXHL60.csv' loaded, 461 left


    303/Unknown - 272s 818ms/step - loss: 2.3875e-05 - mae: 0.0026

INFO:root:File 'IE00BMQ8YK98.csv' loaded, 460 left


    305/Unknown - 274s 817ms/step - loss: 2.3823e-05 - mae: 0.0026

INFO:root:File 'IE00BKWQ0D84.csv' loaded, 459 left


    308/Unknown - 276s 818ms/step - loss: 2.3711e-05 - mae: 0.0026

INFO:root:File 'LU1525418643.csv' loaded, 458 left


    309/Unknown - 278s 819ms/step - loss: 2.3656e-05 - mae: 0.0026

INFO:root:File 'IE00BJK9H753.csv' loaded, 457 left


    328/Unknown - 289s 806ms/step - loss: 2.2767e-05 - mae: 0.0026

INFO:root:File 'LU2082997359.csv' loaded, 456 left


    332/Unknown - 291s 804ms/step - loss: 2.2594e-05 - mae: 0.0026

INFO:root:File 'IE00B6YX5L24.csv' loaded, 455 left


    339/Unknown - 297s 803ms/step - loss: 2.2506e-05 - mae: 0.0026

INFO:root:File 'LU2082996898.csv' loaded, 454 left


    340/Unknown - 297s 803ms/step - loss: 2.2521e-05 - mae: 0.0026

INFO:root:File 'IE00B3B8PX14.csv' loaded, 453 left


    341/Unknown - 300s 808ms/step - loss: 2.2494e-05 - mae: 0.0026

INFO:root:File 'IE00B02KXL92.csv' loaded, 452 left


    350/Unknown - 308s 810ms/step - loss: 2.5594e-05 - mae: 0.0026

INFO:root:File 'LU1681041205.csv' loaded, 451 left


    351/Unknown - 308s 809ms/step - loss: 2.5575e-05 - mae: 0.0026

INFO:root:File 'IE00BHZPJ015.csv' loaded, 450 left


    352/Unknown - 311s 814ms/step - loss: 2.5543e-05 - mae: 0.0026

INFO:root:File 'LU0959210278.csv' loaded, 449 left


    358/Unknown - 316s 814ms/step - loss: 2.5744e-05 - mae: 0.0026

INFO:root:File 'IE000KPJJWM6.csv' loaded, 448 left
INFO:root:File 'IE00BKWQ0M75.csv' loaded, 447 left


    371/Unknown - 324s 808ms/step - loss: 2.7943e-05 - mae: 0.0027

INFO:root:File 'IE000NDWFGA5.csv' loaded, 446 left


    374/Unknown - 326s 806ms/step - loss: 2.7774e-05 - mae: 0.0027

INFO:root:File 'IE00BYSZ5R67.csv' loaded, 445 left


    389/Unknown - 335s 799ms/step - loss: 2.6982e-05 - mae: 0.0026

INFO:root:File 'IE00BGJWWY63.csv' loaded, 444 left


    392/Unknown - 337s 798ms/step - loss: 2.6831e-05 - mae: 0.0026

INFO:root:File 'IE00BJK9HD13.csv' loaded, 443 left


    403/Unknown - 344s 793ms/step - loss: 2.6303e-05 - mae: 0.0026

INFO:root:File 'IE00BMH5Y871.csv' loaded, 442 left


    404/Unknown - 345s 792ms/step - loss: 2.6252e-05 - mae: 0.0026

INFO:root:File 'IE00BYV1Y969.csv' loaded, 441 left


    407/Unknown - 347s 792ms/step - loss: 2.6115e-05 - mae: 0.0026

INFO:root:File 'LU0392496427.csv' loaded, 440 left


    409/Unknown - 350s 796ms/step - loss: 2.6020e-05 - mae: 0.0026

INFO:root:File 'IE00BNDS1P30.csv' loaded, 439 left


    411/Unknown - 351s 795ms/step - loss: 2.5926e-05 - mae: 0.0026

INFO:root:File 'IE00B3CNHJ55.csv' loaded, 438 left


    412/Unknown - 353s 798ms/step - loss: 2.5882e-05 - mae: 0.0026

INFO:root:File 'DE000A0H08H3.csv' loaded, 437 left


    417/Unknown - 359s 803ms/step - loss: 2.5652e-05 - mae: 0.0026

INFO:root:File 'IE00BHXMHL11.csv' loaded, 436 left


    418/Unknown - 360s 803ms/step - loss: 2.5607e-05 - mae: 0.0026

INFO:root:File 'IE00BYTRRC02.csv' loaded, 435 left


    422/Unknown - 363s 803ms/step - loss: 2.5445e-05 - mae: 0.0026

INFO:root:File 'DE000ETF7011.csv' loaded, 434 left


    431/Unknown - 369s 800ms/step - loss: 2.5039e-05 - mae: 0.0026

INFO:root:File 'IE00BYPLS672.csv' loaded, 433 left


    437/Unknown - 374s 799ms/step - loss: 2.4802e-05 - mae: 0.0026

INFO:root:File 'IE00B2NPL135.csv' loaded, 432 left


    444/Unknown - 379s 800ms/step - loss: 2.4771e-05 - mae: 0.0026

INFO:root:File 'DE000ETFL565.csv' loaded, 431 left


    455/Unknown - 386s 794ms/step - loss: 2.4416e-05 - mae: 0.0025

INFO:root:File 'IE00BYSX4846.csv' loaded, 430 left


    457/Unknown - 388s 795ms/step - loss: 2.4323e-05 - mae: 0.0025

INFO:root:File 'IE0032895942.csv' loaded, 429 left


    459/Unknown - 392s 800ms/step - loss: 2.4234e-05 - mae: 0.0025

INFO:root:File 'LU1230561679.csv' loaded, 428 left


    471/Unknown - 399s 796ms/step - loss: 2.3759e-05 - mae: 0.0025

INFO:root:File 'IE00BZ048462.csv' loaded, 427 left


    483/Unknown - 407s 792ms/step - loss: 2.3374e-05 - mae: 0.0025

INFO:root:File 'LU1829218822.csv' loaded, 426 left


    486/Unknown - 410s 794ms/step - loss: 2.3263e-05 - mae: 0.0025

INFO:root:File 'LU2182388400.csv' loaded, 425 left


    492/Unknown - 414s 792ms/step - loss: 2.3113e-05 - mae: 0.0025

INFO:root:File 'IE00BM8R0N95.csv' loaded, 424 left


    497/Unknown - 417s 789ms/step - loss: 2.2928e-05 - mae: 0.0025

INFO:root:File 'IE00BK5BR626.csv' loaded, 423 left


    498/Unknown - 417s 789ms/step - loss: 2.2889e-05 - mae: 0.0025

INFO:root:File 'IE00B4L5YC18.csv' loaded, 422 left


    500/Unknown - 421s 792ms/step - loss: 2.2819e-05 - mae: 0.0025

INFO:root:File 'LU2197908721.csv' loaded, 421 left


    501/Unknown - 421s 792ms/step - loss: 2.2790e-05 - mae: 0.0025

INFO:root:File 'IE00B1FZS798.csv' loaded, 420 left


    512/Unknown - 430s 792ms/step - loss: 2.2468e-05 - mae: 0.0025

INFO:root:File 'IE00BYV1YH46.csv' loaded, 419 left


    515/Unknown - 432s 792ms/step - loss: 2.2379e-05 - mae: 0.0025

INFO:root:File 'IE00B3YLTY66.csv' loaded, 418 left


    521/Unknown - 437s 792ms/step - loss: 2.2195e-05 - mae: 0.0025

INFO:root:File 'IE00BL0BMZ89.csv' loaded, 417 left


    527/Unknown - 441s 790ms/step - loss: 2.2067e-05 - mae: 0.0025

INFO:root:File 'IE000EBFYWX3.csv' loaded, 416 left


    531/Unknown - 443s 788ms/step - loss: 2.1938e-05 - mae: 0.0025

INFO:root:File 'LU1829219390.csv' loaded, 415 left


    534/Unknown - 446s 789ms/step - loss: 2.1840e-05 - mae: 0.0024

INFO:root:File 'DE0005933931.csv' loaded, 414 left


    540/Unknown - 453s 793ms/step - loss: 2.1670e-05 - mae: 0.0024

INFO:root:File 'IE00BFYN8Y92.csv' loaded, 413 left


    557/Unknown - 463s 787ms/step - loss: 2.1230e-05 - mae: 0.0024

INFO:root:File 'DE0006289499.csv' loaded, 412 left


    563/Unknown - 469s 789ms/step - loss: 2.1081e-05 - mae: 0.0024

INFO:root:File 'LU1812090543.csv' loaded, 411 left


    568/Unknown - 473s 790ms/step - loss: 2.0948e-05 - mae: 0.0024

INFO:root:File 'DE0006289390.csv' loaded, 410 left


    572/Unknown - 479s 794ms/step - loss: 2.0859e-05 - mae: 0.0024

INFO:root:File 'IE00BM9GRM34.csv' loaded, 409 left


    580/Unknown - 483s 791ms/step - loss: 2.0767e-05 - mae: 0.0024

INFO:root:File 'DE0002635299.csv' loaded, 408 left


    581/Unknown - 486s 794ms/step - loss: 2.0751e-05 - mae: 0.0024

INFO:root:File 'LU1377382368.csv' loaded, 407 left


    582/Unknown - 487s 795ms/step - loss: 2.0737e-05 - mae: 0.0024

INFO:root:File 'LU1437015735.csv' loaded, 406 left


    592/Unknown - 494s 793ms/step - loss: 2.0621e-05 - mae: 0.0024

INFO:root:File 'IE00B7452L46.csv' loaded, 405 left


    612/Unknown - 507s 788ms/step - loss: 2.0330e-05 - mae: 0.0024

INFO:root:File 'IE00BYTRRB94.csv' loaded, 404 left


    616/Unknown - 510s 788ms/step - loss: 2.0265e-05 - mae: 0.0024

INFO:root:File 'IE00BHZRQY00.csv' loaded, 403 left


    630/Unknown - 518s 784ms/step - loss: 1.9937e-05 - mae: 0.0024

INFO:root:File 'LU1437018168.csv' loaded, 402 left


    635/Unknown - 522s 783ms/step - loss: 1.9837e-05 - mae: 0.0024

INFO:root:File 'LU1291098827.csv' loaded, 401 left


    649/Unknown - 531s 780ms/step - loss: 1.9522e-05 - mae: 0.0024

INFO:root:File 'LU1681042609.csv' loaded, 400 left


    653/Unknown - 535s 781ms/step - loss: 1.9520e-05 - mae: 0.0024

INFO:root:File 'LU1681047319.csv' loaded, 399 left


    658/Unknown - 539s 782ms/step - loss: 1.9464e-05 - mae: 0.0024

INFO:root:File 'LU1681044480.csv' loaded, 398 left


    664/Unknown - 544s 783ms/step - loss: 1.9388e-05 - mae: 0.0024

INFO:root:File 'IE00BKWQ0F09.csv' loaded, 397 left


    668/Unknown - 547s 783ms/step - loss: 1.9322e-05 - mae: 0.0024

INFO:root:File 'DE000A0Q4R36.csv' loaded, 396 left


    673/Unknown - 553s 786ms/step - loss: 1.9225e-05 - mae: 0.0024

INFO:root:File 'LU1900066975.csv' loaded, 395 left


    680/Unknown - 559s 786ms/step - loss: 1.9098e-05 - mae: 0.0024

INFO:root:File 'LU2109786827.csv' loaded, 394 left


    688/Unknown - 564s 784ms/step - loss: 1.8957e-05 - mae: 0.0024

INFO:root:File 'IE00B4L5Y983.csv' loaded, 393 left


    694/Unknown - 569s 785ms/step - loss: 1.9111e-05 - mae: 0.0024

INFO:root:File 'IE00BZ4BMM98.csv' loaded, 392 left


    709/Unknown - 579s 782ms/step - loss: 1.9365e-05 - mae: 0.0024

INFO:root:File 'FR0011475078.csv' loaded, 391 left


    723/Unknown - 588s 779ms/step - loss: 1.9168e-05 - mae: 0.0024

INFO:root:File 'IE00B5MTYK77.csv' loaded, 390 left


    724/Unknown - 590s 781ms/step - loss: 1.9150e-05 - mae: 0.0024

INFO:root:File 'LU0629460089.csv' loaded, 389 left


    729/Unknown - 595s 782ms/step - loss: 1.9104e-05 - mae: 0.0024

INFO:root:File 'IE00BJK9H860.csv' loaded, 388 left


    732/Unknown - 597s 782ms/step - loss: 1.9053e-05 - mae: 0.0024

INFO:root:File 'IE00BWTNM966.csv' loaded, 387 left


    750/Unknown - 608s 778ms/step - loss: 1.8754e-05 - mae: 0.0023

INFO:root:File 'IE00B52SF786.csv' loaded, 386 left


    763/Unknown - 617s 777ms/step - loss: 1.8529e-05 - mae: 0.0023

INFO:root:File 'IE00BKWQ0P07.csv' loaded, 385 left


    764/Unknown - 618s 777ms/step - loss: 1.8508e-05 - mae: 0.0023

INFO:root:File 'LU1650491795.csv' loaded, 384 left


    765/Unknown - 619s 778ms/step - loss: 1.8489e-05 - mae: 0.0023

INFO:root:File 'IE00BHJYDV33.csv' loaded, 383 left


    770/Unknown - 623s 777ms/step - loss: 1.8400e-05 - mae: 0.0023

INFO:root:File 'IE00BYZK4669.csv' loaded, 382 left


    775/Unknown - 627s 777ms/step - loss: 1.8315e-05 - mae: 0.0023

INFO:root:File 'IE00B1FZS350.csv' loaded, 381 left


    786/Unknown - 635s 777ms/step - loss: 1.8171e-05 - mae: 0.0023

INFO:root:File 'IE00BLRPRR04.csv' loaded, 380 left


    787/Unknown - 636s 776ms/step - loss: 1.8158e-05 - mae: 0.0023

INFO:root:File 'LU0603940916.csv' loaded, 379 left


    791/Unknown - 639s 777ms/step - loss: 1.8094e-05 - mae: 0.0023

INFO:root:File 'IE00B979GK47.csv' loaded in retry loop, 378 left


    793/Unknown - 641s 777ms/step - loss: 1.8058e-05 - mae: 0.0023

INFO:root:File 'IE00BYPC1H27.csv' loaded, 377 left


    799/Unknown - 645s 776ms/step - loss: 1.7956e-05 - mae: 0.0023

INFO:root:File 'DE000ETFL482.csv' loaded, 376 left


    805/Unknown - 649s 776ms/step - loss: 1.7871e-05 - mae: 0.0023

INFO:root:File 'LU2056739464.csv' loaded, 375 left


    808/Unknown - 651s 775ms/step - loss: 1.7824e-05 - mae: 0.0023

INFO:root:File 'IE000ST40PX8.csv' loaded, 374 left


    809/Unknown - 652s 775ms/step - loss: 1.7808e-05 - mae: 0.0023

INFO:root:File 'IE00BQN1K901.csv' loaded, 373 left


    810/Unknown - 653s 776ms/step - loss: 1.7792e-05 - mae: 0.0023

INFO:root:File 'IE00BKWQ0C77.csv' loaded, 372 left


    812/Unknown - 655s 777ms/step - loss: 1.7763e-05 - mae: 0.0023

INFO:root:File 'IE00BJQRDM08.csv' loaded, 371 left


    819/Unknown - 660s 776ms/step - loss: 1.7679e-05 - mae: 0.0023

INFO:root:File 'IE00B8FHGS14.csv' loaded, 370 left


    822/Unknown - 663s 776ms/step - loss: 1.7667e-05 - mae: 0.0023

INFO:root:File 'IE00B1FZS913.csv' loaded, 369 left


    831/Unknown - 670s 777ms/step - loss: 1.7565e-05 - mae: 0.0023

INFO:root:File 'LU2198883410.csv' loaded, 368 left


    839/Unknown - 675s 775ms/step - loss: 1.7452e-05 - mae: 0.0023

INFO:root:File 'IE00B5MTZM66.csv' loaded, 367 left


    844/Unknown - 679s 776ms/step - loss: 1.7387e-05 - mae: 0.0023

INFO:root:File 'IE00B1W57M07.csv' loaded, 366 left


    853/Unknown - 687s 776ms/step - loss: 1.7277e-05 - mae: 0.0023

INFO:root:File 'IE00BMDBMT65.csv' loaded, 365 left


    854/Unknown - 687s 776ms/step - loss: 1.7305e-05 - mae: 0.0023

INFO:root:File 'LU1681039134.csv' loaded, 364 left


    855/Unknown - 688s 776ms/step - loss: 1.7778e-05 - mae: 0.0023

INFO:root:File 'LU1681041544.csv' loaded, 363 left


    863/Unknown - 695s 777ms/step - loss: 1.7671e-05 - mae: 0.0023

INFO:root:File 'IE00B8GF1M35.csv' loaded, 362 left


    867/Unknown - 699s 778ms/step - loss: 1.7612e-05 - mae: 0.0023

INFO:root:File 'FR0010361683.csv' loaded, 361 left


    876/Unknown - 706s 778ms/step - loss: 1.7584e-05 - mae: 0.0023

INFO:root:File 'IE00BDDRF478.csv' loaded, 360 left


    895/Unknown - 717s 774ms/step - loss: 1.7423e-05 - mae: 0.0023

INFO:root:File 'IE00BGBN6P67.csv' loaded, 359 left


    899/Unknown - 720s 774ms/step - loss: 1.7366e-05 - mae: 0.0023

INFO:root:File 'LU1650488494.csv' loaded, 358 left


    913/Unknown - 731s 774ms/step - loss: 1.7325e-05 - mae: 0.0023

INFO:root:File 'LU1681045024.csv' loaded, 357 left


    915/Unknown - 734s 775ms/step - loss: 1.7302e-05 - mae: 0.0023

INFO:root:File 'IE00BYXVGY31.csv' loaded, 356 left


    916/Unknown - 735s 775ms/step - loss: 1.7291e-05 - mae: 0.0023

INFO:root:File 'IE00BFNM3B99.csv' loaded, 355 left


    920/Unknown - 738s 775ms/step - loss: 1.7252e-05 - mae: 0.0023

INFO:root:File 'IE00BHZRQZ17.csv' loaded, 354 left


    932/Unknown - 745s 773ms/step - loss: 1.7117e-05 - mae: 0.0023

INFO:root:File 'IE0032077012.csv' loaded, 353 left


    937/Unknown - 750s 775ms/step - loss: 1.7182e-05 - mae: 0.0023

INFO:root:File 'IE00BFXR5W90.csv' loaded, 352 left


    939/Unknown - 752s 775ms/step - loss: 1.7169e-05 - mae: 0.0023

INFO:root:File 'LU2244386053.csv' loaded, 351 left


    940/Unknown - 753s 775ms/step - loss: 1.7165e-05 - mae: 0.0023

INFO:root:File 'IE00B3VTML14.csv' loaded, 350 left


    947/Unknown - 758s 775ms/step - loss: 1.7143e-05 - mae: 0.0023

INFO:root:File 'FR0007056841.csv' loaded, 349 left


    949/Unknown - 763s 778ms/step - loss: 1.7128e-05 - mae: 0.0023

INFO:root:File 'IE00B23LNQ02.csv' loaded, 348 left


    958/Unknown - 770s 778ms/step - loss: 1.7023e-05 - mae: 0.0023

INFO:root:File 'IE00BG5J1M21.csv' loaded, 347 left


    959/Unknown - 771s 778ms/step - loss: 1.7011e-05 - mae: 0.0023

INFO:root:File 'IE00BMFNW783.csv' loaded, 346 left


    967/Unknown - 776s 777ms/step - loss: 1.6926e-05 - mae: 0.0023

INFO:root:File 'DE000ETF7037.csv' loaded, 345 left


    974/Unknown - 780s 776ms/step - loss: 1.6865e-05 - mae: 0.0023

INFO:root:File 'FR0011550185.csv' loaded, 344 left


    979/Unknown - 784s 776ms/step - loss: 1.6828e-05 - mae: 0.0023

INFO:root:File 'IE000XGNMWE1.csv' loaded in retry loop, 343 left


    983/Unknown - 787s 775ms/step - loss: 1.6788e-05 - mae: 0.0023

INFO:root:File 'LU1215461325.csv' loaded, 342 left


    994/Unknown - 794s 774ms/step - loss: 1.6799e-05 - mae: 0.0023

INFO:root:File 'DE000A0D8Q31.csv' loaded, 341 left


   1006/Unknown - 803s 774ms/step - loss: 1.6742e-05 - mae: 0.0023

INFO:root:File 'LU1437017350.csv' loaded, 340 left


   1015/Unknown - 809s 773ms/step - loss: 1.6671e-05 - mae: 0.0023

INFO:root:File 'IE00B14X4N27.csv' loaded, 339 left


   1023/Unknown - 816s 773ms/step - loss: 1.6592e-05 - mae: 0.0023

INFO:root:File 'LU1681043599.csv' loaded, 338 left


   1026/Unknown - 819s 774ms/step - loss: 1.6555e-05 - mae: 0.0023

INFO:root:File 'IE00BKP5L730.csv' loaded, 337 left


   1034/Unknown - 824s 773ms/step - loss: 1.6503e-05 - mae: 0.0023

INFO:root:File 'IE00B5MTYL84.csv' loaded, 336 left


   1037/Unknown - 827s 774ms/step - loss: 1.6472e-05 - mae: 0.0023

INFO:root:File 'IE00BYTH5R14.csv' loaded, 335 left


   1042/Unknown - 830s 773ms/step - loss: 1.6427e-05 - mae: 0.0023

INFO:root:File 'LU0136234068.csv' loaded, 334 left


   1045/Unknown - 835s 776ms/step - loss: 1.6410e-05 - mae: 0.0023

INFO:root:File 'IE00BFNM3F38.csv' loaded, 333 left


   1046/Unknown - 836s 776ms/step - loss: 1.6398e-05 - mae: 0.0023

INFO:root:File 'IE00B4WXJG34.csv' loaded, 332 left


   1068/Unknown - 851s 773ms/step - loss: 1.6186e-05 - mae: 0.0023

INFO:root:File 'IE00B4WXJH41.csv' loaded, 331 left


   1070/Unknown - 853s 775ms/step - loss: 1.6166e-05 - mae: 0.0023

INFO:root:File 'IE00BDDRDW15.csv' loaded, 330 left


   1091/Unknown - 866s 771ms/step - loss: 1.5947e-05 - mae: 0.0022

INFO:root:File 'LU1681041627.csv' loaded, 329 left


   1093/Unknown - 869s 773ms/step - loss: 1.5923e-05 - mae: 0.0022

INFO:root:File 'LU1650492256.csv' loaded, 328 left


   1099/Unknown - 873s 772ms/step - loss: 1.5866e-05 - mae: 0.0022

INFO:root:File 'FR0010342592.csv' loaded, 327 left


   1109/Unknown - 881s 773ms/step - loss: 1.5757e-05 - mae: 0.0022

INFO:root:File 'DE000A0D8Q49.csv' loaded, 326 left


   1110/Unknown - 883s 773ms/step - loss: 1.5746e-05 - mae: 0.0022

INFO:root:File 'IE00BMCZLJ20.csv' loaded, 325 left


   1122/Unknown - 891s 773ms/step - loss: 1.5647e-05 - mae: 0.0022

INFO:root:File 'LU1681040496.csv' loaded, 324 left


   1123/Unknown - 893s 773ms/step - loss: 1.5637e-05 - mae: 0.0022

INFO:root:File 'IE00BDQYWQ65.csv' loaded, 323 left


   1142/Unknown - 905s 771ms/step - loss: 1.5493e-05 - mae: 0.0022

INFO:root:File 'LU1602144575.csv' loaded, 322 left


   1145/Unknown - 907s 771ms/step - loss: 1.5480e-05 - mae: 0.0022

INFO:root:File 'IE00BKM4H312.csv' loaded, 321 left


   1154/Unknown - 913s 770ms/step - loss: 1.5493e-05 - mae: 0.0022

INFO:root:File 'IE00BFNM3G45.csv' loaded, 320 left


   1162/Unknown - 918s 769ms/step - loss: 1.5481e-05 - mae: 0.0022

INFO:root:File 'LU1686832277.csv' loaded, 319 left


   1169/Unknown - 923s 768ms/step - loss: 1.5432e-05 - mae: 0.0022

INFO:root:File 'LU1437018838.csv' loaded, 318 left


   1173/Unknown - 926s 768ms/step - loss: 1.5443e-05 - mae: 0.0022

INFO:root:File 'IE00B5MTWY73.csv' loaded, 317 left


   1174/Unknown - 928s 770ms/step - loss: 1.5434e-05 - mae: 0.0022

INFO:root:File 'IE00BYVJRP78.csv' loaded, 316 left


   1175/Unknown - 929s 770ms/step - loss: 1.5435e-05 - mae: 0.0022

INFO:root:File 'LU1834986900.csv' loaded, 315 left


   1177/Unknown - 933s 772ms/step - loss: 1.5448e-05 - mae: 0.0022

INFO:root:File 'IE000IM4K4K2.csv' loaded, 314 left


   1178/Unknown - 934s 772ms/step - loss: 1.5445e-05 - mae: 0.0022

INFO:root:File 'LU0496786574.csv' loaded, 313 left


   1192/Unknown - 943s 771ms/step - loss: 1.5360e-05 - mae: 0.0022

INFO:root:File 'IE00BGPP6473.csv' loaded, 312 left


   1193/Unknown - 944s 771ms/step - loss: 1.5353e-05 - mae: 0.0022

INFO:root:File 'LU2023678282.csv' loaded, 311 left


   1203/Unknown - 950s 769ms/step - loss: 1.5317e-05 - mae: 0.0022

INFO:root:File 'LU1280303014.csv' loaded, 310 left


   1206/Unknown - 953s 770ms/step - loss: 1.5306e-05 - mae: 0.0022

INFO:root:File 'IE00BG0J4C88.csv' loaded, 309 left


   1207/Unknown - 953s 770ms/step - loss: 1.5317e-05 - mae: 0.0022

INFO:root:File 'IE00BJXRZJ40.csv' loaded, 308 left


   1209/Unknown - 955s 770ms/step - loss: 1.5338e-05 - mae: 0.0022

INFO:root:File 'IE00B0M62Q58.csv' loaded, 307 left


   1213/Unknown - 960s 771ms/step - loss: 1.5358e-05 - mae: 0.0022

INFO:root:File 'IE00B5MTWD60.csv' loaded, 306 left


   1223/Unknown - 967s 771ms/step - loss: 1.5325e-05 - mae: 0.0022

INFO:root:File 'IE00B3ZW0K18.csv' loaded, 305 left


   1229/Unknown - 972s 771ms/step - loss: 1.5310e-05 - mae: 0.0022

INFO:root:File 'IE00B6TLBW47.csv' loaded, 304 left


   1242/Unknown - 981s 770ms/step - loss: 1.5258e-05 - mae: 0.0022

INFO:root:File 'LU1829219713.csv' loaded, 303 left


   1249/Unknown - 987s 770ms/step - loss: 1.5234e-05 - mae: 0.0022

INFO:root:File 'LU1291101555.csv' loaded, 302 left


   1250/Unknown - 988s 771ms/step - loss: 1.5231e-05 - mae: 0.0022

INFO:root:File 'IE00B6S2Z822.csv' loaded, 301 left


   1266/Unknown - 999s 770ms/step - loss: 1.5145e-05 - mae: 0.0022

INFO:root:File 'LU1215415214.csv' loaded, 300 left


   1287/Unknown - 1012s 767ms/step - loss: 1.5010e-05 - mae: 0.0022

INFO:root:File 'DE000A0H08J9.csv' loaded, 299 left


   1289/Unknown - 1016s 769ms/step - loss: 1.4993e-05 - mae: 0.0022

INFO:root:File 'IE00B0M63284.csv' loaded, 298 left


   1290/Unknown - 1019s 771ms/step - loss: 1.4984e-05 - mae: 0.0022

INFO:root:File 'LU1681044720.csv' loaded, 297 left


   1292/Unknown - 1022s 772ms/step - loss: 1.4965e-05 - mae: 0.0022

INFO:root:File 'LU0950381748.csv' loaded, 296 left


   1304/Unknown - 1030s 771ms/step - loss: 1.4874e-05 - mae: 0.0022

INFO:root:File 'IE00B5377D42.csv' loaded, 295 left


   1306/Unknown - 1033s 772ms/step - loss: 1.4867e-05 - mae: 0.0022

INFO:root:File 'LU1852211215.csv' loaded, 294 left


   1309/Unknown - 1035s 772ms/step - loss: 1.4870e-05 - mae: 0.0022

INFO:root:File 'IE00BSKRJZ44.csv' loaded, 293 left


   1310/Unknown - 1036s 772ms/step - loss: 1.4868e-05 - mae: 0.0022

INFO:root:File 'IE00B4L5ZG21.csv' loaded, 292 left


   1329/Unknown - 1049s 771ms/step - loss: 1.4774e-05 - mae: 0.0022

INFO:root:File 'IE00B449XP68.csv' loaded, 291 left


   1344/Unknown - 1059s 770ms/step - loss: 1.4728e-05 - mae: 0.0022

INFO:root:File 'IE00BDFK1573.csv' loaded, 290 left


   1353/Unknown - 1065s 769ms/step - loss: 1.4670e-05 - mae: 0.0022

INFO:root:File 'IE00B3VWM098.csv' loaded, 289 left


   1370/Unknown - 1077s 768ms/step - loss: 1.4582e-05 - mae: 0.0022

INFO:root:File 'IE00BG0J4841.csv' loaded, 288 left


   1371/Unknown - 1077s 768ms/step - loss: 1.4576e-05 - mae: 0.0022

INFO:root:File 'IE00BNGFMY78.csv' loaded, 287 left


   1377/Unknown - 1081s 767ms/step - loss: 1.4580e-05 - mae: 0.0022

INFO:root:File 'IE00BX7RR706.csv' loaded, 286 left


   1380/Unknown - 1084s 767ms/step - loss: 1.4766e-05 - mae: 0.0022

INFO:root:File 'LU1602144229.csv' loaded, 285 left


   1384/Unknown - 1087s 767ms/step - loss: 1.4735e-05 - mae: 0.0022

INFO:root:File 'IE00BYML9W36.csv' loaded, 284 left


   1386/Unknown - 1089s 768ms/step - loss: 1.4721e-05 - mae: 0.0022

INFO:root:File 'IE00BQN1K562.csv' loaded, 283 left


   1393/Unknown - 1094s 768ms/step - loss: 1.5380e-05 - mae: 0.0022

INFO:root:File 'IE0002MXIF34.csv' loaded, 282 left


   1394/Unknown - 1094s 767ms/step - loss: 1.5377e-05 - mae: 0.0022

INFO:root:File 'IE00BYVZV757.csv' loaded, 281 left


   1402/Unknown - 1099s 767ms/step - loss: 1.5342e-05 - mae: 0.0022

INFO:root:File 'IE00BX7RRJ27.csv' loaded, 280 left


   1403/Unknown - 1101s 767ms/step - loss: 1.5336e-05 - mae: 0.0022

INFO:root:File 'LU0832435464.csv' loaded, 279 left


   1412/Unknown - 1108s 767ms/step - loss: 1.5279e-05 - mae: 0.0022

INFO:root:File 'IE00B41RYL63.csv' loaded, 278 left


   1418/Unknown - 1113s 767ms/step - loss: 1.5255e-05 - mae: 0.0022

INFO:root:File 'IE00BLSNMW37.csv' loaded, 277 left


   1420/Unknown - 1115s 768ms/step - loss: 1.5243e-05 - mae: 0.0022

INFO:root:File 'IE00BCRY6003.csv' loaded, 276 left


   1424/Unknown - 1118s 768ms/step - loss: 1.5212e-05 - mae: 0.0022

INFO:root:File 'IE00BMDX0M10.csv' loaded, 275 left


   1429/Unknown - 1121s 768ms/step - loss: 1.5185e-05 - mae: 0.0022

INFO:root:File 'DE000ETF7029.csv' loaded, 274 left


   1430/Unknown - 1122s 768ms/step - loss: 1.5178e-05 - mae: 0.0022

INFO:root:File 'IE00BFD2H405.csv' loaded, 273 left


   1437/Unknown - 1127s 767ms/step - loss: 1.5137e-05 - mae: 0.0022

INFO:root:File 'LU1437018598.csv' loaded, 272 left


   1443/Unknown - 1131s 767ms/step - loss: 1.5105e-05 - mae: 0.0022

INFO:root:File 'LU0480132876.csv' loaded, 271 left


   1451/Unknown - 1137s 767ms/step - loss: 1.5328e-05 - mae: 0.0022

INFO:root:File 'IE00B0M62X26.csv' loaded, 270 left


   1456/Unknown - 1142s 768ms/step - loss: 1.5317e-05 - mae: 0.0022

INFO:root:File 'IE00BF59RW70.csv' loaded, 269 left


   1461/Unknown - 1146s 767ms/step - loss: 1.5287e-05 - mae: 0.0022

INFO:root:File 'IE00B3S5XW04.csv' loaded, 268 left


   1463/Unknown - 1148s 768ms/step - loss: 1.5271e-05 - mae: 0.0022

INFO:root:File 'IE00BYTRR970.csv' loaded, 267 left


   1470/Unknown - 1153s 768ms/step - loss: 1.5298e-05 - mae: 0.0022

INFO:root:File 'LU1681040819.csv' loaded, 266 left


   1472/Unknown - 1156s 769ms/step - loss: 1.5296e-05 - mae: 0.0022

INFO:root:File 'IE00B02KXK85.csv' loaded, 265 left


   1477/Unknown - 1161s 770ms/step - loss: 1.5669e-05 - mae: 0.0022

INFO:root:File 'LU1799934903.csv' loaded, 264 left


   1478/Unknown - 1162s 770ms/step - loss: 1.5666e-05 - mae: 0.0022

INFO:root:File 'IE00BK5BC891.csv' loaded, 263 left


   1485/Unknown - 1166s 769ms/step - loss: 1.5635e-05 - mae: 0.0022

INFO:root:File 'IE00B4WXJD03.csv' loaded, 262 left


   1497/Unknown - 1175s 769ms/step - loss: 1.5589e-05 - mae: 0.0022

INFO:root:File 'LU1681041890.csv' loaded, 261 left


   1500/Unknown - 1178s 769ms/step - loss: 1.5858e-05 - mae: 0.0022

INFO:root:File 'IE00BJK3WF00.csv' loaded, 260 left


   1511/Unknown - 1184s 768ms/step - loss: 1.5872e-05 - mae: 0.0022

INFO:root:File 'DE000ETFL540.csv' loaded, 259 left


   1519/Unknown - 1189s 767ms/step - loss: 1.5869e-05 - mae: 0.0022

INFO:root:File 'IE00BYSX4739.csv' loaded, 258 left


   1524/Unknown - 1192s 766ms/step - loss: 1.5851e-05 - mae: 0.0022

INFO:root:File 'IE00BJ5JNZ06.csv' loaded, 257 left


   1526/Unknown - 1194s 766ms/step - loss: 1.5843e-05 - mae: 0.0022

INFO:root:File 'IE00B3VPKB53.csv' loaded, 256 left


   1534/Unknown - 1200s 766ms/step - loss: 1.5809e-05 - mae: 0.0022

INFO:root:File 'IE00B5L8K969.csv' loaded, 255 left


   1537/Unknown - 1203s 767ms/step - loss: 1.5785e-05 - mae: 0.0022

INFO:root:File 'DE000A0F5UH1.csv' loaded, 254 left


   1541/Unknown - 1207s 768ms/step - loss: 1.5751e-05 - mae: 0.0022

INFO:root:File 'IE00B2QWDR12.csv' loaded, 253 left


   1542/Unknown - 1209s 768ms/step - loss: 1.5743e-05 - mae: 0.0022

INFO:root:File 'IE00BK5BCH80.csv' loaded, 252 left


   1548/Unknown - 1214s 768ms/step - loss: 1.5706e-05 - mae: 0.0022

INFO:root:File 'LU0721552973.csv' loaded, 251 left


   1552/Unknown - 1217s 769ms/step - loss: 1.5677e-05 - mae: 0.0022

INFO:root:File 'IE00BMZ17W23.csv' loaded, 250 left


   1562/Unknown - 1223s 767ms/step - loss: 1.5668e-05 - mae: 0.0022

INFO:root:File 'LU0446734526.csv' loaded, 249 left


   1563/Unknown - 1224s 767ms/step - loss: 1.5661e-05 - mae: 0.0022

INFO:root:File 'DE000ETFL029.csv' loaded, 248 left


   1575/Unknown - 1235s 768ms/step - loss: 1.5585e-05 - mae: 0.0022

INFO:root:File 'IE00BYYW2V44.csv' loaded, 247 left


   1597/Unknown - 1248s 766ms/step - loss: 1.5494e-05 - mae: 0.0022

INFO:root:File 'LU1781541252.csv' loaded, 246 left


   1599/Unknown - 1249s 766ms/step - loss: 1.5479e-05 - mae: 0.0022

INFO:root:File 'LU2082999306.csv' loaded, 245 left


   1603/Unknown - 1252s 766ms/step - loss: 1.5460e-05 - mae: 0.0022

INFO:root:File 'IE00BYTRRG40.csv' loaded, 244 left


   1609/Unknown - 1256s 765ms/step - loss: 1.5424e-05 - mae: 0.0022

INFO:root:File 'IE000KDY10O3.csv' loaded, 243 left


   1611/Unknown - 1257s 765ms/step - loss: 1.5416e-05 - mae: 0.0022

INFO:root:File 'LU1681049109.csv' loaded, 242 left


   1612/Unknown - 1258s 765ms/step - loss: 1.5410e-05 - mae: 0.0022

INFO:root:File 'IE00BNG8L278.csv' loaded, 241 left


   1613/Unknown - 1259s 765ms/step - loss: 1.5404e-05 - mae: 0.0022

INFO:root:File 'LU1681043086.csv' loaded, 240 left


   1620/Unknown - 1265s 766ms/step - loss: 1.5360e-05 - mae: 0.0022

INFO:root:File 'IE00BF11F458.csv' loaded, 239 left


   1624/Unknown - 1268s 766ms/step - loss: 1.5336e-05 - mae: 0.0022

INFO:root:File 'IE00BYSX4283.csv' loaded, 238 left


   1625/Unknown - 1269s 766ms/step - loss: 1.5329e-05 - mae: 0.0022

INFO:root:File 'LU2082997516.csv' loaded, 237 left


   1637/Unknown - 1276s 765ms/step - loss: 1.5547e-05 - mae: 0.0022

INFO:root:File 'IE00BKLWY790.csv' loaded, 236 left


   1638/Unknown - 1277s 765ms/step - loss: 1.5541e-05 - mae: 0.0022

INFO:root:File 'DE000ETF9033.csv' loaded, 235 left


   1640/Unknown - 1279s 765ms/step - loss: 1.5530e-05 - mae: 0.0022

INFO:root:File 'IE00BLDGH553.csv' loaded, 234 left


   1642/Unknown - 1280s 765ms/step - loss: 1.5518e-05 - mae: 0.0022

INFO:root:File 'LU1681040223.csv' loaded, 233 left


   1647/Unknown - 1285s 765ms/step - loss: 1.5500e-05 - mae: 0.0022

INFO:root:File 'IE0002PG6CA6.csv' loaded, 232 left


   1650/Unknown - 1287s 765ms/step - loss: 1.5482e-05 - mae: 0.0022

INFO:root:File 'IE00BD4TYG73.csv' loaded, 231 left


   1652/Unknown - 1289s 766ms/step - loss: 1.5468e-05 - mae: 0.0022

INFO:root:File 'IE00BGL86Z12.csv' loaded, 230 left


   1653/Unknown - 1290s 766ms/step - loss: 1.5479e-05 - mae: 0.0022

INFO:root:File 'LU1681046857.csv' loaded, 229 left


   1654/Unknown - 1291s 766ms/step - loss: 1.5796e-05 - mae: 0.0022

INFO:root:File 'IE000APK27S2.csv' loaded, 228 left


   1655/Unknown - 1292s 766ms/step - loss: 1.5947e-05 - mae: 0.0022

INFO:root:File 'IE00B4K48X80.csv' loaded, 227 left


   1660/Unknown - 1297s 766ms/step - loss: 1.6473e-05 - mae: 0.0022

INFO:root:File 'IE00B7KQ7B66.csv' loaded, 226 left


   1673/Unknown - 1306s 766ms/step - loss: 1.6954e-05 - mae: 0.0022

INFO:root:File 'IE00BMFNWC33.csv' loaded, 225 left


   1676/Unknown - 1307s 765ms/step - loss: 1.6935e-05 - mae: 0.0022

INFO:root:File 'LU1650489385.csv' loaded, 224 left


   1681/Unknown - 1313s 766ms/step - loss: 1.6918e-05 - mae: 0.0022

INFO:root:File 'IE00B53QDK08.csv' loaded, 223 left


   1690/Unknown - 1320s 766ms/step - loss: 1.6872e-05 - mae: 0.0022

INFO:root:File 'LU1753045415.csv' loaded, 222 left


   1691/Unknown - 1321s 767ms/step - loss: 1.6865e-05 - mae: 0.0022

INFO:root:File 'IE00BFNM3M05.csv' loaded, 221 left


   1702/Unknown - 1328s 766ms/step - loss: 1.6803e-05 - mae: 0.0022

INFO:root:File 'IE00BD8PGZ49.csv' loaded, 220 left


   1714/Unknown - 1335s 765ms/step - loss: 1.6737e-05 - mae: 0.0022

INFO:root:File 'LU2206598109.csv' loaded, 219 left


   1717/Unknown - 1337s 764ms/step - loss: 1.6716e-05 - mae: 0.0022

INFO:root:File 'NL0010273801.csv' loaded, 218 left


   1718/Unknown - 1339s 765ms/step - loss: 1.6709e-05 - mae: 0.0022

INFO:root:File 'IE00BF0M2Z96.csv' loaded, 217 left


   1720/Unknown - 1341s 765ms/step - loss: 1.6704e-05 - mae: 0.0022

INFO:root:File 'IE00B23D9570.csv' loaded, 216 left


   1724/Unknown - 1345s 766ms/step - loss: 1.6674e-05 - mae: 0.0022

INFO:root:File 'IE00B0M63391.csv' loaded, 215 left


   1727/Unknown - 1349s 767ms/step - loss: 1.6652e-05 - mae: 0.0022

INFO:root:File 'IE000QNJAOX1.csv' loaded, 214 left


   1728/Unknown - 1349s 767ms/step - loss: 1.6644e-05 - mae: 0.0022

INFO:root:File 'IE000YKE1AQ5.csv' loaded, 213 left


   1731/Unknown - 1351s 766ms/step - loss: 1.6627e-05 - mae: 0.0022

INFO:root:File 'IE00BMTX1Y45.csv' loaded, 212 left


   1732/Unknown - 1352s 766ms/step - loss: 1.6619e-05 - mae: 0.0022

INFO:root:File 'DE000ETFL557.csv' loaded, 211 left


   1742/Unknown - 1358s 765ms/step - loss: 1.6546e-05 - mae: 0.0022

INFO:root:File 'IE00BKVD2J03.csv' loaded, 210 left


   1744/Unknown - 1359s 765ms/step - loss: 1.6533e-05 - mae: 0.0022

INFO:root:File 'LU0603942888.csv' loaded, 209 left


   1745/Unknown - 1361s 766ms/step - loss: 1.6527e-05 - mae: 0.0022

INFO:root:File 'IE00BZ0G8860.csv' loaded, 208 left


   1751/Unknown - 1366s 766ms/step - loss: 1.6493e-05 - mae: 0.0022

INFO:root:File 'IE00BD1F4M44.csv' loaded in retry loop, 207 left


   1753/Unknown - 1368s 766ms/step - loss: 1.6479e-05 - mae: 0.0022

INFO:root:File 'IE00BF2B0L69.csv' loaded, 206 left


   1773/Unknown - 1380s 764ms/step - loss: 1.6413e-05 - mae: 0.0022

INFO:root:File 'IE000MWUQBJ0.csv' loaded, 205 left


   1775/Unknown - 1381s 764ms/step - loss: 1.6412e-05 - mae: 0.0022

INFO:root:File 'IE00B1FZS806.csv' loaded, 204 left


   1783/Unknown - 1388s 765ms/step - loss: 1.6379e-05 - mae: 0.0022

INFO:root:File 'IE00B6YX5D40.csv' loaded, 203 left


   1784/Unknown - 1390s 765ms/step - loss: 1.6375e-05 - mae: 0.0022

INFO:root:File 'IE00B87RLX93.csv' loaded, 202 left


   1785/Unknown - 1392s 766ms/step - loss: 1.6373e-05 - mae: 0.0022

INFO:root:File 'IE00BN4Q1675.csv' loaded, 201 left


   1786/Unknown - 1392s 766ms/step - loss: 1.6367e-05 - mae: 0.0022

INFO:root:File 'IE00BLCHJZ35.csv' loaded, 200 left


   1790/Unknown - 1395s 766ms/step - loss: 1.6349e-05 - mae: 0.0022

INFO:root:File 'IE00B6YX5C33.csv' loaded, 199 left


   1791/Unknown - 1397s 766ms/step - loss: 1.6343e-05 - mae: 0.0022

INFO:root:File 'IE0004U3TX15.csv' loaded, 198 left


   1792/Unknown - 1398s 766ms/step - loss: 1.6336e-05 - mae: 0.0022

INFO:root:File 'IE00B7KMNP07.csv' loaded, 197 left


   1793/Unknown - 1399s 767ms/step - loss: 1.6329e-05 - mae: 0.0022

INFO:root:File 'IE00BD4TXV59.csv' loaded in retry loop, 196 left


   1810/Unknown - 1410s 765ms/step - loss: 1.6246e-05 - mae: 0.0022

INFO:root:File 'IE0031442068.csv' loaded, 195 left


   1812/Unknown - 1414s 767ms/step - loss: 1.6271e-05 - mae: 0.0022

INFO:root:File 'IE00BHZPJ783.csv' loaded, 194 left


   1820/Unknown - 1419s 766ms/step - loss: 1.6225e-05 - mae: 0.0022

INFO:root:File 'IE00B43HR379.csv' loaded, 193 left


   1832/Unknown - 1426s 765ms/step - loss: 1.6175e-05 - mae: 0.0022

INFO:root:File 'IE00B2QWCY14.csv' loaded, 192 left


   1837/Unknown - 1431s 766ms/step - loss: 1.6165e-05 - mae: 0.0022

INFO:root:File 'IE00B3VTMJ91.csv' loaded, 191 left


   1846/Unknown - 1438s 766ms/step - loss: 1.6216e-05 - mae: 0.0022

INFO:root:File 'IE00BLCHJ534.csv' loaded, 190 left


   1849/Unknown - 1440s 765ms/step - loss: 1.6201e-05 - mae: 0.0022

INFO:root:File 'IE000L2ZNB07.csv' loaded, 189 left


   1850/Unknown - 1440s 765ms/step - loss: 1.6197e-05 - mae: 0.0022

INFO:root:File 'IE00B77D4428.csv' loaded, 188 left


   1851/Unknown - 1442s 766ms/step - loss: 1.6190e-05 - mae: 0.0022

INFO:root:File 'IE00BLCHJN13.csv' loaded, 187 left


   1852/Unknown - 1443s 766ms/step - loss: 1.6184e-05 - mae: 0.0022

INFO:root:File 'IE00BMDPBZ72.csv' loaded, 186 left


   1856/Unknown - 1446s 766ms/step - loss: 1.6159e-05 - mae: 0.0022

INFO:root:File 'LU1437016204.csv' loaded, 185 left


   1860/Unknown - 1449s 766ms/step - loss: 1.6162e-05 - mae: 0.0022

INFO:root:File 'LU1327051279.csv' loaded, 184 left


   1863/Unknown - 1451s 766ms/step - loss: 1.6154e-05 - mae: 0.0022

INFO:root:File 'DE000A0Q4RZ9.csv' loaded, 183 left


   1865/Unknown - 1454s 766ms/step - loss: 1.6173e-05 - mae: 0.0022

INFO:root:File 'IE00BHBFDF83.csv' loaded, 182 left


   1890/Unknown - 1469s 764ms/step - loss: 1.6091e-05 - mae: 0.0022

INFO:root:File 'LU1686830909.csv' loaded, 181 left


   1899/Unknown - 1476s 764ms/step - loss: 1.6073e-05 - mae: 0.0022

INFO:root:File 'LU1481203070.csv' loaded, 180 left


   1910/Unknown - 1483s 764ms/step - loss: 1.6080e-05 - mae: 0.0022

INFO:root:File 'LU1852212965.csv' loaded, 179 left


   1913/Unknown - 1485s 764ms/step - loss: 1.6072e-05 - mae: 0.0022

INFO:root:File 'LU1861137484.csv' loaded, 178 left


   1914/Unknown - 1486s 764ms/step - loss: 1.6126e-05 - mae: 0.0022

INFO:root:File 'LU0671493277.csv' loaded, 177 left


   1915/Unknown - 1489s 764ms/step - loss: 1.6152e-05 - mae: 0.0022

INFO:root:File 'IE00B466KX20.csv' loaded, 176 left


   1927/Unknown - 1497s 764ms/step - loss: 1.6297e-05 - mae: 0.0022

INFO:root:File 'IE00BCLWRB83.csv' loaded, 175 left


   1930/Unknown - 1500s 764ms/step - loss: 1.6421e-05 - mae: 0.0022

INFO:root:File 'DE0006289382.csv' loaded, 174 left


   1932/Unknown - 1503s 765ms/step - loss: 1.6599e-05 - mae: 0.0022

INFO:root:File 'IE00B53HP851.csv' loaded, 173 left


   1937/Unknown - 1508s 766ms/step - loss: 1.7563e-05 - mae: 0.0022

INFO:root:File 'LU1681046691.csv' loaded, 172 left


   1944/Unknown - 1513s 766ms/step - loss: 1.8853e-05 - mae: 0.0022

INFO:root:File 'IE00B23D8X81.csv' loaded, 171 left


   1958/Unknown - 1523s 766ms/step - loss: 2.0488e-05 - mae: 0.0022

INFO:root:File 'LU1650488817.csv' loaded, 170 left


   1969/Unknown - 1530s 765ms/step - loss: 2.1769e-05 - mae: 0.0023

INFO:root:File 'IE00B4WXJJ64.csv' loaded, 169 left


   1977/Unknown - 1536s 765ms/step - loss: 2.2051e-05 - mae: 0.0023

INFO:root:File 'DE000A0Q4R69.csv' loaded, 168 left


   1979/Unknown - 1537s 764ms/step - loss: 2.2038e-05 - mae: 0.0023

INFO:root:File 'IE00BJRCLL96.csv' loaded, 167 left


   1980/Unknown - 1538s 764ms/step - loss: 2.2029e-05 - mae: 0.0023

INFO:root:File 'IE00BLP53M98.csv' loaded, 166 left


   1985/Unknown - 1541s 764ms/step - loss: 2.2011e-05 - mae: 0.0023

INFO:root:File 'IE00BMH5XY61.csv' loaded, 165 left


   1990/Unknown - 1544s 764ms/step - loss: 2.1967e-05 - mae: 0.0023

INFO:root:File 'IE00BCBJF711.csv' loaded, 164 left


   1991/Unknown - 1545s 764ms/step - loss: 2.1958e-05 - mae: 0.0023

INFO:root:File 'IE00B1FZSB30.csv' loaded, 163 left


   1998/Unknown - 1552s 765ms/step - loss: 2.1922e-05 - mae: 0.0023

INFO:root:File 'IE00BN4PXC48.csv' loaded, 162 left


   2000/Unknown - 1553s 764ms/step - loss: 2.1907e-05 - mae: 0.0023

INFO:root:2023-03-30 06:59:50.785078
INFO:root:Saved model to '/content/bigdata/chk/FPNWithAttentionBiggerTimebased_2_FutureOnly_60days_GPU_128LB/cp_daily_valid_00_02000/model.h5'
INFO:root:Saved optimizer config to '/content/bigdata/chk/FPNWithAttentionBiggerTimebased_2_FutureOnly_60days_GPU_128LB/cp_daily_valid_00_02000/c.pickle'
INFO:root:Saved optimizer weights to '/content/bigdata/chk/FPNWithAttentionBiggerTimebased_2_FutureOnly_60days_GPU_128LB/cp_daily_valid_00_02000/w.pickle'
INFO:root:Did a gc collect: 0


   2005/Unknown - 1561s 766ms/step - loss: 2.1863e-05 - mae: 0.0023

INFO:root:File 'LU1829218319.csv' loaded, 161 left


   2006/Unknown - 1563s 767ms/step - loss: 2.1855e-05 - mae: 0.0023

INFO:root:File 'IE00BRKWGL70.csv' loaded, 160 left


   2007/Unknown - 1564s 767ms/step - loss: 2.1846e-05 - mae: 0.0023

INFO:root:File 'IE00B02KXH56.csv' loaded, 159 left


   2030/Unknown - 1580s 766ms/step - loss: 2.1658e-05 - mae: 0.0023

INFO:root:File 'NL0010408704.csv' loaded, 158 left


   2040/Unknown - 1587s 766ms/step - loss: 2.1807e-05 - mae: 0.0023

INFO:root:File 'LU1861136247.csv' loaded, 157 left


   2047/Unknown - 1592s 766ms/step - loss: 2.1759e-05 - mae: 0.0023

INFO:root:File 'IE00BG8BCY43.csv' loaded, 156 left


   2049/Unknown - 1593s 766ms/step - loss: 2.1744e-05 - mae: 0.0023

INFO:root:File 'IE00BP2C1V62.csv' loaded, 155 left


   2051/Unknown - 1595s 766ms/step - loss: 2.1727e-05 - mae: 0.0023

INFO:root:File 'LU1686832194.csv' loaded, 154 left


   2052/Unknown - 1596s 766ms/step - loss: 2.1718e-05 - mae: 0.0023

INFO:root:File 'LU2250132763.csv' loaded, 153 left


   2057/Unknown - 1599s 765ms/step - loss: 2.1784e-05 - mae: 0.0023

INFO:root:File 'LU0950674928.csv' loaded, 152 left


   2060/Unknown - 1601s 765ms/step - loss: 2.1886e-05 - mae: 0.0023

INFO:root:File 'IE00BKSBGV72.csv' loaded, 151 left


   2063/Unknown - 1603s 765ms/step - loss: 2.1861e-05 - mae: 0.0023

INFO:root:File 'IE00B4M7GH52.csv' loaded, 150 left


   2067/Unknown - 1607s 765ms/step - loss: 2.2063e-05 - mae: 0.0023

INFO:root:File 'DE000A0F5UE8.csv' loaded, 149 left


   2070/Unknown - 1611s 766ms/step - loss: 2.2042e-05 - mae: 0.0023

INFO:root:File 'IE00B9KNR336.csv' loaded, 148 left


   2073/Unknown - 1614s 767ms/step - loss: 2.2238e-05 - mae: 0.0023

INFO:root:File 'IE00B0M63623.csv' loaded, 147 left


   2082/Unknown - 1621s 767ms/step - loss: 2.2191e-05 - mae: 0.0023

INFO:root:File 'IE00B3LK4Z20.csv' loaded, 146 left


   2084/Unknown - 1624s 767ms/step - loss: 2.2175e-05 - mae: 0.0023

INFO:root:File 'IE00BYXPXL17.csv' loaded, 145 left


   2094/Unknown - 1630s 767ms/step - loss: 2.2094e-05 - mae: 0.0022

INFO:root:File 'LU1829218749.csv' loaded, 144 left


   2110/Unknown - 1641s 766ms/step - loss: 2.2012e-05 - mae: 0.0022

INFO:root:File 'FR0010296061.csv' loaded, 143 left


   2115/Unknown - 1646s 767ms/step - loss: 2.1988e-05 - mae: 0.0022

INFO:root:File 'LU0392494992.csv' loaded, 142 left


   2124/Unknown - 1653s 767ms/step - loss: 2.1936e-05 - mae: 0.0022

INFO:root:File 'IE00BHZRR147.csv' loaded, 141 left


   2130/Unknown - 1657s 766ms/step - loss: 2.1895e-05 - mae: 0.0022

INFO:root:File 'DE0006289473.csv' loaded, 140 left


   2142/Unknown - 1666s 767ms/step - loss: 2.1800e-05 - mae: 0.0022

INFO:root:File 'IE000M0ZXLY9.csv' loaded, 139 left


   2143/Unknown - 1667s 766ms/step - loss: 2.1791e-05 - mae: 0.0022

INFO:root:File 'IE00BN76Y761.csv' loaded, 138 left


   2144/Unknown - 1668s 766ms/step - loss: 2.1783e-05 - mae: 0.0022

INFO:root:File 'LU2297533809.csv' loaded, 137 left


   2151/Unknown - 1672s 766ms/step - loss: 2.1739e-05 - mae: 0.0022

INFO:root:File 'FR0011720911.csv' loaded, 136 left


   2152/Unknown - 1673s 766ms/step - loss: 2.1735e-05 - mae: 0.0022

INFO:root:File 'LU1681047236.csv' loaded, 135 left


   2161/Unknown - 1681s 766ms/step - loss: 2.1677e-05 - mae: 0.0022

INFO:root:File 'LU1215451524.csv' loaded, 134 left


   2170/Unknown - 1687s 766ms/step - loss: 2.1622e-05 - mae: 0.0022

INFO:root:File 'LU2082998670.csv' loaded, 133 left


   2182/Unknown - 1694s 765ms/step - loss: 2.1553e-05 - mae: 0.0022

INFO:root:File 'IE00B66F4759.csv' loaded, 132 left


   2190/Unknown - 1700s 765ms/step - loss: 2.1534e-05 - mae: 0.0022

INFO:root:File 'IE00B4K6B022.csv' loaded, 131 left


   2194/Unknown - 1704s 765ms/step - loss: 2.1512e-05 - mae: 0.0022

INFO:root:File 'IE00BK5BQY34.csv' loaded, 130 left


   2197/Unknown - 1706s 765ms/step - loss: 2.1493e-05 - mae: 0.0022

INFO:root:File 'IE00BP3QZ601.csv' loaded, 129 left


   2202/Unknown - 1710s 765ms/step - loss: 2.1458e-05 - mae: 0.0022

INFO:root:File 'LU2082998324.csv' loaded, 128 left


   2205/Unknown - 1712s 765ms/step - loss: 2.1437e-05 - mae: 0.0022

INFO:root:File 'LU1287023003.csv' loaded, 127 left


   2213/Unknown - 1718s 765ms/step - loss: 2.1396e-05 - mae: 0.0022

INFO:root:File 'IE000GOJO2A3.csv' loaded, 126 left
INFO:root:File 'IE00B3VWN179.csv' loaded, 125 left


   2215/Unknown - 1721s 766ms/step - loss: 2.1391e-05 - mae: 0.0022

INFO:root:File 'IE00BKY59G90.csv' loaded in retry loop, 124 left


   2225/Unknown - 1727s 765ms/step - loss: 2.1343e-05 - mae: 0.0022

INFO:root:File 'DE000A0Q4R28.csv' loaded, 123 left


   2231/Unknown - 1733s 766ms/step - loss: 2.1301e-05 - mae: 0.0022

INFO:root:File 'IE00BYVJRR92.csv' loaded, 122 left


   2240/Unknown - 1739s 766ms/step - loss: 2.1239e-05 - mae: 0.0022

INFO:root:File 'DE0005933923.csv' loaded, 121 left


   2242/Unknown - 1743s 767ms/step - loss: 2.1225e-05 - mae: 0.0022

INFO:root:File 'IE00BFZXGZ54.csv' loaded, 120 left


   2250/Unknown - 1748s 766ms/step - loss: 2.1176e-05 - mae: 0.0022

INFO:root:File 'DE000ETFL011.csv' loaded, 119 left


   2263/Unknown - 1758s 766ms/step - loss: 2.1090e-05 - mae: 0.0022

INFO:root:File 'LU2082999058.csv' loaded, 118 left


   2265/Unknown - 1759s 766ms/step - loss: 2.1076e-05 - mae: 0.0022

INFO:root:File 'DE000A0Q4R02.csv' loaded, 117 left


   2267/Unknown - 1763s 767ms/step - loss: 2.1063e-05 - mae: 0.0022

INFO:root:File 'IE000BPQIAA3.csv' loaded, 116 left


   2268/Unknown - 1764s 767ms/step - loss: 2.1056e-05 - mae: 0.0022

INFO:root:File 'IE000XFORJ80.csv' loaded, 115 left


   2271/Unknown - 1766s 767ms/step - loss: 2.1034e-05 - mae: 0.0022

INFO:root:File 'LU1931975152.csv' loaded, 114 left


   2275/Unknown - 1768s 767ms/step - loss: 2.1007e-05 - mae: 0.0022

INFO:root:File 'IE00B23D8S39.csv' loaded, 113 left


   2280/Unknown - 1773s 767ms/step - loss: 2.0983e-05 - mae: 0.0022

INFO:root:File 'IE00BFNM3C07.csv' loaded, 112 left


   2290/Unknown - 1780s 766ms/step - loss: 2.0937e-05 - mae: 0.0022

INFO:root:File 'LU1861132840.csv' loaded, 111 left


   2292/Unknown - 1781s 766ms/step - loss: 2.0925e-05 - mae: 0.0022

INFO:root:File 'IE00B53L4350.csv' loaded, 110 left


   2303/Unknown - 1789s 766ms/step - loss: 2.0882e-05 - mae: 0.0022

INFO:root:File 'LU2265794276.csv' loaded, 109 left


   2312/Unknown - 1795s 766ms/step - loss: 2.0838e-05 - mae: 0.0022

INFO:root:File 'LU1681045370.csv' loaded, 108 left


   2313/Unknown - 1796s 766ms/step - loss: 2.0836e-05 - mae: 0.0022

INFO:root:File 'IE00B5MJYC95.csv' loaded, 107 left


   2334/Unknown - 1811s 765ms/step - loss: 2.0782e-05 - mae: 0.0022

INFO:root:File 'LU0908501488.csv' loaded, 106 left


   2341/Unknown - 1815s 765ms/step - loss: 2.0740e-05 - mae: 0.0022

INFO:root:File 'IE00BZ0G8C04.csv' loaded, 105 left


   2346/Unknown - 1819s 765ms/step - loss: 2.0714e-05 - mae: 0.0022

INFO:root:File 'IE00BD1F4L37.csv' loaded, 104 left


   2360/Unknown - 1828s 764ms/step - loss: 2.0635e-05 - mae: 0.0022

INFO:root:File 'IE000QUOSE01.csv' loaded, 103 left


   2361/Unknown - 1828s 764ms/step - loss: 2.0631e-05 - mae: 0.0022

INFO:root:File 'IE00BDZZTM54.csv' loaded, 102 left


   2363/Unknown - 1830s 764ms/step - loss: 2.0620e-05 - mae: 0.0022

INFO:root:File 'IE00BFNM3N12.csv' loaded, 101 left


   2365/Unknown - 1832s 764ms/step - loss: 2.0607e-05 - mae: 0.0022

INFO:root:File 'IE00BCLWRD08.csv' loaded, 100 left


   2380/Unknown - 1841s 763ms/step - loss: 2.0509e-05 - mae: 0.0022

INFO:root:File 'DE000ETFL383.csv' loaded, 99 left


   2381/Unknown - 1843s 764ms/step - loss: 2.0503e-05 - mae: 0.0022

INFO:root:File 'LU0488317701.csv' loaded, 98 left


   2382/Unknown - 1845s 764ms/step - loss: 2.0496e-05 - mae: 0.0022

INFO:root:File 'IE00BP3QZ825.csv' loaded, 97 left


   2383/Unknown - 1847s 765ms/step - loss: 2.0488e-05 - mae: 0.0022

INFO:root:File 'IE00BLSN7P11.csv' loaded, 96 left


   2385/Unknown - 1849s 765ms/step - loss: 2.0474e-05 - mae: 0.0022

INFO:root:File 'LU0378437502.csv' loaded, 95 left


   2389/Unknown - 1853s 766ms/step - loss: 2.0447e-05 - mae: 0.0022

INFO:root:File 'IE00B0M63730.csv' loaded, 94 left


   2390/Unknown - 1855s 766ms/step - loss: 2.0440e-05 - mae: 0.0022

INFO:root:File 'LU1861138961.csv' loaded, 93 left


   2391/Unknown - 1857s 767ms/step - loss: 2.0433e-05 - mae: 0.0022

INFO:root:File 'IE00BJP26D89.csv' loaded in retry loop, 92 left


   2405/Unknown - 1866s 766ms/step - loss: 2.0345e-05 - mae: 0.0022

INFO:root:File 'DE0006289465.csv' loaded, 91 left


   2411/Unknown - 1872s 766ms/step - loss: 2.0313e-05 - mae: 0.0022

INFO:root:File 'DE000ETF9090.csv' loaded, 90 left


   2417/Unknown - 1875s 766ms/step - loss: 2.0278e-05 - mae: 0.0022

INFO:root:File 'LU0599612842.csv' loaded in retry loop, 89 left


   2426/Unknown - 1882s 766ms/step - loss: 2.0396e-05 - mae: 0.0022

INFO:root:File 'IE00BKX55S42.csv' loaded, 88 left


   2427/Unknown - 1883s 766ms/step - loss: 2.0418e-05 - mae: 0.0022

INFO:root:File 'IE00B5MTY077.csv' loaded, 87 left


   2447/Unknown - 1897s 765ms/step - loss: 2.0785e-05 - mae: 0.0022

INFO:root:File 'IE00B1FZSC47.csv' loaded, 86 left


   2451/Unknown - 1901s 766ms/step - loss: 2.0765e-05 - mae: 0.0022

INFO:root:File 'IE00B1FZS244.csv' loaded, 85 left


   2466/Unknown - 1912s 765ms/step - loss: 2.0701e-05 - mae: 0.0022

INFO:root:File 'IE00B6R52143.csv' loaded, 84 left


   2472/Unknown - 1917s 766ms/step - loss: 2.0693e-05 - mae: 0.0022

INFO:root:File 'FR0010245514.csv' loaded, 83 left


   2481/Unknown - 1924s 766ms/step - loss: 2.0655e-05 - mae: 0.0022

INFO:root:File 'LU0721553864.csv' loaded, 82 left


   2486/Unknown - 1929s 766ms/step - loss: 2.0623e-05 - mae: 0.0022

INFO:root:File 'IE00BDFC6Q91.csv' loaded, 81 left


   2502/Unknown - 1938s 765ms/step - loss: 2.0534e-05 - mae: 0.0022

INFO:root:File 'LU1484799769.csv' loaded, 80 left


   2513/Unknown - 1945s 764ms/step - loss: 2.0467e-05 - mae: 0.0022

INFO:root:File 'IE000UQND7H4.csv' loaded, 79 left


   2514/Unknown - 1946s 764ms/step - loss: 2.0462e-05 - mae: 0.0022

INFO:root:File 'DE000A0H08D2.csv' loaded, 78 left


   2518/Unknown - 1950s 765ms/step - loss: 2.0440e-05 - mae: 0.0022

INFO:root:File 'LU1563454310.csv' loaded, 77 left


   2529/Unknown - 1957s 764ms/step - loss: 2.0375e-05 - mae: 0.0022

INFO:root:File 'IE000BWKUES1.csv' loaded, 76 left


   2534/Unknown - 1960s 764ms/step - loss: 2.0344e-05 - mae: 0.0022

INFO:root:File 'LU2008763935.csv' loaded, 75 left


   2535/Unknown - 1961s 764ms/step - loss: 2.0338e-05 - mae: 0.0022

INFO:root:File 'IE00BYZK4776.csv' loaded, 74 left


   2537/Unknown - 1963s 764ms/step - loss: 2.0326e-05 - mae: 0.0022

INFO:root:File 'IE0001VXZTV7.csv' loaded, 73 left
INFO:root:File 'IE00B459R192.csv' loaded in retry loop, 72 left


   2541/Unknown - 1967s 764ms/step - loss: 2.0300e-05 - mae: 0.0022

INFO:root:File 'IE00BFWXDY69.csv' loaded, 71 left


   2542/Unknown - 1968s 764ms/step - loss: 2.0294e-05 - mae: 0.0022

INFO:root:File 'IE00B802KR88.csv' loaded, 70 left


   2549/Unknown - 1973s 764ms/step - loss: 2.0374e-05 - mae: 0.0022

INFO:root:File 'IE00BYZTVV78.csv' loaded, 69 left


   2550/Unknown - 1975s 765ms/step - loss: 2.0370e-05 - mae: 0.0022

INFO:root:File 'DE000A0Q4R85.csv' loaded, 68 left


   2566/Unknown - 1984s 764ms/step - loss: 2.0292e-05 - mae: 0.0022

INFO:root:File 'IE00B539F030.csv' loaded, 67 left


   2567/Unknown - 1987s 764ms/step - loss: 2.0286e-05 - mae: 0.0022

INFO:root:File 'IE00BMH5YF48.csv' loaded, 66 left


   2568/Unknown - 1987s 764ms/step - loss: 2.0280e-05 - mae: 0.0022

INFO:root:File 'IE00BDR55927.csv' loaded, 65 left


   2573/Unknown - 1991s 764ms/step - loss: 2.0275e-05 - mae: 0.0022

INFO:root:File 'DE0005933972.csv' loaded, 64 left


   2574/Unknown - 1992s 764ms/step - loss: 2.0269e-05 - mae: 0.0022

INFO:root:File 'IE00BMP3HG27.csv' loaded, 63 left


   2588/Unknown - 2003s 765ms/step - loss: 2.0245e-05 - mae: 0.0022

INFO:root:File 'IE00B0M62V02.csv' loaded, 62 left


   2596/Unknown - 2010s 765ms/step - loss: 2.0818e-05 - mae: 0.0022

INFO:root:File 'LU1646360971.csv' loaded, 61 left


   2599/Unknown - 2015s 766ms/step - loss: 2.0839e-05 - mae: 0.0022

INFO:root:File 'LU2182388582.csv' loaded, 60 left


   2601/Unknown - 2016s 766ms/step - loss: 2.0832e-05 - mae: 0.0022

INFO:root:File 'IE00BSPLC413.csv' loaded, 59 left


   2606/Unknown - 2020s 766ms/step - loss: 2.1014e-05 - mae: 0.0022

INFO:root:File 'LU1691909508.csv' loaded, 58 left


   2612/Unknown - 2024s 765ms/step - loss: 2.0992e-05 - mae: 0.0022

INFO:root:File 'LU1079841273.csv' loaded, 57 left


   2619/Unknown - 2029s 765ms/step - loss: 2.1155e-05 - mae: 0.0022

INFO:root:File 'LU1602144906.csv' loaded, 56 left


   2635/Unknown - 2039s 764ms/step - loss: 2.1063e-05 - mae: 0.0022

INFO:root:File 'FR0007052782.csv' loaded, 55 left


   2639/Unknown - 2044s 765ms/step - loss: 2.1042e-05 - mae: 0.0022

INFO:root:File 'IE000NRGX9M3.csv' loaded, 54 left


   2640/Unknown - 2045s 765ms/step - loss: 2.1036e-05 - mae: 0.0022

INFO:root:File 'IE00BMCZLH06.csv' loaded, 53 left


   2645/Unknown - 2048s 765ms/step - loss: 2.1008e-05 - mae: 0.0022

INFO:root:File 'IE00BJQRDK83.csv' loaded, 52 left


   2646/Unknown - 2048s 765ms/step - loss: 2.1002e-05 - mae: 0.0022

INFO:root:File 'LU1681044647.csv' loaded, 51 left


   2652/Unknown - 2054s 765ms/step - loss: 2.0979e-05 - mae: 0.0022

INFO:root:File 'IE00B74DQ490.csv' loaded, 50 left


   2654/Unknown - 2056s 766ms/step - loss: 2.0969e-05 - mae: 0.0022

INFO:root:File 'IE00BK5BC677.csv' loaded, 49 left


   2664/Unknown - 2063s 765ms/step - loss: 2.0914e-05 - mae: 0.0022

INFO:root:File 'LU2082996385.csv' loaded, 48 left


   2673/Unknown - 2068s 764ms/step - loss: 2.0868e-05 - mae: 0.0022

INFO:root:File 'LU1390062831.csv' loaded, 47 left


   2678/Unknown - 2072s 764ms/step - loss: 2.0844e-05 - mae: 0.0022

INFO:root:File 'IE00B4X9L533.csv' loaded, 46 left


   2685/Unknown - 2077s 765ms/step - loss: 2.0814e-05 - mae: 0.0022

INFO:root:File 'LU1805389258.csv' loaded, 45 left


   2696/Unknown - 2084s 764ms/step - loss: 2.0758e-05 - mae: 0.0022

INFO:root:File 'LU1681040736.csv' loaded, 44 left


   2706/Unknown - 2091s 764ms/step - loss: 2.0707e-05 - mae: 0.0022

INFO:root:File 'IE00B9M6SJ31.csv' loaded, 43 left


   2709/Unknown - 2094s 764ms/step - loss: 2.0690e-05 - mae: 0.0022

INFO:root:File 'LU0392496260.csv' loaded, 42 left


   2710/Unknown - 2096s 764ms/step - loss: 2.0685e-05 - mae: 0.0022

INFO:root:File 'IE00BD1F4K20.csv' loaded, 41 left


   2711/Unknown - 2098s 765ms/step - loss: 2.0679e-05 - mae: 0.0022

INFO:root:File 'LU1900068328.csv' loaded, 40 left


   2726/Unknown - 2109s 765ms/step - loss: 2.0596e-05 - mae: 0.0022

INFO:root:File 'IE00BNG8L385.csv' loaded, 39 left


   2735/Unknown - 2115s 764ms/step - loss: 2.0703e-05 - mae: 0.0022

INFO:root:File 'IE00BLCHJH52.csv' loaded, 38 left


   2740/Unknown - 2117s 764ms/step - loss: 2.0959e-05 - mae: 0.0022

INFO:root:File 'LU0136234654.csv' loaded, 37 left


   2744/Unknown - 2123s 765ms/step - loss: 2.0938e-05 - mae: 0.0022

INFO:root:File 'LU1829219127.csv' loaded, 36 left


   2745/Unknown - 2124s 765ms/step - loss: 2.0932e-05 - mae: 0.0022

INFO:root:File 'IE00BNDS1Q47.csv' loaded, 35 left


   2753/Unknown - 2130s 765ms/step - loss: 2.0891e-05 - mae: 0.0022

INFO:root:File 'LU1900065811.csv' loaded, 34 left


   2759/Unknown - 2135s 765ms/step - loss: 2.0862e-05 - mae: 0.0022

INFO:root:File 'LU1681046931.csv' loaded, 33 left


   2760/Unknown - 2138s 766ms/step - loss: 2.0856e-05 - mae: 0.0022

INFO:root:File 'IE00BKX55Q28.csv' loaded, 32 left


   2766/Unknown - 2143s 766ms/step - loss: 2.0822e-05 - mae: 0.0022

INFO:root:File 'LU1681046006.csv' loaded, 31 left


   2788/Unknown - 2157s 765ms/step - loss: 2.0732e-05 - mae: 0.0022

INFO:root:File 'IE00BLCHJB90.csv' loaded, 30 left


   2794/Unknown - 2160s 764ms/step - loss: 2.0701e-05 - mae: 0.0022

INFO:root:File 'LU1974696418.csv' loaded, 29 left


   2804/Unknown - 2166s 764ms/step - loss: 2.0646e-05 - mae: 0.0022

INFO:root:File 'LU1220245556.csv' loaded, 28 left


   2805/Unknown - 2168s 764ms/step - loss: 2.0640e-05 - mae: 0.0022

INFO:root:File 'LU1681042864.csv' loaded, 27 left


   2812/Unknown - 2174s 764ms/step - loss: 2.0603e-05 - mae: 0.0022

INFO:root:File 'IE00B6YX5M31.csv' loaded, 26 left


   2818/Unknown - 2179s 764ms/step - loss: 2.0571e-05 - mae: 0.0022

INFO:root:File 'FR0007054358.csv' loaded, 25 left


   2821/Unknown - 2184s 765ms/step - loss: 2.0554e-05 - mae: 0.0022

INFO:root:File 'DE0005933949.csv' loaded, 24 left


   2841/Unknown - 2198s 765ms/step - loss: 2.0461e-05 - mae: 0.0022

INFO:root:File 'IE00BJ5JNY98.csv' loaded, 23 left


   2847/Unknown - 2202s 765ms/step - loss: 2.0440e-05 - mae: 0.0022

INFO:root:File 'LU0392495023.csv' loaded, 22 left


   2858/Unknown - 2210s 765ms/step - loss: 2.0396e-05 - mae: 0.0022

INFO:root:File 'LU2037748345.csv' loaded, 21 left


   2860/Unknown - 2211s 765ms/step - loss: 2.0391e-05 - mae: 0.0022

INFO:root:File 'LU1169821292.csv' loaded, 20 left


   2871/Unknown - 2218s 764ms/step - loss: 2.0352e-05 - mae: 0.0022

INFO:root:File 'DE000A2QP349.csv' loaded, 19 left


   2873/Unknown - 2219s 764ms/step - loss: 2.0341e-05 - mae: 0.0022

INFO:root:File 'IE00BFXR5T61.csv' loaded, 18 left


   2874/Unknown - 2220s 764ms/step - loss: 2.0337e-05 - mae: 0.0022

INFO:root:File 'IE000YDZG487.csv' loaded, 17 left


   2875/Unknown - 2221s 764ms/step - loss: 2.0331e-05 - mae: 0.0022

INFO:root:File 'IE00BKWQ0G16.csv' loaded, 16 left


   2877/Unknown - 2223s 764ms/step - loss: 2.0320e-05 - mae: 0.0022

INFO:root:File 'LU1615092217.csv' loaded, 15 left


   2880/Unknown - 2225s 764ms/step - loss: 2.0305e-05 - mae: 0.0022

INFO:root:File 'IE00BKWQ0N82.csv' loaded, 14 left


   2884/Unknown - 2229s 764ms/step - loss: 2.0286e-05 - mae: 0.0022

INFO:root:File 'IE00BYYHSQ67.csv' loaded, 13 left


   2896/Unknown - 2236s 764ms/step - loss: 2.0226e-05 - mae: 0.0022

INFO:root:File 'DE0005933956.csv' loaded in retry loop, 12 left


   2907/Unknown - 2246s 764ms/step - loss: 2.0172e-05 - mae: 0.0022

INFO:root:File 'LU2244387457.csv' loaded in retry loop, 11 left


   2914/Unknown - 2250s 764ms/step - loss: 2.0141e-05 - mae: 0.0022

INFO:root:File 'IE00BD9MMD49.csv' loaded, 10 left


   2916/Unknown - 2251s 764ms/step - loss: 2.0129e-05 - mae: 0.0022

INFO:root:File 'LU1974693662.csv' loaded, 9 left


   2920/Unknown - 2254s 763ms/step - loss: 2.0108e-05 - mae: 0.0022

INFO:root:File 'IE00B3FH7618.csv' loaded, 8 left


   2925/Unknown - 2259s 764ms/step - loss: 2.0079e-05 - mae: 0.0022

INFO:root:File 'IE00B3B8Q275.csv' loaded, 7 left


   2926/Unknown - 2261s 764ms/step - loss: 2.0073e-05 - mae: 0.0022

INFO:root:File 'LU1435356149.csv' loaded, 6 left


   2934/Unknown - 2267s 764ms/step - loss: 2.0031e-05 - mae: 0.0022

INFO:root:File 'DE000ETFL581.csv' loaded, 5 left


   2939/Unknown - 2270s 764ms/step - loss: 2.0005e-05 - mae: 0.0022

INFO:root:File 'LU1681048127.csv' loaded, 4 left


   2942/Unknown - 2272s 764ms/step - loss: 1.9993e-05 - mae: 0.0022

INFO:root:File 'IE00B3F81409.csv' loaded, 3 left


   2946/Unknown - 2275s 764ms/step - loss: 1.9972e-05 - mae: 0.0022

INFO:root:File 'IE00BLF7VW10.csv' loaded, 2 left


   2947/Unknown - 2276s 764ms/step - loss: 1.9967e-05 - mae: 0.0022

INFO:root:File 'IE00B1XNHC34.csv' loaded, 1 left


   2957/Unknown - 2284s 764ms/step - loss: 1.9913e-05 - mae: 0.0022

INFO:root:File 'IE00BMH5YL08.csv' loaded, 0 left


   2962/Unknown - 2287s 764ms/step - loss: 1.9886e-05 - mae: 0.0022

   2994/Unknown - 2305s 762ms/step - loss: 2.0428e-05 - mae: 0.0022

2023-03-30 07:12:22.582800: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 1006632960 exceeds 10% of free system memory.
2023-03-30 07:12:22.868290: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 2013265920 exceeds 10% of free system memory.
2023-03-30 07:12:23.367495: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 2013265920 exceeds 10% of free system memory.
2023-03-30 07:12:23.952016: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 4026531840 exceeds 10% of free system memory.
INFO:root:2023-03-30 07:12:25.360208
INFO:root:Saved model to '/content/bigdata/chk/FPNWithAttentionBiggerTimebased_2_FutureOnly_60days_GPU_128LB/cp_daily_valid_00_end/model.h5'
INFO:root:Saved optimizer config to '/content/bigdata/chk/FPNWithAttentionBiggerTimebased_2_FutureOnly_60days_GPU_128LB/cp_daily_valid_00_end/c.pickle'
INFO:root:Saved optimizer weights to '/content/bigdata/chk/FPNWithAttentionBiggerTimebased_2_FutureOnl

2994/2994 [==============================] - 2316s 765ms/step - loss: 2.0428e-05 - mae: 0.0022


In [54]:
model.optimizer.learning_rate = 5e-6

In [55]:
model.optimizer.learning_rate

<tf.Variable 'Adam/learning_rate:0' shape=() dtype=float32, numpy=5e-06>

In [56]:
epoch_add = 1

cc = CustomCallback(checkpoint_path = CHECKPOINT_PATH,
                    model_name = CHKPNT_NAME,
                    save_freq = CALLBACK_EVERY_N_BATCHES,
                    val_freq = CALLBACK_EVERY_N_BATCHES,
                    epoch_add = epoch_add)

In [ ]:
model.fit(tfGenTraining,
          epochs=5,
          verbose = 1,
          callbacks=[tensorboard_callback, cc])

Epoch 1/5


INFO:root:File 'IE00B6X2VY59.csv' loaded, 531 left
INFO:root:File 'IE00BYXVGZ48.csv' loaded, 530 left
INFO:root:File 'DE000A0F5UF5.csv' loaded, 529 left
INFO:root:File 'DE000ETFL441.csv' loaded, 528 left
INFO:root:File 'LU1781541179.csv' loaded, 527 left
INFO:root:File 'LU1650487926.csv' loaded, 526 left
INFO:root:File 'LU1285960032.csv' loaded, 525 left
INFO:root:File 'IE00B1FZSD53.csv' loaded, 524 left


      3/Unknown - 15s 570ms/step - loss: 9.7085e-06 - mae: 0.0023

INFO:root:File 'IE00B5KQNG97.csv' loaded, 523 left


      4/Unknown - 16s 641ms/step - loss: 8.4052e-06 - mae: 0.0021

2023-03-30 07:12:49.740237: I tensorflow/core/profiler/lib/profiler_session.cc:101] Profiler session initializing.
2023-03-30 07:12:49.740263: I tensorflow/core/profiler/lib/profiler_session.cc:116] Profiler session started.


      6/Unknown - 18s 960ms/step - loss: 7.0151e-06 - mae: 0.0019WARNING:tensorflow:Callback method `on_train_batch_end` is slow compared to the batch time (batch time: 0.1540s vs `on_train_batch_end` time: 0.7298s). Check your callbacks.


      8/Unknown - 20s 852ms/step - loss: 6.6504e-06 - mae: 0.0019

INFO:root:File 'IE00BYM31M36.csv' loaded, 522 left


     10/Unknown - 22s 881ms/step - loss: 6.7794e-06 - mae: 0.0019

INFO:root:File 'LU2082996542.csv' loaded, 521 left


     12/Unknown - 23s 861ms/step - loss: 6.6085e-06 - mae: 0.0019

INFO:root:File 'IE00BF4G7076.csv' loaded, 520 left


     15/Unknown - 26s 855ms/step - loss: 6.7369e-06 - mae: 0.0019

INFO:root:File 'IE00BQN1K786.csv' loaded, 519 left


     17/Unknown - 28s 889ms/step - loss: 6.5628e-06 - mae: 0.0019

INFO:root:File 'LU0136240974.csv' loaded, 518 left


     25/Unknown - 35s 906ms/step - loss: 6.3657e-06 - mae: 0.0019

INFO:root:File 'IE00BLDGH447.csv' loaded, 517 left


     27/Unknown - 37s 884ms/step - loss: 6.2927e-06 - mae: 0.0018

INFO:root:File 'IE00BFTWP510.csv' loaded, 516 left


     30/Unknown - 39s 888ms/step - loss: 2.1586e-05 - mae: 0.0020

INFO:root:File 'IE00BQT3WG13.csv' loaded, 515 left


     36/Unknown - 44s 861ms/step - loss: 1.9170e-05 - mae: 0.0020

INFO:root:File 'LU1407888053.csv' loaded, 514 left


     50/Unknown - 53s 796ms/step - loss: 2.3384e-05 - mae: 0.0020

INFO:root:File 'IE00BMYDM794.csv' loaded, 513 left


     57/Unknown - 57s 770ms/step - loss: 2.1708e-05 - mae: 0.0020

INFO:root:File 'IE00B441G979.csv' loaded, 512 left


     58/Unknown - 58s 775ms/step - loss: 2.1421e-05 - mae: 0.0020

INFO:root:File 'IE00B8X9NY41.csv' loaded, 511 left


     60/Unknown - 61s 808ms/step - loss: 2.1006e-05 - mae: 0.0020

INFO:root:File 'IE00BMDH1538.csv' loaded, 510 left


     62/Unknown - 63s 802ms/step - loss: 2.0475e-05 - mae: 0.0020

INFO:root:File 'IE00BLF7VX27.csv' loaded, 509 left


     69/Unknown - 67s 780ms/step - loss: 1.9389e-05 - mae: 0.0020

INFO:root:File 'IE00BYMS5W68.csv' loaded, 508 left


     73/Unknown - 70s 779ms/step - loss: 1.8664e-05 - mae: 0.0020

INFO:root:File 'LU1079842321.csv' loaded, 507 left


     74/Unknown - 70s 776ms/step - loss: 1.8470e-05 - mae: 0.0020

INFO:root:File 'IE00BKVL7778.csv' loaded, 506 left


     75/Unknown - 72s 787ms/step - loss: 1.8291e-05 - mae: 0.0020

INFO:root:File 'LU1681045537.csv' loaded, 505 left


     77/Unknown - 75s 807ms/step - loss: 1.8017e-05 - mae: 0.0020

INFO:root:File 'IE00B60SX287.csv' loaded, 504 left


     88/Unknown - 83s 798ms/step - loss: 1.6681e-05 - mae: 0.0020

INFO:root:File 'IE00BJXRT698.csv' loaded, 503 left


     99/Unknown - 90s 777ms/step - loss: 1.6095e-05 - mae: 0.0020

2023-03-30 07:14:03.023878: I tensorflow/core/profiler/lib/profiler_session.cc:67] Profiler session collecting data.
2023-03-30 07:14:03.027403: I tensorflow/core/profiler/backends/gpu/cupti_tracer.cc:1798] CUPTI activity buffer flushed
2023-03-30 07:14:03.466557: I tensorflow/core/profiler/backends/gpu/cupti_collector.cc:521]  GpuTracer has collected 594721 callback api events and 597478 activity events. 
2023-03-30 07:14:09.147088: I tensorflow/core/profiler/lib/profiler_session.cc:128] Profiler session tear down.
2023-03-30 07:14:14.795064: I tensorflow/core/profiler/rpc/client/save_profile.cc:136] Creating directory: /content/bigdata/log/FPNWithAttentionBiggerTimebased_2_FutureOnly_60days_GPU_128LB20230330-063353/plugins/profile/2023_03_30_07_14_09

2023-03-30 07:14:18.696556: I tensorflow/core/profiler/rpc/client/save_profile.cc:142] Dumped gzipped tool data for trace.json.gz to /content/bigdata/log/FPNWithAttentionBiggerTimebased_2_FutureOnly_60days_GPU_128LB20230330-063353/plugi

    101/Unknown - 112s 982ms/step - loss: 1.5877e-05 - mae: 0.0020

INFO:root:File 'IE00B40B8R38.csv' loaded, 502 left


    104/Unknown - 114s 976ms/step - loss: 1.5562e-05 - mae: 0.0020

INFO:root:File 'IE00BYTH5T38.csv' loaded, 501 left


    106/Unknown - 115s 970ms/step - loss: 1.5363e-05 - mae: 0.0020

INFO:root:File 'IE00077FRP95.csv' loaded, 500 left


    110/Unknown - 118s 955ms/step - loss: 1.4962e-05 - mae: 0.0019

INFO:root:File 'DE0002635273.csv' loaded, 499 left


    112/Unknown - 121s 969ms/step - loss: 1.4910e-05 - mae: 0.0020

INFO:root:File 'IE00B5WHFQ43.csv' loaded, 498 left


    117/Unknown - 126s 966ms/step - loss: 1.4471e-05 - mae: 0.0019

INFO:root:File 'IE00BKVL7D31.csv' loaded, 497 left


    126/Unknown - 131s 939ms/step - loss: 1.3830e-05 - mae: 0.0019

INFO:root:File 'LU2356220926.csv' loaded, 496 left


    132/Unknown - 136s 931ms/step - loss: 1.3425e-05 - mae: 0.0019

INFO:root:File 'IE00BYZK4883.csv' loaded, 495 left


    133/Unknown - 136s 928ms/step - loss: 1.3359e-05 - mae: 0.0019

INFO:root:File 'IE00B4YBJ215.csv' loaded, 494 left


    134/Unknown - 139s 942ms/step - loss: 1.3298e-05 - mae: 0.0019

INFO:root:File 'IE00BMDKNW35.csv' loaded, 493 left


    136/Unknown - 140s 939ms/step - loss: 1.3186e-05 - mae: 0.0019

INFO:root:File 'LU1769088581.csv' loaded, 492 left


    141/Unknown - 144s 929ms/step - loss: 1.2963e-05 - mae: 0.0019

INFO:root:File 'IE00B6YX5B26.csv' loaded, 491 left


    149/Unknown - 150s 920ms/step - loss: 1.2456e-05 - mae: 0.0019

INFO:root:File 'LU2023678449.csv' loaded, 490 left


    154/Unknown - 153s 910ms/step - loss: 1.2234e-05 - mae: 0.0019

INFO:root:File 'LU1953188833.csv' loaded, 489 left


    162/Unknown - 158s 896ms/step - loss: 1.2011e-05 - mae: 0.0019

INFO:root:File 'LU1861134382.csv' loaded, 488 left


    164/Unknown - 159s 894ms/step - loss: 1.2001e-05 - mae: 0.0019

INFO:root:File 'IE00BLRPN388.csv' loaded, 487 left


    166/Unknown - 161s 891ms/step - loss: 1.2045e-05 - mae: 0.0019

INFO:root:File 'LU1781540957.csv' loaded, 486 left


    172/Unknown - 164s 882ms/step - loss: 1.2365e-05 - mae: 0.0019

INFO:root:File 'IE00BD9MMF62.csv' loaded, 485 left


    175/Unknown - 167s 880ms/step - loss: 1.2706e-05 - mae: 0.0019

INFO:root:File 'LU1806495575.csv' loaded, 484 left


    181/Unknown - 171s 872ms/step - loss: 1.2524e-05 - mae: 0.0019

INFO:root:File 'DE000A0H08N1.csv' loaded, 483 left


    186/Unknown - 177s 880ms/step - loss: 1.2443e-05 - mae: 0.0019

INFO:root:File 'LU2082997946.csv' loaded, 482 left


    193/Unknown - 181s 870ms/step - loss: 1.2320e-05 - mae: 0.0019

INFO:root:File 'DE0002635307.csv' loaded, 481 left


    194/Unknown - 182s 872ms/step - loss: 1.2276e-05 - mae: 0.0019

INFO:root:File 'IE00BWBXM492.csv' loaded, 480 left


    197/Unknown - 187s 883ms/step - loss: 1.2208e-05 - mae: 0.0019

INFO:root:File 'IE00BC7GZJ81.csv' loaded, 479 left


    198/Unknown - 189s 887ms/step - loss: 1.2173e-05 - mae: 0.0019

INFO:root:File 'LU0832436512.csv' loaded, 478 left


    200/Unknown - 191s 892ms/step - loss: 1.2123e-05 - mae: 0.0019

INFO:root:File 'IE00BD3V0B10.csv' loaded, 477 left


    204/Unknown - 194s 888ms/step - loss: 1.2064e-05 - mae: 0.0019

INFO:root:File 'IE00BYTRR863.csv' loaded, 476 left


    210/Unknown - 198s 883ms/step - loss: 1.3392e-05 - mae: 0.0019

INFO:root:File 'DE000ETFL037.csv' loaded, 475 left


    225/Unknown - 209s 871ms/step - loss: 1.8417e-05 - mae: 0.0020

INFO:root:File 'IE00B60SX170.csv' loaded, 474 left


    236/Unknown - 217s 864ms/step - loss: 2.0122e-05 - mae: 0.0020

INFO:root:File 'LU1215454460.csv' loaded, 473 left


    241/Unknown - 221s 862ms/step - loss: 1.9829e-05 - mae: 0.0020

INFO:root:File 'IE00BJXRZ273.csv' loaded, 472 left


    249/Unknown - 225s 854ms/step - loss: 1.9555e-05 - mae: 0.0020

INFO:root:File 'IE00BKT1CS59.csv' loaded, 471 left


    255/Unknown - 229s 848ms/step - loss: 1.9448e-05 - mae: 0.0020

INFO:root:File 'LU1287023342.csv' loaded, 470 left


    257/Unknown - 232s 853ms/step - loss: 1.9511e-05 - mae: 0.0020

INFO:root:File 'LU1981859819.csv' loaded, 469 left


    264/Unknown - 236s 847ms/step - loss: 1.9548e-05 - mae: 0.0020

INFO:root:File 'LU1841731745.csv' loaded, 468 left


    274/Unknown - 243s 839ms/step - loss: 1.9275e-05 - mae: 0.0020

INFO:root:File 'IE000L5NW549.csv' loaded, 467 left


    277/Unknown - 244s 836ms/step - loss: 1.9559e-05 - mae: 0.0020

INFO:root:File 'IE00B4LN9N13.csv' loaded, 466 left


    280/Unknown - 247s 835ms/step - loss: 1.9448e-05 - mae: 0.0020

INFO:root:File 'FR0010869578.csv' loaded, 465 left


    287/Unknown - 252s 835ms/step - loss: 1.9109e-05 - mae: 0.0020

INFO:root:File 'IE00BCRY6557.csv' loaded, 464 left


    293/Unknown - 257s 834ms/step - loss: 1.8809e-05 - mae: 0.0020

INFO:root:File 'LU2090062949.csv' loaded, 463 left


    297/Unknown - 260s 831ms/step - loss: 1.8619e-05 - mae: 0.0020

INFO:root:File 'IE00B5M1WJ87.csv' loaded, 462 left


    300/Unknown - 263s 833ms/step - loss: 1.8474e-05 - mae: 0.0020

INFO:root:File 'IE00B1TXHL60.csv' loaded, 461 left


    303/Unknown - 267s 837ms/step - loss: 1.9786e-05 - mae: 0.0020

INFO:root:File 'IE00BMQ8YK98.csv' loaded, 460 left


    305/Unknown - 268s 836ms/step - loss: 1.9724e-05 - mae: 0.0020

INFO:root:File 'IE00BKWQ0D84.csv' loaded, 459 left


    308/Unknown - 270s 836ms/step - loss: 1.9618e-05 - mae: 0.0020

INFO:root:File 'LU1525418643.csv' loaded, 458 left


    309/Unknown - 272s 837ms/step - loss: 1.9568e-05 - mae: 0.0020

INFO:root:File 'IE00BJK9H753.csv' loaded, 457 left


    328/Unknown - 283s 824ms/step - loss: 1.8769e-05 - mae: 0.0020

INFO:root:File 'LU2082997359.csv' loaded, 456 left


    332/Unknown - 286s 821ms/step - loss: 1.8630e-05 - mae: 0.0020

INFO:root:File 'IE00B6YX5L24.csv' loaded, 455 left


    339/Unknown - 291s 820ms/step - loss: 1.8556e-05 - mae: 0.0020

INFO:root:File 'LU2082996898.csv' loaded, 454 left


    340/Unknown - 292s 820ms/step - loss: 1.8572e-05 - mae: 0.0020

INFO:root:File 'IE00B3B8PX14.csv' loaded, 453 left


    342/Unknown - 294s 823ms/step - loss: 1.8878e-05 - mae: 0.0020

INFO:root:File 'IE00B02KXL92.csv' loaded, 452 left


    350/Unknown - 302s 825ms/step - loss: 2.1505e-05 - mae: 0.0020

INFO:root:File 'LU1681041205.csv' loaded, 451 left


    351/Unknown - 303s 826ms/step - loss: 2.1470e-05 - mae: 0.0020

INFO:root:File 'IE00BHZPJ015.csv' loaded, 450 left


    352/Unknown - 305s 829ms/step - loss: 2.1426e-05 - mae: 0.0020

INFO:root:File 'LU0959210278.csv' loaded, 449 left


    358/Unknown - 310s 829ms/step - loss: 2.1686e-05 - mae: 0.0021

INFO:root:File 'IE000KPJJWM6.csv' loaded, 448 left
INFO:root:File 'IE00BKWQ0M75.csv' loaded, 447 left


    371/Unknown - 318s 822ms/step - loss: 2.3965e-05 - mae: 0.0021

INFO:root:File 'IE000NDWFGA5.csv' loaded, 446 left


    374/Unknown - 320s 820ms/step - loss: 2.3807e-05 - mae: 0.0021

INFO:root:File 'IE00BYSZ5R67.csv' loaded, 445 left


    389/Unknown - 329s 813ms/step - loss: 2.3122e-05 - mae: 0.0021

INFO:root:File 'IE00BGJWWY63.csv' loaded, 444 left


    392/Unknown - 331s 812ms/step - loss: 2.2983e-05 - mae: 0.0021

INFO:root:File 'IE00BJK9HD13.csv' loaded, 443 left


    403/Unknown - 338s 806ms/step - loss: 2.2535e-05 - mae: 0.0021

INFO:root:File 'IE00BMH5Y871.csv' loaded, 442 left


    404/Unknown - 338s 806ms/step - loss: 2.2494e-05 - mae: 0.0021

INFO:root:File 'IE00BYV1Y969.csv' loaded, 441 left


    406/Unknown - 340s 806ms/step - loss: 2.2407e-05 - mae: 0.0021

In [ ]:
# A python generator function has to be applied on the dataStream

def pythonGeneratorEval(fileList):
  # Initialize the FileListToDataStream generator
  dataStreamEval= DataStreamCreator.FileListToDataStream(fileList = fileList,
                                                      batch_size = BATCH_SIZE,
                                                      X_Block_lenght = X_BLOCK_LENGHT,
                                                      y_type_dict=Y_TYPE_DICT,
                                                      shuffle=False,
                                                      parallel_generators = 1,
                                                      random_seed = RANDOM_SEED,
                                                      **DATA_STREAM_PARAMETERS
                                                      )
  
  # This while has to integrated into the FileListToDataStream method
  while True:  
    try:
      ne = next(dataStreamEval)
      _X = ne['X']
      _y = _y = ne['y']#[:,[1,3]]
    
      # Limit the y signal to avoid excess
      _y /= 10.0
      _y = np.clip(_y, -10.0, 10.0)
    
      # 'Blow up' the X array to a 2**n size
      #_X_new = np.zeros((_X.shape[0], _X.shape[1], TARGET_FEATURE_CNT))
      #_X_new[:,:,:_X.shape[2]] = _X

      yield (_X, _y)
    except StopIteration as si:
      logging.warning("StopIteration in pythonGenerator")
      logging.warning(si)
      return

In [ ]:
# Create a Tensorflow dataset out of the python generator, which can be fed to the network
tfGenEval = tf.data.Dataset.from_generator(lambda: pythonGeneratorEval(fileList=[TRAIN_FILES[4]]), 
                                               output_types = (tf.float32, tf.float32),
                                               output_shapes=(
                                                   (BATCH_SIZE, X_BLOCK_LENGHT, TARGET_FEATURE_CNT),
                                                   (BATCH_SIZE, 4)
                                                   )
                                               )
tfGenEval

In [ ]:
# ne[0].shape

In [ ]:
# ne[1].shape

In [ ]:
# plt.plot(ne[1][:,0])

In [ ]:
# plt.plot(ne[1][:,1])

In [ ]:
# evl = model.evaluate(tfGenEval)
# evl

In [ ]:
p = model.predict(tfGenEval)
p *= 10.0
p.shape

In [ ]:
def getPastDataFromGen(genIn, predictedShapeIn):
    it = genIn.as_numpy_iterator()

    y_past_data = np.empty((predictedShapeIn[0], 2))
    i = 0

    try:
        while (ne := next(it)):
            #print(i)
            y_past_data[i:i+ne[1].shape[0],0] = ne[1][:,0]
            y_past_data[i:i+ne[1].shape[0],1] = ne[1][:,2]

            i += ne[1].shape[0]

    except StopIteration:
        pass

    return y_past_data
    
y_past_data = getPastDataFromGen(tfGenEval, p.shape)
y_past_data.shape

In [ ]:
plt.plot(y_past_data[:,0])

In [ ]:
plt.plot(y_past_data[:,1])

In [ ]:
plt.plot(p[:,0])

In [ ]:
plt.plot(p[:,1])

In [ ]:
p.shape

In [ ]:
tickDF = pd.read_csv(TRAIN_FILES[1])
tickDF

In [ ]:
tickDF.shape[0] - p.shape[0]

In [ ]:
tickDFcropped = tickDF.iloc[-p.shape[0]:, :]
tickDFcropped

In [ ]:
# p_dir = p[:,0]
# p_dir_derivation = p[:,1]

p_future = p[:,0]
p_future_derivation = p[:,1]

In [ ]:
# Plot the prediction again, now over the open price
chart_name="Predicted direction of price movement with open price"
fig, ax1 = plt.subplots(figsize=(20,10))
ax1.set_title(chart_name, fontsize=14)

_ = ax1.plot(p_future, color="green", label="Predicted p_future")
_ = ax1.plot(p_future_derivation, color="red", label="Predicted p_future_derivation")
# _ = ax1.plot(p_neutral, color="gray", label="Predicted neutral")

ax2 = ax1.twinx()

ax2.plot(tickDFcropped.loc[:,'open'].values, color="black", label="Price")

ax1.set_xlabel("Timesteps")
ax1.set_ylabel("Direction")
ax2.set_ylabel("Price")

# Show a legend
lines, labels = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax2.legend(lines + lines2, labels + labels2, loc="upper left")

# Save the figure
# fig_name = "FileListToDataStreamExample_" + chart_name.replace(" ", "_").replace("'", "").replace("(", "").replace(")", "") + ".svg"
# plt.savefig(os.path.join(IMG_SAVE_PATH, fig_name), bbox_inches="tight")

In [ ]:
#@title Buy and sell signal thresholds
BUY_SIGNAL_THRESHOLD_FUTURE = 0.15 #@param {type:"number"}
BUY_SIGNAL_THRESHOLD_PAST = 0.01 #@param {type:"number"}

SELL_SIGNAL_THRESHOLD_PAST = 0.1 #@param {type:"number"}

In [ ]:
#@title Plot buy and sell signals
chart_name="Buy and sell signals"
fig, ax1 = plt.subplots(figsize=(20,10))
ax1.set_title(chart_name)

x_datetimes = [datetime.datetime.fromtimestamp(ts) for ts in tickDFcropped.loc[:,'open'].index]

_ = ax1.plot(x_datetimes, tickDFcropped.loc[:,'open'].values, color="black", label="Price", linewidth=2)

# Color area axis
ax2 = ax1.twinx()

# Convert the float value prediction into rising and falling categories
yCategoryFall = p_past_gain >= SELL_SIGNAL_THRESHOLD_PAST
yCategoryRise = (p_future_gain > p_past_gain) & (p_past_gain <= BUY_SIGNAL_THRESHOLD_FUTURE) #(p_future_gain >= BUY_SIGNAL_THRESHOLD_FUTURE)

ax2.fill_between(x_datetimes, yCategoryFall , alpha=0.5, color="red", label="'Buy' signal")
ax2.fill_between(x_datetimes, yCategoryRise , alpha=0.5, color="green", label="'Sell' signal")

# Remove tick marks and set limits for color area axis
ax2.set_yticks([])
ax2.set_ylim(-0.05,1.05)

ax3 = ax1.twinx()
_ = ax3.plot(x_datetimes, p_future_gain, color="blue", label="Predicted future gain")
# _ = ax3.plot(x_datetimes, 10.0*p_dir_derivation, color="red", label="10.0 * Predicted price direction derivation")
# ax3.set_ylim(-1.05,1.05)

ax3.plot([np.min(x_datetimes), np.max(x_datetimes)], [0.0,0.0], color="gray")

# Show a legend
lines, labels = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
lines3, labels3 = ax3.get_legend_handles_labels()
ax2.legend(lines + lines2 + lines3, labels + labels2 + labels3, loc="upper left")

# Save the figure
# fig_name = chart_name.replace(" ", "_").replace("'", "") + ".svg"
# plt.savefig(os.path.join(IMG_SAVE_PATH, fig_name), bbox_inches="tight")

# Add predictions to tick tables

In [ ]:
stop

In [ ]:
# PREDICTED_SAVE_PATH = "/content/dataset/etffancy/PastFutureGainV2/test"

In [ ]:
!mkdir /content/dataset/etffancy/FPNWithAttentionBiggerTimebased_1_FutureOnly
!mkdir /content/dataset/etffancy/FPNWithAttentionBiggerTimebased_1_FutureOnly/test
!mkdir /content/dataset/etffancy/FPNWithAttentionBiggerTimebased_1_FutureOnly/eval

In [ ]:
# Create a Tensorflow dataset out of the python generator, which can be fed to the network
# https://stackoverflow.com/questions/52443273/how-do-you-send-arguments-to-a-generator-function-using-tf-data-dataset-from-gen

#fileList = EVAL_FILES
#PREDICTED_SAVE_PATH = "/content/dataset/etffancy/FPNWithAttentionBiggerTimebased_1_FutureOnly/eval"

fileList = TEST_FILES
PREDICTED_SAVE_PATH = "/content/dataset/etffancy/FPNWithAttentionBiggerTimebased_1_FutureOnly/test"

pd.options.mode.chained_assignment = None  # default='warn'

for file_index in tqdm(range(0, len(fileList))):
    try:
        filename = fileList[file_index]

        logging.info(f"\nFile name: '{filename}' for index {file_index}")

        tfGenEval = tf.data.Dataset.from_generator(lambda: pythonGeneratorEval(fileList=[filename]), 
                                                       output_types = (tf.float32, tf.float32),
                                                       output_shapes=(
                                                           (BATCH_SIZE, X_BLOCK_LENGHT, TARGET_FEATURE_CNT),
                                                           (BATCH_SIZE, 4)
                                                           )
                                                       )
        p = model.predict(tfGenEval, verbose = 0)

        logging.info(f"p.shape: {p.shape}")

        p_future_gain = p[:,0]
        p_future_gain_derivation = p[:,1]
        
        # Load the tick table
        tickDF = pd.read_csv(filename)
        tickDFcropped = tickDF.iloc[-p.shape[0]:, :]
        
        # Add the predicted future gain
        tickDFcropped.loc[:,"p_future_gain"] = p_future_gain
        tickDFcropped.loc[:,"p_future_gain_derivation"] = p_future_gain_derivation
        
        # Get the (known) past data
        y_past_data = getPastDataFromGen(tfGenEval, p.shape)

        # Add the past gain
        tickDFcropped.loc[:,"p_past_gain"] = y_past_data[:,0]
        tickDFcropped.loc[:,"p_past_gain_derivation"] = y_past_data[:,1]

        # Save the DF
        tickDFcropped.to_csv(os.path.join(PREDICTED_SAVE_PATH, filename.split(os.path.sep)[-1]))

        logging.info("Saved the predicted data.")
    except KeyboardInterrupt:
        raise
    except Exception as ex:
        logging.warning(str(ex))

In [ ]:
# Create a Tensorflow dataset out of the python generator, which can be fed to the network
# https://stackoverflow.com/questions/52443273/how-do-you-send-arguments-to-a-generator-function-using-tf-data-dataset-from-gen

fileList = EVAL_FILES
PREDICTED_SAVE_PATH = "/content/dataset/etffancy/FPNWithAttentionBiggerTimebased_1_FutureOnly/eval"

# fileList = TEST_FILES
# PREDICTED_SAVE_PATH = "/content/dataset/etffancy/FPNWithAttentionBiggerTimebased_1_FutureOnly/test"

pd.options.mode.chained_assignment = None  # default='warn'

for file_index in tqdm(range(0, len(fileList))):
    try:
        filename = fileList[file_index]

        logging.info(f"\nFile name: '{filename}' for index {file_index}")

        tfGenEval = tf.data.Dataset.from_generator(lambda: pythonGeneratorEval(fileList=[filename]), 
                                                       output_types = (tf.float32, tf.float32),
                                                       output_shapes=(
                                                           (BATCH_SIZE, X_BLOCK_LENGHT, TARGET_FEATURE_CNT),
                                                           (BATCH_SIZE, 4)
                                                           )
                                                       )
        p = model.predict(tfGenEval, verbose = 0)

        logging.info(f"p.shape: {p.shape}")

        p_future_gain = p[:,0]
        p_future_gain_derivation = p[:,1]
        
        # Load the tick table
        tickDF = pd.read_csv(filename)
        tickDFcropped = tickDF.iloc[-p.shape[0]:, :]
        
        # Add the predicted future gain
        tickDFcropped.loc[:,"p_future_gain"] = p_future_gain
        tickDFcropped.loc[:,"p_future_gain_derivation"] = p_future_gain_derivation
        
        # Get the (known) past data
        y_past_data = getPastDataFromGen(tfGenEval, p.shape)

        # Add the past gain
        tickDFcropped.loc[:,"p_past_gain"] = y_past_data[:,0]
        tickDFcropped.loc[:,"p_past_gain_derivation"] = y_past_data[:,1]

        # Save the DF
        tickDFcropped.to_csv(os.path.join(PREDICTED_SAVE_PATH, filename.split(os.path.sep)[-1]))

        logging.info("Saved the predicted data.")
    except KeyboardInterrupt:
        raise
    except Exception as ex:
        logging.warning(str(ex))